- Idno/Common/Page.php
- Idno/Core/Idno.php
- IdnoPlugins/Firefox/templates/default/account/firefox/manifest.tpl.php
- templates/default/shell.tpl.php
- templates/default/shell/favicon.tpl.php
- templates/default/shell/icons.tpl.php
* Introduces site()->getSiteIcons() that returns an array of icons that can be used in various contexts to render an icon suitable for display, prepopulated with defaults but overridable via event hooks.
* Introduces getIcon() on Page, which will return an icon for the current page context, overridable via icon event hook, or in code.
* Moves default icon/user icon favicon selection controller logic from favicon.tpl.php to Page::getIcon()
* Updates favicon.tpl.php, icons.tpl.php and the firefox manifest to use the new API
TODO: find a nicer way of populating defaults, perhaps via template... putting in links to graphics assets in code seems *wrong*, but couldn't think of a better way at the moment.
Closes #624
> Site icons

- Idno/Core/Plugins.php
Closes #685.
Adds the ability to load plugins directly from the most common checkout, where the plugin directory is actually in a subdirectory of the repo.
It requires a file ```autoloader.php``` in the repo's root, this should contain the following code:
```php
/**
* Support loading of direct checkout.
*/
spl_autoload_register(function($class) {
$class = str_replace('\\', DIRECTORY_SEPARATOR, $class);
$segments = explode(DIRECTORY_SEPARATOR, $class);
$PLUGIN_NAME = $segments[1];
$basedir = dirname(dirname(dirname(__FILE__))) . '/'; 
$file = str_replace($PLUGIN_NAME, basename(dirname(__FILE__)) . "/$PLUGIN_NAME", $class);
\Idno\Core\site()->plugins()->plugins[basename(dirname(__FILE__))] = \Idno\Core\site()->plugins()->plugins[$PLUGIN_NAME]; …
```
> Adds the ability to load plugins from direct checkouts

- Idno/Common/Page.php
- Idno/Core/Session.php
* Gatekeepers no longer forward if this is an api request, as this causes the response code to be lost
* Removes http 401 (which is invalid in this context), and replaces it with 403
> Api gatekeepers

- Idno/Pages/Account/Register.php
- Idno/Pages/Account/Settings.php
- Idno/Pages/Session/Login.php
I accidentally included some visible warnings on my ssl warning patch, which shouldn't have been there (given my assertion that it was API only). Very sorry about that, reverted by this patch.
> Reverting accidental inclusion of visible non-ssl warnings.

- Idno/Caching/Cache.php
- Idno/Caching/EphemeralCache.php
- Idno/Caching/MemoryCache.php
- Idno/Caching/PersistentCache.php
This is the kind of thing I was thinking of Ben. 
There are two basic kinds of caches in this world, ones that are persistent outside of script execution and those that aren't (hence the two families). 
For now, databases should probably cache using the memory cache to do query caching. That said, since Idno uses PDO, it may be easier to cache at the object level. Again, use the memory cache for now, but since every object in the system has a unique ID it should be fairly straight forward to switch that over to a persistent cache of some sort.
Refs #369
> Caching interface (refs #369)

- Idno/Core/MentionClient.php
- Idno/Core/Webmention.php
- external/mention-client-php/src/IndieWeb/MentionClient.php
Since the project no longer has the mentions library as a submodule, we can directly apply the patches submitted to the upstream project rather than wait.
> Known mentions

- Idno/Common/Entity.php
Accept "u-in-reply-to h-cite" in addition to "u-in-reply-to" by checking 
each property value to see if it is a complex value, and extracting the
"url" property if it is.
@benwerd, this fixes #701 (tested on my partner's new Known site!).
Please don't be afraid to tell me if this is not how you would/want to do it.
> Webmention receipt: accept more complex mf2 combinations

- templates/default/entity/content/embed.tpl.php
vimeo video ids are digits only
Without this fix the template will try to embed vimeo user pages like vimeo.com/sasich/videos which results in a vimeo embed with an error message (since "sasich" would not be a valid video id)
> fixed vimeo url regexp

- .gitignore
Refs #744 
config.json no longer excluded, but you may need to add it to the repo in a commit
> Allow fontello config to be added

- Idno/Core/Email.php
- Idno/Pages/Admin/Email.php
- templates/default/admin/email.tpl.php
This patch *should* go some way to fixing #775.
There are three methods for secure connections for sending email - SSL, TLS and STARTTLS. Unfortunately swift seems to conflate the last two.
However, this patch now provides a way of connecting over SSL, which might address the problem. If @neilr8133 tries the patch, it'd be good to get feedback.
> Options for SMTP connections

- Idno/start.php
lets say a user has set a time limit of 40 which is greater than default time limit 30 but still it will cause a lot of problem . So we should force the execution limit to be at least 120 . Any problem on this ?
> force time limit to be min 120

- IdnoPlugins/Like/templates/default/entity/Like/edit.tpl.php
The pageTitle was not populating the input field when editing a Like. Code was pulling 'title' instead of pageTitle
> pageTitle incorrectly named title

- IdnoPlugins/Like/Like.php
The pageTitle was not being saved when entering or updating a Like. The code was checking if $title was empty, but not doing anything if it wasn't. I added an else statement to save it if it isn't empty.
> Change to have pageTitle persist if entered

- Idno/Core/Session.php
Applying some of the recommendations from https://php.net/manual/en/session.security.php
Mainly, setting cookies_secure during secure sessions, but also, enabling strict mode sessions and switching the session ID algorithm from MD5 to sha256
> Secure cookies

- IdnoPlugins/Text/Pages/Edit.php
entry/edit page title was not reflecting whether it is a new post or not. Changed the empty($object) check to check for empty id.
> Change empty object check

- Idno/Core/Session.php
Seems to make sessions more stable.
I've tested with picture upload: before session was logged out after large picture upload, after patch session is preserved.
> Regenerate session ID on privilege change rather than every page load

- Idno/Common/Page.php
- Idno/Pages/Entity/View.php
- Idno/Pages/File/View.php
- Removed duplicate getallheaders shim in \Pages\File\View
- $this->getallheaders() will defer to getallheaders() if it's defined.
Background: had an error referencing getallheaders in Idno/Pages/Entity/View.php on nginx. I changed it to $this-> to fix the error, and thought it would be nice to deduplicate the two shims.
> always use $this->getallheaders() workaround for nginx

- schemas/.htaccess
Minor point, but giving access to schemas makes it trivial to scan for vulnerable versions
> Don't allow browser access to the schema directory

- templates/default/shell.tpl.php
* Only attempt loading service worker when available (fatal error can stop other JS from running)
* Only load service worker on TLS connections, as per the developer docs, they MUST ONLY be used when the connection is secure.
> Fixes service worker code

- .htaccess
- warmup/settings.php
Use a silly redirect in .htaccess (/js/canary.js -> /js/default.js),
and use it in warmup/settings.php to detect whether .htaccess is
allowed to rewrite URLs. Hoping this helps fewer self-hosters
get hung up on this common configuration glitch!
This is real dog-sciencey as I fumble through learning php;
please feel free to reject or ask for changes/improvements.
Addresses #858
> Detect "AllowOverride None" during setup

- css/simple.css
- warmup/requirements.php
Place a message during warmup/requirements.php to alert the administrator when they're installing Known on a non-secure site, nudging them to consider installing a certificate.
This is only a warning at the moment, but there's a switch for making it a requirement at some point in the future when port 80 is more widely deprecated.
> Warmup ssl

- templates/default/content/end.tpl.php
- templates/default/content/syndication.tpl.php
- templates/default/entity/annotations/comment/main.tpl.php
- templates/default/forms/link.tpl.php
Some work to prevent the worst cases of scope pollution in api views (#808) and closes #815 by returning more useful service account details in api result.
I think we may need to rethink how views are rendered, especially how data for the api is collected. Rendering $vars as json presents two problems 1) scope violation due to the long standing bug in bonita, 2) it's not possible to override views for an object because you can't just replace an object template and have it rendered.
> Tidy api result

- .htaccess
Oops, need to fix an earlier mistake -- this way the -f -d RewriteConds apply
to the index.php RewriteRule, not to the canary rule.
> htaccess: move canary RewriteRule above the RewriteConds

- Idno/Common/Page.php
- Idno/Core/PubSubHubbub.php
When a new ActivityStreamPost is saved, try to gather all the feeds it belongs to (homepage, content/type, content/all, any tag feeds, and all of the RSS equivalents) and send a ping to Superfeedr for all of them at once.
I tested this a bit with http://known.kylewm.com/ and Woodwind, and it seems to work!
This is for issue #866
> Pubsubhubbub feeds

- IdnoPlugins/Bridgy/Main.php
- IdnoPlugins/Bridgy/Pages/Account.php
- IdnoPlugins/Bridgy/Pages/Disabled.php
- IdnoPlugins/Bridgy/Pages/Enabled.php
- IdnoPlugins/Bridgy/templates/default/bridgy/account.tpl.php
- better visual feedback when connected
- allow users to disconnect via the same interface
this addresses issue #843 
still TODO:
- Refetch and parse the Bridgy user page to update connected status
in the future.
> store Bridgy connected/disconnected status

- Idno/Core/Admin.php
- Idno/Pages/Admin/EmailTest.php
- templates/default/admin/email.tpl.php
- templates/email/admin/emailtest.tpl.php
This patch adds an extra form to the email settings in admin, which let the admin validate their email settings via a one click button.
Note: This isn't a unit test (doesn't really make sense to do this as a unit test atm)
> Email settings test

- IdnoPlugins/Bridgy/Main.php
- IdnoPlugins/Bridgy/Pages/Account.php
- IdnoPlugins/Bridgy/Pages/Check.php
- IdnoPlugins/Bridgy/templates/default/bridgy/account.tpl.php
- First call checks whether account enabledness has changed
- Re-render the account page and have JS swap out the relevant section
This is the last thing I was planning to do for #843
Of possible minor interest, I wanted to re-render the Account page as part of the Check handler (so that there would only need to be one request). So I would update $user, and then draw the Account page, but it never seemed to pick up the changes to user... guessing it has something to do with the way the session is persisted. Rendering in a second JS request proved much more reliable.
> re-check bridgy connection status

- Idno/Common/ContentType.php
- Idno/Pages/Homepage.php
- IdnoPlugins/Status/ContentType.php
- IdnoPlugins/Status/Main.php
- IdnoPlugins/Status/Pages/Edit.php
- IdnoPlugins/Status/RepliesContentType.php
- IdnoPlugins/Status/Reply.php
- IdnoPlugins/Status/Status.php
- IdnoPlugins/Status/templates/default/entity/Reply.tpl.php
- IdnoPlugins/Status/templates/default/entity/Reply/icon.tpl.php
Split status messages and replies, allows for filtering on both.
* Detects both inreplyto and @reply as a reply
* Introduces creatable ContentType field (default true), which determines whether a button will appear on the create bar
(closes #55)
> Split replies and status updates

- Idno/Core/Email.php
- Idno/Entities/Invitation.php
- Idno/Entities/User.php
- Idno/Pages/Account/Password.php
- Idno/Pages/Admin/EmailTest.php
- Idno/Pages/Admin/Export/Generate.php
- Idno/Pages/Admin/Import.php
- templates/email-text/account/invite.tpl.php
- templates/email-text/account/password.tpl.php
- templates/email-text/admin/emailtest.tpl.php
- templates/email-text/admin/export.tpl.php
- templates/email-text/admin/import.tpl.php
- templates/email-text/content/notification/like.tpl.php
- templates/email-text/content/notification/reply.tpl.php
- templates/email-text/content/notification/rsvp.tpl.php
- templates/email-text/content/notification/share.tpl.php
Adds general text only support + text only components on existing emails
> Text only email

- IdnoPlugins/Like/templates/default/entity/Like.tpl.php
Bad code no longer breaks page, but we still need to work out why 
http://nymag.com/scienceofus/2015/05/some-people-get-sad-in-the-summer.html 
Breaks title extraction regex in callback
> Fixing bookmarks

- Idno/Common/Entity.php
If it's specified "u-uid u-url" gives the post permalink,
as opposed to "u-url" by itself which can include things
like shortlinks.
Known currently concatenates multiple u-urls together
which btw, is probably a bad idea in general
bc you should always be getting full absolute URLs as
the value of u- properties. (so concatenating them
would always give an incorrect URL)
> use "u-uid u-url" to find wm permalink

- Idno/Pages/Account/Settings/Tools.php
- templates/default/account/settings/tools.tpl.php
API keys (which are user passwords) are no longer automatically injected into page, and must be explicitly retrieved.
This means passwords are no longer leaked by simply viewing the page over a non-tls connection.
> Retrieve API key via javascript endpoint

- templates/default/entity/content/embed.tpl.php
- templates/default/shell.tpl.php
Merges code from my soundcloud plugin which loads the embed asynchronously via javascript oembed call rather than blocking with file_get_contents().
> Modify soundcloud embed

- .travis.yml
- Idno/Common/Page.php
- Idno/Data/MySQL.php
- Idno/Data/Sqlite3.php
- Tests/Data/DataConciergeTest.php
- Tests/build/config_sqlite3.ini
- schemas/sqlite3/sqlite3.sql
This patch does a bunch (below) but primarily it introduces support for SQLite file based sql storage.
I did this because SQL/Mongo has quite a lot of overhead in terms of both complexity and resources compared to straight files, and often seemed overkill for folk running Known on low powered devices (embedded / single use sites / simple hosting etc).
It provides a nice fallback, a useful tool for quickly building test builds, as well as reduces some of the admin overhead for folk.
I've got plans for this for some IoT type stuff, and was meaning to do it for a while, but it was prompted by some guy on IRC who's SD card bought the farm, and I figured a SQLite db might be more appropriate.
Anyway, this patch does:
* Introduces SQLite dataconcierge 
* Adds SQLite to travis builds
* …
> Adds SQLite3 support

- Idno/Core/Config.php
- Idno/Core/Template.php
Actually initialise Bonita's CSRF secret, so action tokens can't be trivially guessed.
> Initialise CSRF token

- templates/default/entity/User/profile/fields.tpl.php
Github icon needs class `fa` instead of `a` to be a font awesome icon. Was just a typo I guess.
> Fixed font-awesome class for github icon

- Idno/Core/Config.php
- Idno/Core/TokenProvider.php
- Idno/Pages/Admin/Diagnostics.php
- Tests/CryptoTest.php
- Tests/EnvironmentTest.php
- warmup/requirements.php
* Asserts OpenSSL requirement (is required by core functions, but this is not stated)
* Replaces site secret generation with a cryptographically secure token (double hashing = bad) + generates more entropy.
* Fixes a signup error introduced by #984
> Better Secret/crypto

- .travis.yml
- Idno/Data/Postgres.php
- Tests/EnvironmentTest.php
- Tests/build/config_pgsql.ini
- schemas/postgres/postgres.sql
Closes #76 
This is very much experimental, because Postgres was giving me a headache, but I'm like a dog with a bone with this sort of thing ;)
Things not working quite yet:
* Full text search
* A better way to do on delete insertions (not supported by postgres)
> Postgres support

- Idno/Caching/XCache.php
- Idno/Common/Page.php
- Idno/Core/Idno.php
- Idno/Pages/Entity/View.php
- Idno/Pages/File/View.php
* Adds XCache key cache support (with stub for other mechanisms) - useful alternative to database storage for cached data
* Cache 304 data on object and file views, so database is no longer required for 304 test
> Xcache pages

- Idno/Entities/User.php
Generate the API key from an actual entropic source.  
Things still to consider:
> Generate API key with some actual random bytes.

- Idno/Core/Session.php
Logging straight to error log for now. This is inconsistent with how other authentication failures are handled, but is the only option until #918 is addressed.
> Log API login failures.

- IdnoPlugins/Bridgy/templates/default/bridgy/account.tpl.php
- IdnoPlugins/Bridgy/templates/default/bridgy/facebook.tpl.php
- IdnoPlugins/Bridgy/templates/default/bridgy/twitter.tpl.php
- don't require users to put their Known url in their Twitter/Facebook profile.
Send the user url along with the authorization request (I thought we had
already done this??)
- fix typo on delete Facebook form action -- should be delete/start instead of
facebook/start
I don't think twitter.tpl.php and facebook.tpl.php are used anywhere?
> Bridgy interactions bugfixes

- Idno/Common/Page.php
- Idno/Pages/Session/Login.php
- IdnoPlugins/Comments/Pages/Post.php
- IdnoPlugins/Comments/templates/default/comments/public/form.tpl.php
* Sets a booby-trap logged out comment field
* Checks for referrer on login and logged out comment
Both of these do much to stop the basic script kiddie attack scripts.
> Some simple script kiddie spam/login protection

- Idno/Common/Page.php
- Idno/Core/Session.php
Note, this changes the way the API works slightly, but avoids XSS issues with the API.
> Prevent some XSS issues with the api

- Idno/Core/TokenProvider.php
- Idno/Entities/Invitation.php
* Improves / documents TokenProvider
* Removes another instance of artificially reducing entropy where we don't have to. From my code comment: 
> Unless you're planning to do validation on the token based on it's construction (e.g. comparing a password against a hashed and salted password), there is no benefit to artificially reducing entropy by feeding deterministic and computable values into the hash.
> In this instance what you're doing is feeding time() (easily determined by the attacker) + email (supplied by the attacker) + a random value with highly limited scope. Additionally, where email isn't there, you hash a hash, which adds no extra entropy.
> True, an invitation must exist, so it's not actually all that of a problem here, but 1) we have a token, so use it. 2) it's a smaller …
> Invite entropy

- Idno/Core/Webservice.php
- Idno/Pages/Entity/Share.php
- Idno/shims.php
MF2 only called for supported file types, which avoids out of memory error when processing a non-supported type (like MP3 or video)
> Checks content type before MF2 mining on share

- Idno/Common/Page.php
Update:
* Avoids #1036 
* Closes #1038
> Out of band headers are hard; use in-band data for api forwarding squish.

- Tests/Data/ConfigTest.php
Ubuntu for some reason comes bundled with a really old version of PHP Unit.
> Backport for older phpUnit

- Idno/Core/Webservice.php
Quickfix for #753.
Adds a block to Webservice.php:file_get_contents() to check for redirections. Stops after 3 redirections to prevent redirect loops.
> Follow redirections on file_get_contents()

- Idno/Core/Migration.php
When a post coming from wordpress is less than 500 characters and has no title, treat it as a status update, rather than a full-on post.
> Cleaner status imports from WP

- Idno/Core/Idno.php
- Idno/Core/Session.php
- IdnoPlugins/IndiePub/Main.php
- IdnoPlugins/IndiePub/Pages/MicroPub/Endpoint.php
- clarify that "login" happens once when the user enters their
username/password, whereas "auth" happens per-request
- plugins should expect to register hooks before user auth happens --
cannot depend on the user being set during init.
- plugins should handle event "user/auth/request" to provide own
authentication mechanism
- plugins should handle event "user/auth/success" to react to the user
being authed
- updated IndiePub plugin to use the pluggable auth mechanism
Intends to address #519 and #918, and supersedes @mapkyca's PR #1123
> sort out order of plugin registration and user auth

- Idno/Core/Idno.php
- Idno/Data/MySQL.php
Makes a pretty significant performance improvement when inserting an entity. On my system it's on the order of 0.3s without and 0.03s with a transaction.
Before:
```
PHP message: Known (known.dev): DEBUG - insert or update took 0.30136895179749 s
PHP message: Known (known.dev): DEBUG - insert or update took 0.3676438331604 s
PHP message: Known (known.dev): DEBUG - insert or update took 0.29871201515198 s
PHP message: Known (known.dev): DEBUG - insert or update took 0.37608504295349 s
```
After: 
```
PHP message: Known (known.dev): DEBUG - insert or update took 0.038892030715942 s
PHP message: Known (known.dev): DEBUG - insert or update took 0.024508953094482 s
PHP message: Known (known.dev): DEBUG - insert or update took 0.030456066131592 s
PHP message: Known (known.dev): DEBUG - insert …
```
> mysql: insert entity and metadata inside of a transaction

- Idno/Core/Session.php
- IdnoPlugins/Event/Pages/Edit.php
- IdnoPlugins/Event/templates/default/entity/Event/edit.tpl.php
- IdnoPlugins/Text/Entry.php
- IdnoPlugins/Text/Pages/Edit.php
- js/default.js
- templates/default/forms/input/richtext.tpl.php
- Use unique ID as selector when saving body
- Restore autosaved fields in getContent instead of the template.
- DOMXPath constructor causes a silent fatal error instead of throwing
an exception; add null-safety for it
> Autosave: fixes to work with TinyMCE

- Idno/Pages/Admin/Home.php
Loading /admin/ takes a while because of a call to db->optimize().
This PR throttles it so that it will only call optimize if it's been
more than 24 hours since the last call. I'm open to other ideas too
(including leaving it alone)
> Call db->optimize at most once a day

- Idno/Core/Autosave.php
- IdnoPlugins/Text/templates/default/entity/Entry/edit.tpl.php
- templates/default/forms/input/richtext.tpl.php
- Don't save for any use of richtext editor -- move autoSave call to
Text's edit template itself.
- Since javascript only sends values that have changed, merge them
with the existing autosave values on the server side.
> Autosave bugfixes

- IdnoPlugins/Checkin/templates/default/entity/Checkin/edit.tpl.php
- IdnoPlugins/Like/templates/default/entity/Like/edit.tpl.php
- IdnoPlugins/Media/templates/default/entity/Media/edit.tpl.php
- IdnoPlugins/Photo/templates/default/entity/Photo/edit.tpl.php
- IdnoPlugins/StaticPages/templates/default/entity/StaticPage/edit.tpl.php
The call to `$t->__(array('object' => $object))` was overwriting the
actual 'object' value in `$vars` with the undefined variable `$object`.
We could call `$t->__(array('object' => $vars['object']))` instead but I
believe that would be redundant.
Fixes #1026
> bugfix: Post Privacy was reset to public when editing some post types

- Idno/Common/Entity.php
- Idno/Core/Config.php
- Idno/Core/Idno.php
- Idno/Pages/Admin/Home.php
- Tests/Core/PermalinkStructureTest.php
- Tests/Core/SessionTest.php
- Tests/KnownTestCase.php
- templates/default/admin/home.tpl.php
Allow the administrator to choose one of
* `/:year/:slug`
* `/:year/:month/:slug`
* `/:year/:month/:day/:slug`
We may want to add a nag screen or some other protection against breaking old permalinks, e.g. maybe `/year/slug` should be made to always redirect to whatever the current configuration is.
Fixes #1139 (at least to the extent that I redefined #1139)
> Basic support for custom permalink structures

- Idno/Data/MySQL.php
- schemas/mysql/2015061501.sql
* Prevent extra md join on MySQL::countRecords, md# names are indexed from 1.
* Make sure to write the schema version out after executing 2015061501.sql; otherwise it was running on every request!
> MySQL optimization/bugfixes

- Idno/Common/Page.php
- Idno/Core/Template.php
- IdnoPlugins/IndiePub/Pages/IndieAuth/Auth.php
- external/bonita/includes/Bonita/Templates.php
- external/torophp/src/Toro.php
- templates/default/shell.tpl.php
Unsilencing errors in template rendering helps debugging
when there are problems (including syntax errors) in the template.
Changed @include  to include, and fix some warnings that were
happening when rendering templates in general.
Fixes #1145
> Do not suppress errors in templates

- external/bonita/includes/Bonita/Templates.php
- templates/default/onboarding/register.tpl.php
- templates/default/shell/simple/messages.tpl.php
- warmup/settings.php
There were two issues:
1. if ($ok = true) instead of if ($ok == true) was hiding an earlier error
2. installing the mysql schema can return false or 0 but still have been
successful. adding some logic to check the PDO::errorInfo() error code.
Fixes #1174
> bugfix: preserve site title during registration

- js/default.js
- templates/default/content/create.tpl.php
Use a flag to avoid the situation where you can click a content create
button multiple times. Opening a second editor on top of the first
editor can erase content (if you're on a slow enough connection that
it is noticeable).
Fixes #1167
> ignore addtl clicks on contentCreateButton

- IdnoPlugins/Status/external/brevity-js/LICENSE
- IdnoPlugins/Status/external/brevity-js/README.md
- IdnoPlugins/Status/external/brevity-js/brevity.js
- IdnoPlugins/Status/external/brevity-js/test/index.html
- IdnoPlugins/Status/external/brevity-js/test/node-test.js
- IdnoPlugins/Status/external/brevity-js/test/test.js
- IdnoPlugins/Status/external/brevity-js/tests.json
- IdnoPlugins/Status/templates/default/entity/Status/edit.tpl.php
brevity-js accounts for t.co shortening that Twitter does when
counting characters, for a more accurate estimate of whether your note
will fit in a tweet.
N.B. I wouldn't be offended if you held off on merging this until after
the 0.9 release. It's a non-trivial change and I have only tested locally
a little.
Fixes #1162
> Use a library to count characters when composing a status

- templates/default/entity/edit/footer.tpl.php
avoid ambiguity when there are multiple spinners on a page
(needed for a plugin)
> reference spinner by its id

- Idno/Common/Page.php
- Idno/Core/Session.php
- Tests/Core/GatekeeperTest.php
- templates/default/pages/403.tpl.php
- templates/default/shell.tpl.php
Pages now return correct error code (as opposed to forwarding and losing the response code).
> No forwarding

- Idno/Core/Config.php
- Idno/Core/DataConcierge.php
- Idno/Data/MySQL.php
- Idno/Data/Postgres.php
- Idno/Data/Sqlite3.php
- Tests/API/BasicAPITest.php
- Tests/Core/PermalinkStructureTest.php
- Tests/Data/DataConciergeTest.php
- Tests/KnownTestCase.php
Mongo's getAnyRecord always returned an array while
other implementations converted the array to an object
if possible.
Changed all DBs to return an array for getAnyRecord and
added DataConcierge::getAnyObject.
(Config was the only thing using this function
and this allows us to remove some special casing from its
init)
Fixes #978
> Reconcile DataConcierge::getAnyRecord with other DBs

- .htaccess
- htaccess.dist
- templates/default/shell.tpl.php
- templates/default/shell/css.tpl.php
The ?yyyymmdd query string caching trick doesn't work terribly well with some browsers and any caching proxy.
In the default configuration a proxy will strip the query string, and so see the foo.js?12345 and foo.js?67890 as the same thing, returning a HIT for the earlier version.
Alternatively, another common configuration, anything with a query string is treated as dynamic, and so uncacheable. 
Either way, not good.
This patch provides a rewrite rule that takes a number prior to the path on JS and CSS standard files, allowing new versions to be incremented with machine version numbers.
> Caching resources

- Idno/Common/MappingIterator.php
- Idno/Core/DataConcierge.php
* %-encode '$', '.', and '%' in field names before storing to Mongo
* unencode field names when loading from Mongo
I'm a bit unconfident in the `MappingIterator` stuff stye-wise &mdash; Known doesn't
seem to have a place to stick generic utility functions (which kind of blows my mind),
and every other class has a clean OO/Domain driven design thing going on. Ideally
it would just be a hidden inner class tucked away inside the Mongo specific code, but
PHP doesn't seem to support those. Open to suggestions.
@finalcut @misuba it would be great if you could try this out and see if it fixes your issue.
Fixes #447
> bugfix: MongoDB 2.6+ disallows .'s and $'s in field names

- Idno/Common/Entity.php
previously array_shift(array_pop(...)); was probably failing but
hidden by the insidious @ operator
Fixes #1104
> bugfix: read dt-published from incoming webmentions correctly

- Idno/Common/Entity.php
- css/default.css
- templates/default/account/settings.tpl.php
- templates/default/admin/themes.tpl.php
- templates/default/content/syndication.tpl.php
- templates/default/content/syndication/links.tpl.php
* set syndication buttons disabled based on posse_link['username'] rather than 'name'
* pass 'username' to syndication links icon template
* minor theme tweaks; don't hard-code spacing between form elements, it breaks
bootstrap's form-group spacing
> posse_links tweaks

- IdnoPlugins/Status/Status.php
Ensure replies are always created as replies in order to prevent a broken/inconsistent data model.
Hiding replies as replies needs to be handled in the UX otherwise users perceive behaviour as a bug
> Fixes the broken status/replies datamodel

- Idno/Common/Entity.php
- drop support for receiving old-style mf2 likes and reposts.
- these classes are now more often used to mark up likes and reposts,
and our own likes can end up being backfed to us if the sender
implements salmentions
there are ways to do this more intelligently if we need to keep
support for these older classes, but i'm not aware of anyone that
still uses u-like/u-repost exclusively
fixes #1245
> don't interpret "u-like" and "u-repost" in received webmentions

- Idno/Core/Migration.php
changing from `Entity::save()` to `Entity::publish()`
(I overlooked this call to `save()` when changing the behaviour for "retroactive posse" #206 )
> bugfix for importing rss feeds

- Idno/Common/Entity.php
- Idno/Core/Idno.php
- js/default.js
- templates/default/content/create.tpl.php
fixes the remaining conflict between IndePlugins/Reactions/Like and
IdnoPlugins/Like/Like because Reactions can use any edit url it
prefers now (currently using /indielike/edit instead of /like/edit,
which is admittedly a little bit puerile, "my likes are indier than
yours")
> allow ContentTypes to override their default edit URL

- Idno/Core/Webservice.php
leave the encoding to cURL. this is required in order to
send files (key=@filename) via POST for micropub
> Webservice::post should not form-encode params

- Idno/Common/Entity.php
getRelativePublishDate() does not appear to be used and isn't localised in either timezone or language.
This sort of thing is better handled on the fly computing from a GMT timestamp to local wallclock, with translations applied (e.g. by timeago on the main template)
Closes #729
Refs #339
> Remove getRelativePublishDate().

- Idno/start.php
Small fix to suppress warnings on shared hosts where php.ini/safe mode can't be modified.
> set_time_limit won't work in safemode

- Idno/Pages/Admin/Diagnostics.php
- Tests/Core/GatekeeperTest.php
- warmup/requirements.php
Based on stuff mooted in the conversation in #1238, this patch modifies diagnostics and warmup requirements to warn for php >=5.4 && <5.5.
Not a hard failure, just a nudge that there's a potential problem (which many users probably aren't even aware), similar to how we handle nonTLS installs.
> Warn about php 5.4 in diagnostics and warmup

- Idno/Core/PubSubHubbub.php
PuSH pings weren't being sent for / because it was checking for the ContentType itself rather than the class that the ContentType represents
> bugfix: PuSH was not pinging the homepage

- Idno/Pages/Admin/Home.php
This permits db optimisation to take place after the page has been rendered and sent, allowing the user to continue.
Does not require user to configure cron on their system.
> Refs #1247: Run DB optimisation on a shutdown hook.

- IdnoPlugins/StaticPages/Main.php
- IdnoPlugins/StaticPages/Pages/ClearHomepage.php
- IdnoPlugins/StaticPages/Pages/Homepage.php
- IdnoPlugins/StaticPages/Pages/SetHomepage.php
- IdnoPlugins/StaticPages/StaticPage.php
- IdnoPlugins/StaticPages/plugin.ini
- IdnoPlugins/StaticPages/templates/default/shell/toolbar/content/default.tpl.php
- IdnoPlugins/StaticPages/templates/default/staticpages/admin.tpl.php
- IdnoPlugins/StaticPages/templates/default/staticpages/toolbar.tpl.php
- templates/default/forms/link.tpl.php
- templates/default/shell/toolbar/content.tpl.php
- templates/default/shell/toolbar/content/all.tpl.php
- templates/default/shell/toolbar/content/default.tpl.php
- templates/default/shell/toolbar/content/entry.tpl.php
- templates/default/shell/toolbar/content/type.tpl.php
I'm new to Known, and my day job is not PHP so this probably needs some cleanup.
Anyway, my primary motivation for this plugin was to make it easier to customize the homepage without too much work creating plugins and themes. I knew that I had the ability to create static pages, but none of them could be promoted to the homepage.
This adds the ability to set a page as your homepage by pressing the "home" icon on the pages admin page. In order for the homepage not to disappear completely, I needed to modify the "links" template in order to allow me to modify the default link. In addition, I added the ability to set a title on links created by "createLink" in order to condense the homepage toggle down to just an icon in order to save space.
I tried to make the former homepage discoverable, …
> Adds the ability to set a static page as the homepage.

- Idno/Core/DataConcierge.php
- Idno/Data/AbstractSQL.php
- Idno/Data/Mongo.php
- Idno/Data/MySQL.php
- Idno/Data/Postgres.php
- Idno/Data/Sqlite3.php
- refactor to eliminate duplicate code between Postgres, Mysql, &
Sqlite implementations
- change logic of build_where_query slightly to support
`[$not]` and `[$not][$in]` (previously it combined the two cases).
- also check for `$key == '$or'` rather than `!empty($value['$or'])`,
which I don't think made sense.
> pull common SQL functions to AbstractSQL

- IdnoPlugins/IndiePub/Pages/MicroPub/Endpoint.php
renamed $photo variable
$photo is used to create a photo entity and should then not be added to the $content
> MP Endpoint: rollback $photo

- docs/install/instructions.md
Added postgres installation instructions, deprecated mongo
Mysql is recommended, so should be first. Postgres was missing entirely
> Add postgres instructions

- Idno/Data/AbstractSQL.php
if querying just one subtype, then just set `$search['entity_subtype'] = value`. The `$not` query in this case is redundant and trying to set it was giving a warning message.
My previous PR introduced this bug. It used to just set `[$in]` and `[$not][$in]` even if there was only one candidate match.
> AbstractSQL bugfix: $not cannot be side-by-side with a simple = value

- IdnoPlugins/IndiePub/Pages/MicroPub/Endpoint.php
delete single quotes in categories name
4sq categories are internationalized and can have single quotes (apostrophe), as this would break the hashtag, we need to delete them.
> MP Endpoint: delete single quotes in categories (for hashtags)

- Idno/Pages/Webmentions/Endpoint.php
remove urldecode calls on received webmentions
form parameters should already have been decoded; decoding them again
caused an issue where we could not recognize webmentions when the
source has unicode characters in the URL (i.e. it would grep the target content
for the source, but not find it since the %-characters in the source URL
had been converted to their unicode equivalent)
@nekr0z reported this issue to bridgy here: https://github.com/snarfed/bridgy/issues/625
> remove urldecode from webmention endpoint

- Idno/Common/Entity.php
- Idno/Core/Syndication.php
- templates/default/content/syndication.tpl.php
- templates/default/content/syndication/links.tpl.php
Added parameters so I can stick "additional" properties into serviceAccount definitions and also into posseLinks that have been created.
This supports IndieSyndicate which will store a configurable icon and posse-style
for each micropub syndication account.
> let plugins store additional properties in posse links

- templates/default/content/syndication/links.tpl.php
remove rel=syndication when rendering syndication links in the h-feed
rel=syndication is page-scoped so they should only be used when we're on
the post's permalink
> remove rel=syndication when rendering syndication links in the h-feed

- Idno/Data/AbstractSQL.php
- Idno/Data/MySQL.php
- Idno/Data/Postgres.php
- Idno/Data/Sqlite3.php
use strict comparisons (===) when checking keys in `build_query_from_array`
I ran into a case where the input for build_query had numeric keys,
and `$key == '$or'` is TRUE when $key = 0. Better in these cases to use
strict equality.
> DataConcierge: use strict comparisons (===) when checking keys

- Idno/Core/Logging.php
Check the top 3 frames, and take the first one that is not from class
Idno\Core\Logging.
The addition of warn(), info(), debug(), methods mean that we cannot
count on the 2nd frame always being meaningful.
> log the file:line based on the first stack frame before Logging

- Idno/Core/Webservice.php
- Idno/Core/WebserviceFile.php
- Tests/API/UploadTest.php
this prevents curl from interpreting values with a leading @ as
filenames, and is the default value in PHP 5.6.
otherwise, when sending e.g. Tweets that start with an @ via
Webservice, curl tries to interpret it as a filename and chokes.
this does not help PHP 5.4, where it does not seem to be possible
to send textual values that start with an @.
depends on https://github.com/idno/Known/pull/1315 being pulled first.
> Webservicefile safe upload

- Idno/Core/Webservice.php
- Idno/Core/WebserviceFile.php
- Tests/API/UploadTest.php
As per @kylewm's suggestion, introducing a webservice file wrapper around the various curl file formats
Removing the previous shim broke the build for > PHP 5.4, and while I think binning 5.4 is the longterm goal (#1313) this is a good solution to this specific issue.
Closes: #1310
Closes: #1312
> Adds WebserviceFile curl wrapper

- docs/plugins/community.md
New content type for Known
Journal content type for Known, post journal entries to your Known site
> Journal content type plugin added

- IdnoPlugins/Comments/templates/default/comments/public/form.tpl.php
- templates/default/account/login.tpl.php
Add form-group divs around elements in the Comments form.
Change control-group to form-group in Login form.
Bootstrap 3 changed control-group to form-group, this fixes the spacing
between form elements that had been fixed artificially before 1a59ac17a74a21bd3d3c1e903cd60cba391e907c
> tweak form-group in templates

- Idno/Common/Entity.php
Stripped % characters in stubs, %encoding should already have been urlencoded.
Reported problems with % chars in stub
> Strip % characters in slug, closes #1331

- Idno/Common/Entity.php
- Tests/Common/EntityTest.php
- new unit test for prepareSlug with some simple cases and some umlauts (both inside and outside of the slug length)
- allow % characters when creating the slug; prevents it from converting %C3%BC to C3BC
- specify 'UTF-8' encoding in mb_strtolower
On some versions of PHP, `mb_strtolower` without a specific converts ü to \343\247, which is some other encoding that breaks everything and erases the slug.
Fixes #1343
> Unicode slug fix

- Idno/Common/Entity.php
- Tests/Common/EntityTest.php
- make sure %'s and other special characters (that aren't \p{L}) are also encoded
- add more cases to the unit test to make sure we're doing what's expected
This should support both #1343 and #1331.
Previously we tried stripping %'s altogether, which converted unicode characters like %C3%BC to C3BC (which is fine but ugly), and including all %'s which was problematic when there is an actual literal % in the title.
> urlencode the entire slug after dasherizing

- Idno/Core/Idno.php
To answer a specific question, temporarily start collecting db engines in use.
> Temporarily capture DB engine on vendor message ping

- .travis.yml
- Idno/Core/Webservice.php
- Idno/Pages/Admin/Diagnostics.php
- Tests/API/UploadTest.php
- docs/install/requirements.md
- warmup/requirements.php
* Uses stronger language in PHP 5.4 warning message
* Changing documented minimum requirement to PHP 5.5
Removal of the @ file shim in 2279f5f488d9d9823e807bd45c19c2a2447d0336 introduced a breaking change in the Webservice interface, this means we can no longer maintain PHP 5.4 support without significant technical debt. 
This patch moves PHP 5.4 to the "breaking" section of the travis build, and softly deprecates 5.4 support in the installer. 5.4 installs will still install (i.e. the installer won't kick you out), but we now state that it's going to be increasingly unsupported and that you should upgrade.
Closes previous tickets and PRs related to this issue.
Refs #1310
> Soft deprecation of PHP 5.4

- IdnoPlugins/IndiePub/Pages/IndieAuth/Token.php
Call to findUserForToken() should be static, otherwise it's undefined.
It should be static.
Possibly related to #1352
> IndiePub needs to call static function as static

- Idno/Core/Syndication.php
I think this was just a typo in 7457fe846ad1caf993f44ffd5a01b5e01a81cbdc
fixes #1362
> change key $accounts to 'accounts' to fix invalid index error

- Idno/Pages/Entity/Share.php
on the /share page, strip all extra non-URL text from the share_url property
Support for mobile apps that add extra stuff (title, tagline, via, app name) to the url.
Fixes #1361
> Share: strip all extra text from share_url property

- Idno/Common/Entity.php
- Idno/Common/Page.php
- Idno/Pages/Webmentions/Endpoint.php
- Tests/Common/EntityTest.php
- add unit tests for `Entity::addWebmentions`
- examine incoming webmention source to see if it looks like a feed (has > 1 h-entry)
- discard webmentions from pages that look like feeds
- refactored Entity::addWebmentionItem to remove duplicate code for parsing h-cards
If you send a webmention to yourself wtih `source=http://yoursite.com/` and `target=http://yoursite.com/2016/a-permalink`, it currently sends yourself a reply from every post on the feed to that target, which looks crazy (see #1358 for screenshots)
fixes #1358
> ignore webmentions where the source is a feed

- Idno/Core/Session.php
Prevent cookie set on logout for API requests
This caused issues of headers already being sent when logout called on shutdown hook in api (to avoid XSS issues elsewhere). 
Session is still destroyed, but client cookie reset, while still recommended, is optional, and not really necessary on the API since we no longer require cookies to handle forwarding to newly created objects.
> Closes #1365: Don't remove client cookie when called on API

- Idno/Common/Page.php
- Idno/Core/Idno.php
- Idno/Core/Session.php
- IdnoPlugins/IndiePub/Main.php
- IdnoPlugins/IndiePub/Pages/IndieAuth/Auth.php
- IdnoPlugins/IndiePub/Pages/IndieAuth/Token.php
* Page() is now abstract
* currentPage() no longer returns a Mayfly object
* Introduces a page/ready event call once the system is booted and page object is ready.
Assets were being set, but silently clobbered when the "real" page is booted. This relates to a number of issues we've encountered before, e.g. #235 
Closes #1303
> Fixing assets take 3

- Idno/Core/Logging.php
- css/default.css
- templates/default/entity/FeedItem.tpl.php
- templates/default/entity/annotations/replies.tpl.php
- templates/default/entity/shell.tpl.php
- move h-entry outside of the h-card in the default theme, so that the author is captured
- narrow h-card in comments so that it only includes the author, and not the permalink url
- remove break-all from css -- causes words to be broken in the middle unnecessarily (like "Kyle Ma\nhan")
fixes #1371 and #1372
> mf2 markup tweaks

- IdnoPlugins/Checkin/checkin.js
remove extra / from checkin.js url
based on https://github.com/idno/Known/issues/1375#issuecomment-200840476 the leading / seems to be causing an error. Since wwwroot() is based on getDisplayURL(), we are safe to assume it will end in a slash and can remove the leading one here
fixes #1375 
(again)
> remove leading / when building checkin.js url

- Tests/Pages/HomepageTest.php
- index.php
Instead of rendering 404 directly, create a Homepage instance and call
noContent on it.
Recent changes to avoid creating a default Page meant that
currentPage() returned false for 404 routes, which resulted in
errors rendering the template.
> bugfix: 500 error on page not found

- Idno/Pages/File/Picker.php
The 'shell' template expects 'messages' to be set, and drawPage sets it.
fixes #1370
> use drawPage rather than draw('shell')

- IdnoPlugins/StaticPages/Main.php
Added "%" encoded chars on StaticPages page router definition.
Pages with unicode characters were not being picked up by the page router, which meant there was no current page when the shell was rendered.
> Closes #1385: Handle "%" encoding in page URLS.

- Idno/Common/Entity.php
- Idno/Entities/Notification.php
- Idno/Pages/User/View.php
- IdnoPlugins/IndiePub/Pages/MicroPub/Endpoint.php
- Tests/Pages/HomepageTest.php
- Tests/Pages/User/ViewTest.php
Since we don't store user mentions in the user object,
we need to make sure we're only sending one Notification per
source/target pair (rather than one per webmention)
This checks uniqueness using a "notification key" which is
analogous to the slug of a post, except that the notification
key contains long urls so we take the md5 hash of it.
I'm also sneaking in a change to indiepub that prevents it
from changing "www.instagram.com" to "www.instagram" 
that I forgot to make in a separate branch.
fixes #1381
> skip duplicate notifications for the same source/target

- Idno/Core/PubSubHubbub.php
Check that $entity->getContentType() returns something before trying to access it.
$entity->getContentType() returns false or StaticPage entities.
Fixes #1394
> bugfix: check that ContentType is not false before inspecting it

- Idno/Core/Webmention.php
When parsing webmentions, do not let flat/simple "author" properties prevent us from searching the rest of the page for the full author "h-card". Only fall back to the flat properties if we can't find an h-card at all.
quick fix for #1397 ... does not get us any closer to implementing /authorship as written, but should cover most of the real world use cases.
> fallback to flat author properties only if there is not top level hcard

- Idno/Core/Template.php
- Tests/Core/TemplateTest.php
- Add ; : and ? to the trailing punctuation marks that are stripped
- Conditionally allow a trailing ) only if there is a matching ( earlier in the URL
Better display of https://kylewm.com/2016/04/where-do-these-people-come-from-sumantmannei-don-t-think-his-making-a-statement-would-have-changed-anything-e9b31598e378joxoiqdn6-are-they-just
> auto-linking: strip more trailing punctuation

- Idno/Common/Entity.php
Entity::removeAnnotation(...) removes based on the local annotation URL.
This change modifies it so that it also searches each annotation's "permalink"
field for a remote URL (i.e. the webmention source).
Webmentions where the source returns HTTP 410 were being processed and
acknowledged, but weren't actually deleting the comment
> bugfix: support delete webmentions

- Idno/Common/Entity.php
- Tests/Common/EntityTest.php
- remove redundant call to prepareSlug at the beginning of setSlugResilient
- calling prepareSlug twice meant that unicode characters got
converted from ü to %C3%BC to %25c3%25bc which was bad!
> don't double encode unicode characters in setSlugResilient

- Idno/Common/Entity.php
- Idno/Core/EventQueue.php
- Idno/Core/Idno.php
- Idno/Core/PubSubHubbub.php
- Idno/Core/SynchronousQueue.php
- Idno/Core/Syndication.php
- Idno/Core/Webmention.php
- IdnoPlugins/Status/Status.php
Add a Queue interface and default (sync) implementation. Move some events (webmentions, PuSH ping, syndication) to the queue first.
- allow some events to send to a queue instead of triggering immediately
- EventQueue is super generic to hopefully allow experimentation, avoid
specifying exactly how a queue dispatcher should work
This PR continues my thought process from #691, I don't necessarily need it merged so much as I wanted to continue the conversation... FWIW, I have a proof of concept plugin that uses Gearman running locally, but it might be a little while before I can release it.
> add a Queue interface and default (sync) implementation

- Idno/Core/MentionClient.php
Emergency fix of broken MentionClient -- _get, _head, _post methods 
have different return values now.
Somehow the changes I'd made to Idno\Core\MentionClient were lost
and we're getting major breakage because of the mismatch between it and the
new version of the class it extends
TODO add unit tests
fixes #1411
> fix warnings resulting from old version of Idno\Core\MentionClient

- Idno/Core/Syndication.php
- IdnoPlugins/IndiePub/Pages/MicroPub/Endpoint.php
based on draft http://micropub.net/draft/#syndication-targets, we shouldn't need to provide syndicate-to and syndicate-to-expanded. All the fancy data can go right in syndicate-to as long as they are requesting JSON.
Note we still fall back to just sending service IDS if the Accept header is not set to application/json
Iterating on the best format for syndication targets in the micropub spec right now. Sending back the old style flat targets in JSON breaks integration with Quill.
fixes #1423
> micropub: update format of q=syndicate-to response

- Idno/Core/Session.php
Set a client visible header when validation tripwire is fired
Debugging session issues for hosted version, where logs are not available.
> Debug session validation tripwire for hosted domains (refs #1403)

- Idno/Core/Session.php
Removed call to Page::deniedContent() from tryAuthUser()
It was previously causing a fatal error when api auth failed. Calling deniedContent here is not necessary, since if $return isn't set, then no user has been found.
Defer the page content error.
> Closes #1420: Defer deniedContent() until page is set.

- docs/developers/plugins/index.md
- templates/default/admin/plugins/plugin.tpl.php
Bring back plugin requirements display
For some reason the $requirements array from the plugin details has been lost when passed to the plugin template.
> Fixes plugin requirements listing on plugins page.

- Idno/Common/Page.php
Added a log of exceptions
Page exception handler displayed the exception but suppressed it's entry into the log (!!), meaning background processes were harder to debug.
> Actually log exceptions, can't believe this was overlooked before.

- IdnoPlugins/StaticPages/Main.php
Passing function result to variable before passing to empty().
Using function result in empty() isn't supported in PHP < 5.5, and while php 5.4 is no longer officially supported, this was a simple fix.
Closes #1440
> PHP 5.4 compatibility

- Idno/Common/Page.php
- Idno/Pages/File/View.php
Added partial content support to file downloads.
Apple requires partial content support on streams, hopefully it is sufficient to add this support on file objects only, since generic page support isn't possible without a way that getContent() works.
> Partial content

- Idno/Files/File.php
- Idno/Files/LocalFile.php
A getSize() method on the File interface.
So it's possible to retrieve the size of the file, and provide's some interface parity with MongoGridFSFile.
This fixes the issue where *SQL users were seeing broken images.
> Closes #1453: Introducing getSize() on File interface.

- Idno/Core/Template.php
Modified regex to allow .@ username notation
It's common practice to use .@user at the start of a tweet to make a public reply, however the local copy didn't activate the username.
> Closes #1465: Allows the commonly used .@ reply notation

- Idno/Common/Entity.php
Reset the ->attachments array
Deleting object attachments removed the files but not the array, resulting in duplicates / broken images when displaying.
> Reset object's attachment array after deleting attachment files.

- Idno/Core/Config.php
- Idno/Core/Logging.php
* Known logger now intercepts PHP error messages
* Introducing *pedantic_mode* which will convert all PHP error messages to ErrorException()
* Notice errors are verbotten, using pedantic_mode during development will make it easier to enforce this discipline.
> Notice as exception

- Idno/Core/Idno.php
fixed #1473
the routes all have KNOWN_SUBDIRECTORY prepended to them, so stripping
it off path_info before trying to find a matching handler is counter productive.
@herbsmn It would be awesome if you could pull this branch (or copy/paste the three-line change) into your installation and check that it actually works before we merged into master. Thanks!
> support webmentions for subdirectory installations

- Idno/Common/Page.php
- IdnoPlugins/StaticPages/templates/default/staticpages/admin.tpl.php
Removed \Exception type constraint.
Removed a notice error.
PHP7 has different type hierarchy.
> Pages errors

- templates/default/content/access.tpl.php
Added the ability to pass a "default" access permission to the ACL control box
It wasn't possible to default the box to anything other than 'PUBLIC'
> Access defaults

- Idno/Entities/AccessGroup.php
- Idno/Entities/User.php
Flattened the members associated array in AccessGroup, modified User to retrieve user's access groups correctly.
ACLs were not being retrieved for users.
> Fixing acls

- Idno/Entities/File.php
Added conditional around $file_path
To avoid pedantic-mode exception
> Remove pedantic-mode error when file is missing

- Idno/start.php
Added a try/catch around ob_clean() call in fallback exception handler.
When running in pedantic mode, a test where an exception is thrown before output buffering has started, ob_clean() throws a notice, which in turn is converted into an exception and thus losing the original error.
> Catch duplicate exceptions.

- Idno/Entities/AccessGroup.php
Prevent duplicate entries; fixing isMember()
* It was possible to enter a user into a given acl multiple times.
* isMember() would fail if $user_id was the first entry due to key '0' evaluating to boolean false.
> Fixing acls redux

- Idno/Entities/AccessGroup.php
Removed canEdit() check on ACL addMember()
The canEdit() check made it impossible to use ACLs to manage something like a group join, since the AccessGroup object would always be owned by the group owner.
removeMember() had no such check, and management of ACLs is an inherently manual process, with no exposed API, so I figured the risk of exploit was minimal. 
Closes #1492
> Acl addmember bypass

- docs/plugins/community.md
Listing for Short Profile plugin as a community contributed plugin 
New plugin seen via https://twitter.com/egoexpress/status/757922821771104256 cleans up profile page and adds some additional icons for social sites.
> Add Short Profile plugin

- Idno/Common/Entity.php
- IdnoPlugins/Media/Media.php
- IdnoPlugins/Photo/Photo.php
Delete all attachment on deletion of entity
closes #1475 optimises upload as it deletes media which is no more required
> Delete attachment on deletion of entity

- Idno/Core/Webservice.php
Added a URL safe version of base64.
It is not safe to include base64 content in urls, but it's handy to be able to do so.
> URL Safe base64 encoding methods

- Idno/Core/PubSubHubbub.php
Change private methods to protected
This is good practice, and necessary as I wanted to implement my own pubsub functions and not rewrite the wheel.
> Make PubSub functions useable by child classes

- IdnoPlugins/IndiePub/Pages/MicroPub/Endpoint.php
Only content[html] may contain HTML, "normal" content needs to be encoded.
Resolves: #1519
> Encode HTML entities posted via micropub's "content" property.

- IdnoPlugins/IndiePub/Pages/MicroPub/Endpoint.php
Ability to create comments and likes as annotation via micropub
I want to back up instagram posts together with their likes and their comments, so I needed a way to import them programmatically.
> Support annotation creation via micropub (like/reply(comment))

- Idno/Core/Template.php
Decode `&auml;` to "ä", but keep "<", ">" and "&" characters encoded.
Resolves: #1523
> Fix HTML entity decoding while keeping support for unicode tags.

- Idno/Core/PubSubHubbub.php
Added atom feed to findFeed regex
We were previously only detecting atom feeds.
> Pubsub: findFeed now supports atom alternatives

- Idno/Data/AbstractSQL.php
When logged in as site admin, acls are bypassed.
While there is an admin bypass on canEdit() etc, object retrieval as site admin meant that such objects could not be retrieved and edited if created as another user.
Admins should be as Gods.
(Probably needs some discussion/checking to make sure this isn't some horrible security hole)
> Bypass access groups query for site admins.

- Idno/Common/Entity.php
Commented out all the slug debug / setting resilient slug messages
It's pretty clear this code is working now, and it makes for noisy logs when you're trying to debug something else.
> Pour some salt on the slug debug

- Idno/Common/Entity.php
* Added ACL admin awareness to canRead()
* Added ACL awareness of write and admin groups to canEdit().
This, among other things, makes these methods consistent with the database object read methods.
A user could be able to access an object, but not edit it, if they were in an ACL write group. Admins should always be able to write, so to should users who have been given admin writes over an object in it's acl. 
Since ACLs were not a well trodden path, this functionality was missing.
> Make entity canEdit/canRead ACL aware

- Idno/Files/LocalFileSystem.php
Increased the entropy of file ID generation for the LocalFileSystem engine.
md5 of time() . metadata was in no way "random", and could result in a collision of a file was saved twice in quick succession (rare but sometimes desirable)
> Increase entropy on generated file ids

- Idno/Entities/AccessGroup.php
- Tests/Data/AccessGroupTest.php
* Explicitly testing owner only "PRIVATE" ACL access
* Adding getByAccessGroup helper function to retrieve objects based on access group.
* The former needed to be tested
* The latter was useful
> Testing private ACLS, introducing getByAccessGroup

- Idno/Common/Entity.php
Added an isAdmin() shortcircuit to Entity::canRead()
Queries have an admin ACL bypass, so it was possible to retrieve the object but not view the object.
> Adding admin bypass to canRead

- templates/default/robot/wizard.tpl.php
Unsets body after robot message is displayed
Body was ending up in posts.
Refs: benwerd/bonita#2
> Closes #1558: Unset $this->vars['body'] after wizard display.

- Idno/Core/Purifier.php
If upload_dir isn't specified, purifier will use system temp for cache data
To remove this errrors.
> Provide a backup cache directory for HTML purifier

- Idno/Common/Entity.php
AccessGroup check on canEdit() and canRead() methods are now limited to objects that are 'published'.
It occurred to me that objects saved as e.g. 'draft' in a shared context (e.g. a group) would loadable by others in the shared context's acl, which, although we could filter these out, could still be accessible if you knew or could guess the uuid.
While I'm pondering, I still think the entity retrieval functions should still retrieve based on ACL, this modification means that non-published entities can only be displayed by owner and admin for access limited posts.
I'm not sure whether we want this, or whether it's the best way, so I push this as a starting point for discussion.
> Limit ACL lookup to 'published' status posts.

- Idno/Data/MySQL.php
- Idno/Data/Postgres.php
- Idno/Data/Sqlite3.php
- schemas/mysql/2016102601.sql
- schemas/mysql/mysql.sql
- schemas/postgres/2016102601.sql
- schemas/postgres/postgres.sql
- schemas/sqlite3/2016102601.sql
- schemas/sqlite3/sqlite3.sql
Introduced a schema change to add publish_status on the main collection tables.
publish_status as metadata required a backfill in order to support NOT 'draft' functionality, due to #1563
> Post status improved

- .htaccess
- Idno/Common/Page.php
- htaccess-2.4.dist
- htaccess.dist
See full description in #1509.
When Apache connects to PHP via FastCGI, the HTTP "Authorization" header
is not sent to PHP.
.htaccess is modified so that the header is made available to PHP.
The header is available as REDIRECT_HTTP_AUTHORIZATION, so the
Idno/Common/Page::getallheaders() is adjusted to take that into account.
Usage of the native `getallheaders()` function is dropped since it does not
return the REDIRECT_HTTP_AUTHORIZATION header at all.
Resolves: #1505, #1509
> Make micropub authentication work on FastCGI servers

- Idno/Entities/File.php
Changed getByURL() to better extract photo ids from urls.
The new mongo code exposed an error with File::getByURL() where by the file ID contained /thumb.jpg and so the object failed to be loaded from Mongo.
> Fixing File::getByURL()

- Idno/Core/Purifier.php
Use temporary directory when upload_path not set for $basic_html route
Avoid error messages
> Use temporary directory when upload_path not set

- templates/default/shell/headers.tpl.php
As per OWASP recommendations, added x-Frame-Options: deny to main template
For security, and also to make ModSecurity STFU
> Add X-Frame-Options: DENY to main template

- Idno/Core/Template.php
Trigger an event for default in_reply_to parseUsers() callback
So plugins can extend @whatever users
> Make parseUsers() pluggable for in_reply_to events

- Idno/Files/MongoDBFileSystem.php
Added basename to MongoFS file construction
On mongo, the new mongodb bucket library code passes the full file path as the filename. This caused broken images on photos, since the regex could not handle urls with an encoded "/" in the url.
Interestingly, this only happened with *some* images (the ones that work seem to get named "thumb.jpg"), not sure why that occurs... Aaaaanyway, this hadn't turned up in testing.
Note, files were still uploaded, so no data was actually being lost.
> Fix photo uploads on mongo

- Idno/Files/MongoDBFileSystem.php
Use $metadata['filename'] instead of $file_path as filename
Using tmpname, even with basename() wrapper causes problems with things that cant interpret mimetype.
> Use correct file name for mongo storage

- Idno/Common/Entity.php
- Idno/Pages/Homepage.php
Pass $search array to countFromX() call
Counts would return the incorrect value for searches.
> Adding missing counts to Homepage feed

- .travis.yml
- Idno/Pages/Admin/Diagnostics.php
- docs/install/requirements.md
- warmup/requirements.php
- Diagnostics and warmup will nag on both PHP 5.4 and PHP 5.5
- Installation requirements now documented as PHP 5.6+
- Moved 5.5 build to travis' allowed_failures branch
PHP 5.5 is dead, and will not be receiving security patches across the board, we should no longer go out of our way to support it. 
As with previous patch for 5.4, this isn't a hard failure, so those stuck on 5.5 can still install (with a massive warning), but the travis change means that while we will make best efforts to maintain support, we won't be held back.
> Deprecate PHP 5.5 support

- Idno/Core/Idno.php
- Idno/Data/Mongo.php
- Idno/Pages/Homepage.php
- Idno/Pages/User/View.php
* Mongo publish_status backfill
* Homepage and Profile feeds are draft aware
Because.
> Homepage and Profile feeds are draft aware

- Idno/Data/MySQL.php
- Idno/Data/Postgres.php
- Idno/Data/Sqlite3.php
- schemas/mysql/2016110301.sql
- schemas/mysql/mysql.sql
- schemas/postgres/2016110301.sql
- schemas/postgres/postgres.sql
- schemas/sqlite3/2016110301.sql
- schemas/sqlite3/sqlite3.sql
Further to 6b168a1de4fc683849ed1506bac6b46f640701fb, I've added a CREATE TABLE to create a versions table if it was missing (for really old schemas)
I also optimised the schema upgrade code.
Many sites were running old old schemas which didn't have versions, and so this broke upgrades.
> Version patches

- Idno/Entities/User.php
Added a plugin hook for access control groups
Allow for programmatic modification/addition of access control lists.
> Allow user access group lists to be extended programmatically

- .gitignore
* Added a gitignore for /foo/bar/nbproject 
* Added /codedocs/
To prevent accidentally committing project and code docs when working on the project
> Ignore netbeans

- Idno/Common/Page.php
By default, isAcceptedContentType() now respects the q parameter
application/json anywhere in the accept string would override any other content type. This update changes the default behaviour to only return true if $contentType was the first/most high priority value stated.
> isAcceptedContentType() respects q parameter (new default behaviour)

- docs/plugins/community.md
I saw that a fork was made of the community Video plugin that was listed, so I added the forked Video plugin to the list in the docs so that others can find it easier in the future.
People said that the other community Video plugin wasn't working https://twitter.com/finalcut/status/817123405321355264
> Added a new community plugin for Videos

- Idno/Core/Config.php
Closes #1627: This is a better solution.
If there is a list of plugins loaded from the database, this replaces those derived from defaults and ini files
Allows plugins to be reliably toggled.
> Database loaded plugin lists now always take precedence.

- Idno/Pages/Entity/Share.php
In cases where content-type is an array, use the last entry when determining whether a page is something we can mine for MF2.
When sharing some urls, it is possible (although rare) that you get multiple Content-Type headers back. This caused the regex on the share page to throw an error.
What seems to be happening is that if you share a URL which performs a 30x redirect, on some servers, both the 301 and the 200 return a Content-Type header, which curl captures and is then returned to us as an array of Content-Type headers. 
It makes no sense for a redirect to return a content type, so I'm thinking the sites who's urls are being shared are misconfigured in some way, but, we should handle this gracefully.
Since the 200 response should always be the last, lets assume that the last entry in …
> Assume last content-type is correct when we get multiple

- IdnoPlugins/Like/Like.php
When saving a local URL, we try a number of mechanisms to work out the local object context.
To provide more contextual information about a bookmark when rendering.
> Bookmark enhancements

- IdnoPlugins/Webhooks/Main.php
Set content-type header for webhook pings
Speculative fix for reported webhook problems, although i've not been able to replicate them myself
> Set content type for webhook pings correctly

- IdnoPlugins/Comic/templates/default/entity/Comic/edit.tpl.php
- IdnoPlugins/Photo/templates/default/entity/Photo/edit.tpl.php
- Themes/Cherwell/templates/default/admin/cherwell.tpl.php
- templates/default/entity/User/edit.tpl.php
- templates/default/file/picker/image.tpl.php
- templates/default/onboarding/profile.tpl.php
Changed accept="" on image file uploads to W3C syntax
It was possible to upload non-image content types.
> Limit image uploads to image types

- Idno/Core/Config.php
Modify ini file config loader to also parse sections in the config file
This allows settings to be namespaced, for example:
[MyPlugin]
setting1 = 'foo'
setting2 = 'bar'
Will now be rendered as
$config->MyPlugin['setting1']
$config->MyPlugin['setting2']
etc
> Pass sections in the ini file

- templates/default/js/known.tpl.php
Added currentURL and currentURLFragments to the known environment object
Provide an easy way to access these from javascript libraries
> Current page helpers on Known JS object

- Idno/Data/MySQL.php
- Idno/Data/Postgres.php
- Idno/Data/Sqlite3.php
- schemas/mysql/2017032001.sql
- schemas/mysql/mysql.sql
- schemas/postgres/2017032001.sql
- schemas/postgres/postgres.sql
- schemas/sqlite3/2017032001.sql
- schemas/sqlite3/sqlite3.sql
Extended the name column to 64 characters
To allow longer keys to be searchable.
> Extend name column size in metadata table

- Idno/Data/Mongo.php
- docs/install/instructions.md
- docs/install/upgrade.md
- docs/plugins/community.md
Mongo database handler now checks for the existence of the correct mongodb extension on init, throws a more useful exception message to hopefully nudge people forward.
For folk upgrading from mongo to mongodb the wrapper client would through a very unhelpful message.
> Slightly more useful message for people upgrading from old mongo

- Tests/_bootstrap.php
- Tests/_shims.php
Added some shims to get travis unit tests working again
Travis changed their build environment recently, which is causing unit tests to fail
> Adding PHPUnit shim for 5.6 travis builds

- Idno/Common/Entity.php
Passing slug_extension as a separate variable so it can be appended after slug creation
Avoid an infinite loop under certain circumstances
> Pass slug extension as a separate variable

- IdnoPlugins/IndiePub/Pages/MicroPub/Endpoint.php
With these changes, Known now passes the basic Micropub JSON syntax tests at https://micropub.rocks: 200, 201 and 203. The others will require more substantial changes to how Known stores posts. This is essentially just a syntax transformation from JSON to how Known already handles form-encoded Micropub requests.
This also adds support for handling checkins that [OwnYourSwarm](https://ownyourswarm.p3k.io) sends in JSON format.
Some Micropub clients, such as https://ownyourswarm.p3k.io and https://ownyourgram.com send JSON requests in addition to or instead of form-encoded requests.
> accept JSON micropub requests and checkins

- docs/plugins/community.md
pnut.io is a Twitter-like status update social network
Also added note to plugin for App.net, which has been shut down. Please keep the link to the plugin as it was actually used as a template for the pnut plugin and may be useful to others in the future for this reason.
> Added syndication plugin for pnut social network

- version.known
Changed human readable version from 0.9.2 to 0.9.5
Because the perpetual 0.9.2 is making triage very frustrating, and is starting to feel like that episode of Buffy with the mummy hand.
> Bumping human version

- ISSUE_TEMPLATE
Added a prompt in the issue template for some clarification and the contents of version.known
I keep on asking for this information, it'd be helpful for triage if it was just given.
> Prompting for some version info

- Idno/Pages/File/View.php
* Fixed a by one error in range content
* Suppressed fseek warning for pedantic mode
* Handle constructing bytes from non-file stream resources (which are often chunked to 8192 bytes, see php docs for fread)
* Range downloads were failing
Closes #1682
> Handle partial content from non-file sources

- README.md
Fixed the markdown for titles in the readme
Somewhere along the line the spaces were lost (or github changed its rendering engine), either way, titles stopped rendering correctly
> Fixing spaces

- Idno/Pages/Account/Register.php
Added a hook to allow third party plugins to validate user signup
I needed to limit signups to only certain email domains.
> Add hook for user registration validaton

- IdnoPlugins/Status/templates/default/entity/Status.tpl.php
Removed strip_tags from status message output
It was unnecessary since we also pass text through htmlentities, and was resulting with text using a < from being stripped.
> We don't need to strip tags if we're encoding html entities

- docs/plugins/community.md
Added a new plugin for tracking what you watch (TV and movies), including a Plex webhook.
Because I wanted to!
> Adding Watching plugin

- Idno/Data/Mongo.php
* Prevent encoded values appearing in decoded object
* Prevent multiple double encoding (and corresponding bloat of object size)
* Now possible to retrieve dotted values
They were all broken
> Mongo dot encoding

- Idno/Common/Page.php
Test for existence of $headers['Accept']
Pedantic mode unit tests were failing
> Avoid notice / pedantic mode failure where accept headers are missing

- Idno/Pages/Admin/Diagnostics.php
Removed explicit pdo_mysql check in diagnostics
It is implicit that you've got the pdo driver for your current engine installed in order to get as far as the admin diagnostics page, and the mysql check was causing errors for those on other engines.
> Closes #1707: Remove explicit mysql pdo check

- templates/default/shell/nav.tpl.php
Test for the environment variable in nav
Nav was shown even if hidenav was set to true
> Fixing hidenav for share template

- templates/rss/shell.tpl.php
Replaced strip_tags with htmlspecialchars
So that title on certain elements weren't lost
> Closes #1704: Encode entities in output

- IdnoPlugins/Convoy/templates/default/convoy/account/signup.tpl.php
- IdnoPlugins/IndiePub/templates/default/account/indiepub.tpl.php
fixed h1 heading in Convoy plugin and added row div in IndiePub plugin account page
Cycling through the "Account settings" sub pages the layouts of "Connect services" and "IndiePub" weren't in line with the other pages. Now they are.
> fix layout of Convoy+IndiePub plugin account page

- IdnoPlugins/Event/templates/default/entity/Event/edit.tpl.php
Making start/end control datetime-local
Adds a date picker where supported, without the need for jquery or similar libraries.
Discuss as to whether this is the correct approach.
cc/ @benwerd
> Closes #739: Using datetime form control where supported, because HTML5

- IdnoPlugins/IndiePub/Pages/IndieAuth/Auth.php
This fixes the token endpoint to not require the `state` parameter when exchanging the authorization code for an access token. https://tools.ietf.org/html/rfc6749#section-4.1.3
A common mistake in the OAuth flow is expecting the client to send the state parameter in the token request. This means some clients were unable to sign in because they (correctly) were not sending the `state` parameter.
> don't check state parameter on token request

- Idno/Data/MySQL.php
- Idno/Data/Postgres.php
- Idno/Data/Sqlite3.php
- Tests/Data/DataConciergeTest.php
I added the capability to query with "<" and ">" operators to the MySQL backend. If I also need to add support for other database backends to get this PR merged, please do let me know, and I'll try and work on those too. From what I could tell, the only supported backend at this point is MySQL, but I could be wrong!
To enable me to create an "On This Day" feature for my website. You can find my implementation here:
https://github.com/cleverdevil/CleverCustomize/blob/master/Pages/OnThisDay.php
... you can see it in action here:
https://cleverdevil.io/onthisday/
https://cleverdevil.io/onthisday/04/18
> Adding the ability to query with "<" and ">" operators to MySQL.

- docs/install/index.md
- docs/install/troubleshooting.md
- mkdocs.yml
Added a troubleshooting section to the docs
So we have a place to start adding non-bug related common configuration and installation problems.
> Adding troubleshooting section to docs

- Idno/Core/Session.php
Remove a notice error
When called from unit tests logoff is called sometimes without a user being logged on, this causes a notice error (which is fatal with pedantic mode on)
> Fixing travis pedantic mode build error

- docs/plugins/community.md
As far as I can tell, this plugin never really had any true functionality, it certainly never worked as a video plugin, wasn't supported, and has since been replaced by a working version by Christian Weiske
* [Video](https://github.com/tjgillies/Video) – Post videos to your Known site, by [Tyler Gillies][]
> Remove link to non-working video plugin

- Idno/Common/Entity.php
Removed getURL() call from getUUID()
It was possible, using user set urls, to have a UUID which was generated as being the same as a previously deleted object. Not only did this mean UUIDs could be changed, but it meant that UUIDs, which are often used to address an entity, could take the ownership of a deleted entity.
Major bad times.
Closes #1741 
This is a 3 line fix that addresses the root cause of #1741, this renders tombstoning unnecessary.
Closes #1742 
Closes #1743
> UUIDs now exclusively machine generated

- IdnoPlugins/Like/templates/default/entity/Like.tpl.php
- Themes/Black/css/default.css
- Themes/Fauvists/css/default.css
- Themes/Green/css/default.css
- Themes/Kandinsky/css/default.css
I updated the bookmark template to use `u-bookmark-of` instead of `p-bookmark`. This fixes the parsed version of bookmark posts.
The bookmark Microformats were setting only the plaintext `bookmark` property which caused bookmarks to not actually reference the URL they are bookmarks of.
> fixes bookmark Microformats markup

- IdnoPlugins/Like/Like.php
Changed from using `htmlspecialchars_decode` to `html_entity_decode` for more complete processing of title text in HTML.
This fixes #1700
> Fixing #1700 by properly decoding entities into unicode.

- Idno/Core/Admin.php
- Idno/Core/Logging.php
- Idno/Pages/Admin/Logs.php
- templates/default/admin/logs.tpl.php
- templates/default/admin/menu.tpl.php
Added a setting to turn on native log capture, whereby Known generated log messages will be output to a temporary file visible from the admin interface, as well as being outputted to the apache php logs
Sometimes it was unnecessarily hard/impossible to get vital debug information from certain platforms. This provides a workaround...
> Introducing capture_logs config setting

- docs/install/upgrade.md
Pointed out default database engine change
It was unclear, caused problems.
> Refs #1754: Clearer mongo upgrade instructions

- Idno/Pages/Session/Login.php
- templates/default/pages/403.tpl.php
Switched for url encoding to base64 encoding for fwd parameter
urlencoding a urlencoded link in sharing caused modsecurity to have a hissy fit, I'm hoping that base64 is safer.
> Closes #1651: Using url safe base64 encoded urls instead of urlencoding

- Idno/Common/Entity.php
- Idno/Core/SynchronousQueue.php
- Idno/Data/MySQL.php
- Idno/Data/Postgres.php
- Idno/Data/Sqlite3.php
- Idno/Files/LocalFileSystem.php
- Tests/CryptoTest.php
Switched to using mt_rand() instead of rand()
Spotted a few places where rand() was passed with parameters resulting in low entropy, in addition on certain platforms (e.g. windows) getrandmax() was unreliably low. 
mt_rand() is both more reliable and faster, so switching to use this for instances where rand() was called.
> Increase entropy / use more reliable random number generator

- Idno/Common/Page.php
- Idno/Core/Input.php
- Tests/Core/InputTest.php
Second attempt at making input defaults more consistent.
Now, passing a default of 'null' will not result in a default of 'false', even though these are both empty()
Was causing problems for some people.
> Make input default returns more consistent (replaces #1539).

- IdnoPlugins/Like/Like.php
- IdnoPlugins/Like/Pages/Callback.php
- IdnoPlugins/Like/templates/default/entity/Like.tpl.php
Modified the title extraction regex to be less greedy 
Old regex extracted title from the first <title> tag to the *last* </title> .. so if the content contained malformed content containing a second </title> it'll return everything in between, resulting in a lot of garbage.
> Fixing like

- Tests/CryptoTest.php
- external/bonita/includes/Bonita/Forms.php
Moved from sha1() hash to sha256 hmac
hmacs are cryptographically secure, so it's harder to fix the site secret (public key).
Holding off merge until status of #1772 has been decided.
> Updating CSRF token generation to a more secure mechanism 

- IdnoPlugins/Photo/templates/default/entity/Photo.tpl.php
Using photo title as image alt attrib.
Accessibility
> Closes #1548: Use title for alt tag.

- Idno/Common/Page.php
- templates/json/shell.tpl.php
Explicitly parse out exceptions in JSON shell
The json encoded version of exception was pretty much useless...
> Json exception

- .htaccess
- htaccess-2.4.dist
- htaccess.dist
Removed header expiry header control from htaccess
It isn't our place to do this, and often conflicts with server admin's often better cache and proxy settings.
Closes #1791
> Removing cache control headers from htaccess files

- Idno/Core/Config.php
Added the ability to specify the base path/domain via environment variable, for cases where it's not available from SERVER_NAME
To allow console plugins access to configurations specified in domain specific configuration files.
> Allow the active domain base url to be specified by environment variable

- templates/default/shell/headers.tpl.php
Disabled X-Frame-Options clickjacking defence, instead leaving it to admins.
It was causing problems for some, as well as chrome / Firefox plugin
Closes #1797
> Temporarily removing X-Frame-Options

- Idno/Stats/Timer.php
Logging now shows class
To distinguish between types of timer
> Distinguish between types

- Idno/Caching/FilesystemCache.php
- Idno/Core/Idno.php
* Added a file system cache class
* Use this as default if other caching isn't available
* I needed a simple disk cache for another project, thought it'd be useful as a wider context and to ensure that a persistent cache is always available as a fallback.
> Introducing a disk cache class

- Idno/Stats/Timer.php
Catch exception in logTimer()
In usage, having the exception bubble up was annoying
> Catch exceptions when logging

- Idno/Pages/Entity/View.php
Partial reversion of 673697a8c0008b6839d21d38959bbfaf732bf767 to no longer lie about permalink update time, leaving other cache headers at their default settings.
Always setting last-modified to _now_ was causing artefacts with feed reader notifications
> Partial restoration of permalink caching headers

- Idno/Caching/FilesystemCache.php
@ on the unlink
Prevent notice error, and pedantic mode crash
> Prevent notice error when unlinking non-existent cache

- Idno/Core/Session.php
Allow api users to be identified by email address in addition to username
Some authentication systems identify by email address and leave handle hidden.
> Allow an email address as secondary API identifier

- docs/install/advanced.md
- docs/install/config.md
- mkdocs.yml
Introduced an advanced options section to the installation guide, included documentation of the asynchronous event queue
Needed documenting.
> Advanced docs

- Idno/Common/Page.php
- Idno/Core/Idno.php
- Idno/Core/Logging.php
- Idno/Stats/DummyStatisticsCollector.php
- Idno/Stats/StatisticsCollector.php
- Idno/start.php
* Hooks to collect stats of a running system
* Added some initial stats for counting events (which gives us object saves, log ins etc for free), log messages (gives us errors and warnings), fatal errors and a timer for overall page construction (so we can see cases when a change causes a overall slow down
* Dummy stats collector designed to be replaced with a functional back end
In a nutshell: https://codeascraft.com/2011/02/15/measure-anything-measure-everything/
But more, to give more data of running systems, and to make it easier to track down problems.
> Advanced stats

- Idno/Common/Page.php
Fixes "Illegal string offset" warnings trying to index into the result of getallheaders().
I'm working on a Known docker image based on alpine, and I am getting 502's with a ton of these warnings trying to index into the result of the function. I changed the initialization of `$headers` to reflect the expected return type.
> Return an array from getallheaders() in Page.php

- Idno/Core/Template.php
- Tests/Core/TemplateTest.php
* Truncate display of urls at 100 chars
* Additional <wbr> on = to handle long get parameters
Some urls pasted in looked butt ugly
> Url handling

- templates/default/file/picker/image.tpl.php
Put a try/catch around exif extraction
Some files, which were images, were causing problems during exif extract and so preventing the upload button from displaying.
> Prevent decoding errors from stopping execution

- templates/default/shell/javascript.tpl.php
Disabled fragmentions
There appear to be instances where this library causes script execution
failures:
```Empty string passed to getElementById(). fragmention.min.js:1:735```
Since nobody(?) really uses this, and the project appears to no longer be
maintained, I'm removing it for now.
Refs chapmanu/fragmentions#14
> (temporarily?) removing fragmentions library.

- IdnoPlugins/Text/Entry.php
- IdnoPlugins/Text/templates/default/entity/Entry/edit.tpl.php
* Blog posts now no longer return "Untitled" when no title is set
* Titles set as a "required" attribute on forms to encourage proper titles
* "Untitled" posts caused unhelpful slug generation, and caused a lot of #1858 to be seen a lot in the wild. This goes some way to mitigating - since empty titled slugs are now generated from content or failing that are random.
> No "untitled"

- Idno/Core/Template.php
- IdnoPlugins/Checkin/templates/default/entity/Checkin/edit.tpl.php
- IdnoPlugins/Event/templates/default/entity/Event/edit.tpl.php
- IdnoPlugins/Event/templates/default/entity/RSVP/edit.tpl.php
- IdnoPlugins/Like/templates/default/entity/Like/edit.tpl.php
- IdnoPlugins/Media/templates/default/entity/Media/edit.tpl.php
- IdnoPlugins/Photo/templates/default/entity/Photo/edit.tpl.php
- IdnoPlugins/Status/templates/default/entity/Status/edit.tpl.php
- IdnoPlugins/Text/templates/default/entity/Entry/edit.tpl.php
- templates/default/content/access.tpl.php
- templates/default/content/syndication/account.tpl.php
- templates/default/forms/input/datetime-local.tpl.php
- templates/default/forms/input/file.tpl.php
- templates/default/forms/input/hidden.tpl.php
- templates/default/forms/input/input.tpl.php
- templates/default/forms/input/longtext.tpl.php
- templates/default/forms/input/richtext.tpl.php
- templates/default/forms/input/select.tpl.php
* Added a form control documentation method (documentFormControl()) to Template
* Extended standard form controls to automatically document themselves
* Extended bundled thingies to use form controls
* Introduced a couple of new form control templates
* Extended form controls to clear up their own variables to prevent ongoing polution (benwerd/bonita#2)
* Fixed a few other bugs I found along the way
Now possible to make an API get call to establish what form fields are available, and what values the endpoint is expecting.
> Self documenting API

- Idno/Common/Component.php
- Idno/Core/Idno.php
- Idno/Core/Language.php
- Idno/Core/Translation.php
- Tests/Core/LanguageTest.php
- docs/developers/languages/index.md
- mkdocs.yml
Added a few things I saw as missing from the initial Language() mechanism as written by @benwerd 
* Added some candy to make it easier to load one or more translations
* Detect and set the current language based on passed parameter, or from browser string
* Added an actual way to get translation string, with parameters, suitable for echo (as it was you could only translate static strings, this now allows sprintf substitution)
The initial take on this looked somewhat incomplete, however I don't know what Ben had in mind with this
Closes #1871
> More language

- nginx.conf
- templates/default/shell/css.tpl.php
- templates/default/shell/footerjavascript.tpl.php
- templates/default/shell/javascript.tpl.php
Restore cache-busting for JS and CSS based on machine version
Got tired of telling folk to ctrl-f5 all the goram time
> Cache busting

- Idno/Entities/UnfurledUrl.php
- templates/default/entity/UnfurledUrl.tpl.php
If not otherwise specified, interpret a remote page as UTF-8 during unfurling.
The dom document was being corrupted meaning certain links that had UTF-8 characters were being incorrectly handled.
> Unfurl encoding

- templates/default/entity/annotations/mentions.tpl.php
- templates/default/entity/annotations/replies.tpl.php
- templates/default/entity/annotations/shares.tpl.php
s/usort/uasort
Permalink is used as array index, so needed to be preserved
> Preserve annotation urls in array sort

- templates/default/file/picker/image.tpl.php
Remove "capture" attribute
Allow for capture or select on ios. This is the same workaround as in #1730 .
> Allow capture or select on ios for file selector

- IdnoPlugins/Photo/templates/default/entity/Photo.tpl.php
When a photo is clicked on on a permalink page, the original image is displayed
While having title and image go to the permalink page in a feed view, it makes sense for the original image to be referenced in the permalink page.
> Link to original image on permalink

- templates/default/entity/UnfurledUrl.tpl.php
Removed htmlentities call on UnfurledUrl
It was unnecessary, and has caused problems for some proxied image urls
> Since this is a proxied image, we do not need to encode entities

- Idno/Common/Page.php
- Idno/Core/Idno.php
- Idno/Core/Version.php
Moved version build and fingerprint stuff into it's own component
The central Idno class is starting to become a little bulky, this tidies things up a bit as well as makes is easier to use version.known for more than just build and version.
> Version file

- IdnoPlugins/IndiePub/Pages/MicroPub/Endpoint.php
Also throw the error correctly.
- Check if the annotation type is correct
- Call the wrong-type-error function with the correct number of arguments
- Fetch post by slug not UUID, that does not work anymore.
Adding annotations via micropub (#1535) was broken.
> Correctly check type when sending annotation via micropub

- ConsolePlugins/EventQueueService/Main.php
- Idno/Entities/AsynchronousQueuedEvent.php
Enabled support for mongo asynchronous queues.. note, this also requires the latest MongoDB driver from PECL
I wanted to use async queues, and I'm still stuck on mongo
> Asynchronous Queues on mongo

- Idno/Core/AsynchronousQueue.php
Added a date/time stamp to key events
It was hard to see back to when events were actually dispatched.
> Adding dates to key events for tracking

- Idno/Common/Entity.php
May Entity __construct() override call parent
So all entities can register hooks/pages/etc as part of component init.
> Lets make sure we also initialise the rest of the Component

- Idno/Core/Idno.php
- Idno/Pages/Chrome/ServiceWorker.php
- chrome/service-worker.js
- js/service-worker.js
- js/service-worker.min.js
- templates/default/chrome/manifest.tpl.php
- templates/default/shell.tpl.php
- templates/default/shell/favicon.tpl.php
- templates/default/shell/opengraph.tpl.php
- templates/default/shell/webapp.tpl.php
* Brought Android manifest.json up to date
* Enabled said manifest
* Added a basic service worker implemented via virtual page so it appears in the root
* Split webapp stuff off to its own shell template
* Webapp install was missing for 'droid
* Needed a service worker for notifications on android devices, tbd.
> Misc tidy of some kruft

- Idno/Entities/User.php
- templates/default/account/settings/tools.tpl.php
* Added more entropy to api key generation
* Changed tool control to be consistent with skinned controls elsewhere.
Did some more thinking and research on standard practices, and #831 isn't such a problem since it's never user generated and won't expose other accounts. Admin limit prevents system wide damage so an attacker can only do what they can do anyway, and although attack via database dump is still an issue, since this is a generated value we won't be exposing other user accounts elsewhere.
So, added some more entropy to the key.
> More entropy apikey

- known.php
Allow php files in ConsolePlugins/ to be scanned for console plugins
It was time consuming to create full directory hierarchies when you just needed a quick console file.
> Allow stub console plugins

- docs/install/sharedhost.md
Added link to Dreamhost installation instructions on kiaikim.com
Add a link to my kiaikim.com post for installing Known on Dreamhost
Would have added the text to the site, but not sure if that's the way it should be done. Plus this github interface is new to me and I'd probably mess it up somehow. Feel free to copy the text and add/edit it directly onto the site.
> Added Dreamhost link

- Idno/Core/Config.php
Added the Event plugin to the initial plugins
It was reported that folk were finding this functionality hard to find when defaulted off, and people were getting questions
> Changing install defaults: Default events to enabled.

- Idno/Core/Session.php
Rearranged the sequence of session setup.
The cache limiter isn't supposed to be modified once a session is started.
> Resolving a warning in PHP 7.2 with sessions.

- Idno/Common/ContentType.php
- Idno/Common/Entity.php
- Idno/Entities/AsynchronousQueuedEvent.php
- Idno/Entities/BaseObject.php
- Idno/Entities/GenericDataItem.php
- Idno/Entities/Object.php
- Idno/Entities/RemoteObject.php
- Idno/Entities/UnfurledUrl.php
- Tests/Common/EntityTest.php
Introduces BaseObject, deprecated Object and migrates classes across.
This is soft deprecated so as to mitigate hardship for plugin authors.
Object is a reserved word in PHP 7.2+, so we need to migrate away.
Closes #1977 - includes all this stuff (thanks for the PR) but does a couple of other bits.
Closes #1980
> Rename Object to BaseObject

- Idno/Common/Page.php
- Idno/Pages/Admin/Diagnostics.php
* Added a no cache option to page
* Disable caching on diagnostics page
Changes introduced in ce203f7 had a knock on effect that, since caching actually works, the diagnostics page broke.
> Fix diagnostics

- Idno/Common/Page.php
- Idno/Core/Bonita/Forms.php
Logging somewhat redacted details for both sides of the CSRF exchange - token generation and token validation.
Some sites are getting "Invalid token" errors, so this information is being corrupted somewhere along the line. I'd like to know what, and when.
> CSRF Token debug

- docs/developers/standards.md
Expanding the documentation a little around comments.
I think it was needed, because I want to encourage commenting!
> Expanding standards document around comments

- Idno/Core/ArrayKeyTranslation.php
- Idno/Core/Language.php
- Idno/Core/Translation.php
- Tests/Core/LanguageTest.php
- docs/developers/languages/index.md
Changed the way that the translation code works slightly to no longer pass around strings (although the Massive Array of Strings mechanism is still supported). 
To make the translation code much more flexible, and allow easier support, of other translation mechanisms (e.g. gettext). It also allows for a heterogeneous environment, with multiple different translation mechanisms being supported.
> Extend translation mechanism to be more flexible

- docs/developers/commit-messages.md
Talk about projects in subjects
It is a good idea to reference the logical project that a commit is referencing, e.g. "Documentation" or "Security"
> Documentation: Reference "projects" in commit message subjects

- Idno/Core/Language.php
Provide a way to capture untranslated strings in order to generate work lists, in the future. Not perfect as it'll only detect stuff when pages are hit, but it's better than nothing.
Needed a way to capture strings which have not been translated.
> i18n: Add a mechanism to capture untranslated strings

- Idno/Core/Language.php
Use vsprintf instead of sprintf
This is the correct use when passing parameters
> Use vsprintf instead of sprintf

- IdnoPlugins/IndiePub/Pages/IndieAuth/Token.php
IndieAuth scopes were hardcoded to "post," rather than using the requested scopes. I fixed the code to read the scopes off of the original request, and passing those through.
This created several issues for third-party clients connecting to Known via IndieAuth, including Together, Quill, and OwnYourGram.
> Fix indieauth scopes

- Idno/Common/Page.php
- Idno/Core/Bonita/Forms.php
* Improved token generation debug
* Stripped GET line from action when generating a CSRF token
I started running into invalid tokens being generated (which may or may not be the same as the issue @benwerd has been hitting), but in this case it was being caused by the GET line being included in the token generation. Since the GET line could vary between generation and post, this caused problems.
> Normalise action generation

- Idno/Common/Page.php
Truncate the fingerprint
To avoid any possibility of some future tech will work out the build version from the fingerprint, lets truncate it. This will give us the same result (ability to tell whether core has been updated) without leaking any info.
> Truncate the fingerprint

- Idno/Entities/User.php
- IdnoPlugins/IndiePub/Pages/IndieAuth/Approve.php
- IdnoPlugins/IndiePub/Pages/IndieAuth/Auth.php
- IdnoPlugins/IndiePub/Pages/IndieAuth/Token.php
Added a helper method to User called `getIndieAuthURL`, which is used in place of the `getURL` method in the IndieAuth plugin. Then, ensured that the IndieAuth plugin is consistent in how it pulls the `me` from the user.
Known was playing a bit fast and loose with user URLs. In the case of a single-user instance, in many places the base URL for the site would work just fine, but in others, you'd have to substitute the profile link, which isn't quite right, and threw off other aspects of IndieAuth.
With this change, if the single-user mode is enabled, the base URL of the site can be used consistently throughout, otherwise it falls back to the old behavior.
> Enabling single-user Known sites to use their base URL as their "me" for IndieAuth

- Idno/Caching/FilesystemCache.php
- Idno/Common/Page.php
- Idno/Common/Plugin.php
- Idno/Core/AsynchronousQueue.php
- Idno/Core/Session.php
- Idno/Core/TokenProvider.php
- Idno/Core/Webservice.php
- Idno/Data/Mongo.php
- Idno/Entities/GenericDataItem.php
- Idno/Files/LocalFileSystem.php
- Idno/Pages/Account/Settings/Following/Bookmarklet.php
- Idno/Pages/Admin/Statistics.php
- Idno/Pages/Search/User.php
- Idno/Pages/Service/Security/CSRFToken.php
- Idno/Pages/Service/Web/ImageProxy.php
- Idno/Pages/Service/Web/UrlUnfurl.php
- Idno/Stats/Timer.php
- Idno/Stats/TotalTimer.php
Added translation hook around (most) thrown exceptions
Errors should be available in all languages
> i18n: Apply translation hooks to thrown Exceptions

- Idno/Data/MySQL.php
- Idno/Data/Postgres.php
- Idno/Data/Sqlite3.php
- Tests/Data/ConfigTest.php
Added ordering to the sql query in getAnyRecord to return the latest matching
In cases of multiple entries this caused inconsistent results
> Make getAnyRecord consistent with mongo

- .travis.yml
- Idno/Core/DataConcierge.php
- Idno/Pages/Admin/Diagnostics.php
* Diagnostics entry to show the multiple config bug
* PHP7 support to catch fatal errors during object instantiation
* Wanted to try and get down to the why of why some domains had multiple configs
* Handle left over Entity in old unit tests
> Config diagnostics and entity instantiation error handling

- Idno/Core/Input.php
This function normalises the array to a sensible structure, so instead of:
```
$_FILES['file'] = [
'name' => [
'foo',
'bar'
],
'size' => [
123,
456
]
]
```
You get
```
$_FILES['file'] = [
0 => [
'name' => 'foo',
'size' => 123
],
1 => [
'name' => 'bar',
'size' => 456
]
]
```
Helper function based on comments from #1991
> Helper function to retrieve $_FILES details

- templates/default/entity/UnfurledUrl.tpl.php
Adding target="_blank" to unfurl urls
It happened a couple of times that I accidently clicked on an unfurled URL while editing a post, causing me to navigate away and losing the post.
Simplest solution is to open unfurled links in a blank tab/new window.
> Open unfurled urls in a new window

- Idno/Common/Page.php
- Idno/Core/Input.php
- IdnoPlugins/Status/Status.php
* Fixing input functions to better transcribe certain inputs ('0', ' ', etc) as their correct values
* Adding exception for '0' body 
* Fixing status edge case
* Fixing Input functions to handle values that would erroneously be evaluated as false by empty()
> Handle status messages of '0'

- .gitignore
- Idno/Core/Config.php
- configuration/.htaccess
- nginx.conf
- warmup/settings.php
- warmup/top.php
Originally config files were scattered around the root. This patch attempts to also load configurations from a configuration directory.
As well as tidying things up it also means that the *whole* root doesn't need to be web server writable for automatic configuration (which will help us with things like #2060 ). It also helps with future modularisation.
> Moving configuration to its own directory

- Idno/Core/Bonita/Templates.php
- Idno/Core/Template.php
Adding a mechanism to use alternative page shells.
Allow pages to render alternative page shells without switching out to alternative template hierarchies 
Ref #1846
> Providing a mechanism to specify alternative shells

- IdnoPlugins/Checkin/templates/default/entity/Checkin.tpl.php
- IdnoPlugins/Like/templates/default/entity/Like.tpl.php
- IdnoPlugins/Media/templates/default/entity/Media.tpl.php
- IdnoPlugins/Photo/templates/default/entity/Photo.tpl.php
- IdnoPlugins/Status/templates/default/entity/Status.tpl.php
- IdnoPlugins/Text/templates/default/entity/Entry.tpl.php
- templates/default/forms/output/tags.tpl.php
* Added a common output view for (deprecated) tags
* Handle both string and array tags
* Updated core plugins
While Known's interface uses #hashtags rather than explicit tags, some clients use them, and they weren't being drawn very well at all
> Unify tagging display

- IdnoPlugins/IndiePub/Pages/MicroPub/Endpoint.php
Added a secondary mechanism for detecting mime from a downloaded file
Some people where having mime type problems when using Quill. This is a speculative fix for an issue I've not yet encountered...
Refs #2097
> Adding a secondary mime-type detection mechanism for uploadFromUrl()

- .gitignore
Adding .AppleDouble to the gitignore.
Because apple products chuck these _everywhere_ and it's really fracking annoying.
> Adding .AppleDouble to gitignore

- Idno/Core/Idno.php
Hooked the cache into the component factory
So it is possible to specify the base cache being used.
> Allow the core cache used to be pluggable

- .travis.yml
- Idno/Core/Config.php
- Idno/Core/Migration.php
- Idno/Entities/RemoteUser.php
- Idno/Pages/Account/Settings/Feedback.php
- Idno/Pages/Admin/Diagnostics.php
* Reverting the breaking change introduced in an earlier commit
* Allow Mongo build tests
* Tidied up some other cruft
While I understand the reason for hard coding an ID for the config object (which I understand was a workaround for the previously introduced multiple config bug - now fixed) using such IDs is not compatible in Mongo or other nosql dbs which all tend to prefer their own IDs so they can manage efficient indexing.
Only one Config can ever be returned in later Known builds, so the hard coded ID shouldn't be necessary. Cleanup of the sawdust should be accomplished by a separate tool.
> Fixing mongo

- Idno/Core/Installer.php
- warmup/CLI/CLIInstaller.php
- warmup/webserver-configs/config.ini.template
Added the ability for the installer to handle different database engines (e.g. postgres).
Web installer is still hard coded to MySQL, however CLI is more flexible.
Because they exist, and should be easier to use.
Refs: idno/Known-Docker#9
> Installer: Specify different database engines

- README.md
- docs/install/instructions.md
Linking people to the unofficial withknown install packages
Bit cheeky, but this was by popular request, and the official binary is well over a year old at this point.
> Alternative package

- languages/processfile.php
Use correct input variable for line number generation
Previously the language file generator was using the wrong input data in order to calculate the line number of the specific translation string.
> i18n: Correcting line numbers on .pot file language generator

- README.md
Remove reference to fontello
Pretty sure we no longer use Fontello, so probably should remove reference to it.
> Remove reference to Fontello

- templates/default/content/unfurl.tpl.php
The text labels were huge, and unfortunately inconsistently sized across templates. Here's how the revised version looks:
> Shrinking controls for unfurl to icons only

- Tests/EnvironmentTest.php
I'm not actually sure we should have the environmental tests at all - these don't check code quality. But I removed the htaccess and config.ini tests for now because configuration can be loaded a number of ways, and some people are using nginx with custom rules to run Known. It doesn't seem fair to restrict to config.ini and Apache.
> Removing tests that limit for certain kinds of installations

- Idno/Pages/Service/Queues/Queue.php
Check that queue isn't empty before iterating it.
Empty queues produce warning if empty in the foreach.
> Check that queue isn't empty before iterating it.

- IdnoPlugins/Comments/Pages/Post.php
- IdnoPlugins/Comments/templates/default/comments/public/form.tpl.php
I changed the comment form to avoid using `name` and `url` fields, and include blank, hidden fields with those names in a hidden form. The idea is that bots will see `name` and `url` first in the form and add content to those. In addition, every site's real `name` and `url` fields will be named something different.
Public comments on my site were still being heavily abused. Hopefully this stems the tide.
> Creating a deeper spam trap for public comments

- Idno/Core/Webservice.php
- Tests/API/HSTSTest.php
- Tests/EnvironmentTest.php
Added HSTS support to Webservice::send()
HTTP Strict Security Policy is a method by which a web server can instruct a client to address any future requests to a secure endpoint to always use the secure endpoint.
Previously, if a Known webservice call was addressed at http://example.com but was forwarded to https://example.com, future requests would also follow the Location headers. 
Now, if HSTS headers are set on https://example.com, and are found to be valid, any future request to http://example.com will automatically be rewritten to call the secure endpoint.
Refs #2181
> HTTP Strict Transport Security support

- ISSUE_TEMPLATE
“you” to ‘your’ in admin/diagnostics line
It’s been appearing in submitted issues, and it’s started to grate :o)
> Typo. in ISSUE_TEMPLATE

- docs/developers/languages/index.md
Documentation: Reordering the language page.
Gettext is the "blessed" method for adding translations, so this should be made clearer.
Reordered documentation to place gettext section first.
> Documentation: Reordering the language page.

- templates/default/admin/plugins/plugin.tpl.php
Better namespaced requirements in plugin.ini
Looking for things like "build" in plugin.ini is confusing if not properly namespaced in a [requirements] section, so lets prefix each bit with "require-" for non-namespaced fields.
> Better namespaced requirements in plugin.ini

- templates/default/admin/plugins/plugin.tpl.php
Reverse the colour on enable/disable buttons
I found the btn-primary for enable / btn-default for disable confusing since it looks like disabled plugins were enabled.
Reverse these colours.
> Reverse the colour on enable/disable buttons

- Idno/Core/Plugins.php
Attempt to load some settings from package.json
Since some packages are starting to use package.json in order to set various grunt tasks, and since there are a number of common attributes, lets give the ability to use package.json to set some plugin settings.
Requires #2213
> DRY: Attempt to load some settings from package.json

- IdnoPlugins/Checkin/Checkin.php
Correcting translation language call
Should return a string, not an object
> Correcting translation language call

- IdnoPlugins/IndiePub/Pages/MicroPub/Endpoint.php
When submitting the "visibility" property via the Micropub endpoint, the standard is for JSON MF2 is for the property to be specified as an array. This change brings our endpoint into compliance and makes us compatible with more tools.
I was working on a Micropub action for the iOS app Drafts, and noticed that we were handling this incorrectly.
> In MF2 JSON, visibility is specified as an array

- docs/plugins/community.md
Removed Journal plugin from the plugin list.
Tino Kremer removed the repo for the Journal plugin from GitHub.
> Remove Journal plugin

- ConsolePlugins/Import/.gitignore
- ConsolePlugins/Import/Gruntfile.js
- ConsolePlugins/Import/Main.php
- ConsolePlugins/Import/languages/import.pot
- ConsolePlugins/Import/package.json
Adding a console plugin wrapper for import
A number of people have reported issues using the web import code. Often this occurs on large imports where resources (memory, run time, etc) start becoming an issue. This is less of a problem on CLI, and so I'm adding a CLI wrapper for the same import.
> Adding a console plugin wrapper for import

- templates/default/content/syndication/account.tpl.php
Add "name" field to the form documentation
Also, since this is for json output, html entities encoding is not required.
Make parsing easier for API calls
> Add "name" field to the form documentation

- CODE_OF_CONDUCT.md
- docs/community/harassment.md
For some reason GitHub doesn't recognize Known as having a CoC, although it's had one for many years. Hopefully this change ticks the box.
> Adjusting Known's CoC title and contact details

- Idno/Common/Page.php
Attempt to mimic PHP's array name conversion for JSON blobs
PHP magically converts ```foo[]``` into ```$_REQUEST['foo'] => array(...)```, and these names are expected by the code (e.g. for syndication).
This code attempts to mimic this functionality by automatically removing the "[]" from variable names. Actual [] blocks in payload should be escaped and not modified, but report any problems.
> Attempt to mimic PHP's array name conversion for JSON blobs

- Idno/Core/Config.php
Removing Firefox and taking the style / footer JS plugins out of the default stack.
> Adjusting initial plugins

- docs/community/contributors.md
- docs/developers/standards.md
* Reworded a couple of lines for clarity
* Changed Erin's website address
Clarity, and because erinjo.is is now a casino spam site.
> Documentation tweaks

- Idno/Pages/Service/Notifications/NewNotifications.php
Only store created time if notification has actually been retrieved.
This is to avoid a notification loop.
> Only store created time if notification has actually been retrieved.

- Idno/Core/Idno.php
- Idno/Pages/Annotation/Delete.php
- templates/default/content/annotation/edit.tpl.php
Pass annotation permalink as parameter.
Generating an annotation slug from the current URL causes problems in some cases (e.g. if you're behind a reverse proxy, or have changed your site url).
Solution was to explicitly pass the full slug/annotation permalink rather than construct it on deletion.
Fixes #2260
> Pass annotation permalink as parameter.

- Idno/Pages/Service/Notifications/NewNotifications.php
Only display notifications for entities that are available.
It was reported that notifications could throw an exception in some cases. This happened when the notifications endpoint (which uses the email template to render the message) attempted to do so on a target that was no longer available. This meant that notifications sent on posts which were then deleted would cause all notifications to become unavailable.
Solution was to check that the target was available before it was rendered. 
Fixes #2262
> Only display notifications for entities that are available.

- Idno/Entities/User.php
- IdnoPlugins/Checkin/Checkin.php
- IdnoPlugins/Media/Media.php
- IdnoPlugins/Photo/Photo.php
- IdnoPlugins/Text/Entry.php
the :array syntax hint is not widely supported, it seems. Removing as it's not a massively important thing.
> Removing :array hint

- docs/community/contributors.md
Very minor point, but since both these sites have secure versions, we should default to those.
> Use HTTPS urls by default.

- ConsolePlugins/Export/.gitignore
- ConsolePlugins/Export/Gruntfile.js
- ConsolePlugins/Export/Main.php
- ConsolePlugins/Export/languages/export.pot
- ConsolePlugins/Export/package.json
- Idno/Core/Migration.php
- Idno/Data/Mongo.php
- IdnoPlugins/Event/templates/default/entity/RSVP.tpl.php
- IdnoPlugins/Media/templates/default/entity/Media.tpl.php
- IdnoPlugins/Photo/templates/default/entity/Photo.tpl.php
- IdnoPlugins/Text/templates/default/entity/Entry.tpl.php
Adds a CLI export function to match the import function, for similar reasons, that CLI has fewer restriction in terms of runtime and memory.
Improved the export function somewhat in order to make it export more safely, and handle errors better.
Still no import for this, PRs welcome.
Discussion: My thinking is that we should actually remove the web interface import and export code, since this is a pretty technical thing to do. Raising the bar slightly to using the CLI (which works better anyway as you're not going to hit so many memory issues) might reduce some of the help questions. Anyway.
> Adding a CLI export method

- warmup/WebInstaller.php
I am not sure why this was here, but it was causing the canary to skip and return null on nginx or similar, where rewrite was possible, but install would still fail.
Probably a cut and paste error on my part.
Closes #2238
> Remove check for apache_get_version() in rewrite canary.

- Idno/Core/Language.php
Sometimes strings need to be escaped in order for them to be safe to be echoed, this adds a helper method to do so.
Closes #2174
> Adds mechanism to escape translated strings.

- docs/install/config.md
If you accidentally lock yourself out of your install and you haven’t configured smtp, it’s nice to be able to do so, so you can get your password back.
> Document a few useful config items, including smtp

- Idno/Core/Admin.php
The moved `getAdmins()` method didn't have a default value for `offset`, so needed exactly two parameters, breaking some plugins that depended on it. Additionally, methods should always supply  a default value for `offset`.
> getAdmins has a default offset value

- Idno/Core/Idno.php
- Idno/Pages/User/View.php
Adding content type filtering support to user profiles
Previously, user profiles were hard coded to specific content types. 
Solution was to add support to list content types, identical to how it functions on the Homepage.
Refs #178
> Adding content type filtering support to user profiles

- IdnoPlugins/Comments/templates/default/comments/public/form.tpl.php
Replaced id="comment-form" with id="comment-form-(last 5 digits of uuid)" in `comments/public/form.tpl.php` and fix the related JS.
Specifically I detected this in the /profile/username page, this was causing bugs because IDs were being repeated from post to post. Maybe somewhere else the same error could occur.
> Comments plugin: IDs were not unique causing errors

- IdnoPlugins/Photo/Photo.php
Allows the image to show up in the opengraph metadata.
Imitating the getIcon{} override in IdnoPlugins/Text/Entry.php, added an override.  Based the code for finding an image on the code in jsonSerialize().  Chose the large image.
So photo posts could use their photos as thumbnails for Facebook
- [x ] This pull request addresses a single issue
- [ x] If this code includes interface changes, I've included screenshots in this Pull Request thread
- [x ] I've adhered to Known's style guide (I think so?)
- [x ] My git branch is named in a descriptive way - i.e., yourname-summary-of-issue
- [x ] I've tested my code in-browser
- [x ] My code contains descriptive comments
> Add getIcon method to Photo.php

- Idno/Core/Purifier.php
HTMLPurifier now allows iframes for YouTube, Vimeo, SoundCloud, RadioPublic, and Google Maps by default.
Users can also whitelist other iframe sources using the new `allowedIframes` config setting.
Fixes #2314
Users should absolutely be allowed to post safe iframes of their choice.
> Whitelist certain iframe sources

- README.md
Move the backing and sponsors buttons next to build status
Just tidying up
> Move the backing and sponsors buttons next to build status

- docs/plugins/community.md
Remove HTML Purifier
HTML Purifier is now in core (has been for a while), this plugin is no longer needed.
> Remove HTML Purifier

- IdnoPlugins/Text/languages/text.pot
- IdnoPlugins/Text/templates/default/entity/Entry.tpl.php
Adding a missing translation hook for the Text plugin
It was missing, it shouldn't have been
> Adding missing translation

- Idno/Core/Idno.php
Using componentFactory for file systems.
Previously, there was not a unified way to specify alternative filesystems, and plugins (including the S3 plugin) had to resort to the dark arts to install themselves. 
Solution was to use the component factory to unify this mechanism.
> Using componentFactory for file systems.

- IdnoPlugins/OAuth2/Main.php
No longer throw an exception if auth token is not found
Various micropub clients were having problems authenticating if the OAuth2 plugin was activated.
This was because the OAuth2 plugin assumed that all authentication tokens were for it, but this was not the case. 
Solution was to no longer throw an exception if a token wasn't found in storage, but rather, just silently log a debug message.
Closes #2326
> No longer throw an exception if auth token is not found

- docs/plugins/community.md
Updated the Flickr import link
The project referenced is deprecated, use the new one.
> Updating Flickr import link

- templates/default/entity/User/edit.tpl.php
Remove 'camera' attribute from file upload
Bringing this in line with that of the photos plugin, and hopefully avoid issues on mobile where camera capture is forced.
Closes #2311
> Remove 'camera' attribute from file upload

- Idno/Files/FileSystem.php
- Idno/Files/LocalFileSystem.php
- Idno/Files/MongoDBFileSystem.php
- Tests/Core/FilesystemTest.php
Introducing storeContent
Filesystem interface only allowed storing directly from a file, but sometimes you already have the data you want to store
> Modify filesystem to allow storing data from memory

- Idno/Core/Plugins.php
Removing plugin directory autoloader.
The autoloader used to handle situations where an actual Known plugin exists inside a subfolder in a github checkout.
Unfortunately, this was clunky and didn't really work very well, and there's got to be a better way of doing. Probably with *gulp* composer.
> Removing plugin directory autoloader.

- Idno/start.php
- statics/db.php
- statics/error-page.php
Added a static error message template
Bring things a little bit more up to date, making things more professional looking in run up to 1.0
> Improved error message templates

- templates/default/settings-shell/footerjavascript.tpl.php
Removing unused h5f shim reference from settings template
Housekeeping
> Removing unused h5f shim reference from settings template

- Idno/Data/Mongo.php
Mongo error to use new error template
A bit of housekeeping to make the mongodb connection error message use the new failsafe error template.
> Mongo error to use new error template

- Idno/Common/Entity.php
- templates/default/content/notification/wrapper.tpl.php
- templates/default/entity/annotations/likes.tpl.php
- templates/default/entity/annotations/mentions.tpl.php
- templates/default/entity/annotations/rsvps.tpl.php
- templates/default/entity/annotations/shares.tpl.php
Added sanitisation
Webmentions can be badly formatted at times, and potentially this is exploitable.
> Security: Adding some sanitisation to notifications and webmentions

- README.md
- composer.json
- warmup/CLI/CLIInstaller.php
- Upgraded the symfony/console dependency using composer
- Fixed the CLIInstaller.php imports for composter and symfony
I was looking at how to install using CLI and found that the existing tool was inoperative.  Also wanting to test workflow on a simple change.
> Upgrade symfony/console dependency, fix CLIInstaller

- composer.json
Downgrading symfony console to 3.4.22
The 4.x branch requires PHP 7.1 minimum, and my debian install is ooooold.
> Downgrading symfony console to 3.4.22

- IdnoPlugins/Comments/templates/default/comments/public/form.tpl.php
- templates/default/account/login.tpl.php
- templates/default/account/password.tpl.php
- templates/default/account/register.tpl.php
- templates/default/forms/input/captcha.tpl.php
Added a stub captcha hook
Some forms need bot protection, and while captchas have moved on (Recaptcha 3 for example requires no user interaction), we still need a hook for plugins to extend
> Adding captcha hook

- .htaccess
- warmup/WebInstaller.php
- warmup/webserver-configs/htaccess-2.4.dist
- warmup/webserver-configs/htaccess.dist
The AllowOverride check tests that a redirect .htaccess works
Since js/default.js does not exist anymore we redirect to js/known.min.js
During install, there was a hardstop error that said the AllowOverride was not set to All in apache2.conf.
What actually happened was that the check was wrong because it was trying to redirect from js/canary.js to js/default.js and default.js did not exist anymore so that the error was incorrect.
Now, .htaccess redirects from js/canary.js to js/known.min.js so the AllowOverride check during install works.
The user can proceed with the install now.
screenshot of changed error message which now references known.min.js instead of default.js.
got 7 failures from master branch
Error message with fixed file name.
> Redirect to known.min.js in .htaccess

- composer.json
SimplePie is used for importing XML files and for the latent Reader feature.  Later
releases have microformat support that may be of use.
Changelog: https://github.com/simplepie/simplepie/releases
Only extension/php level changes to overall composer state:
Before:
```
simplepie/simplepie 1.4 A simple Atom/RSS parsing library for PHP
`--php >=5.3.0
```
After
```
simplepie/simplepie 1.5.2 A simple Atom/RSS parsing library for PHP
|--ext-pcre *
|--ext-xml *
|--ext-xmlreader *
`--php >=5.6.0
```
Modernizing dependencies
> Upgrade simplepie from 1.4.0 to 1.5.2

- Idno/Pages/Admin/Diagnostics.php
Display whether you're running Known from a package in diagnostics
Detect and warn if you're running directly from a git/composer checkout or an unofficial (soon to be official) package build.
This was done to hopefully help the few folk who are having issues using composer, and nudging them towards the (un)official packages.
> Display whether you're running Known from a package in diagnostics

- README.md
- composer.json
Remove unused `webignition` libraries from `composer.json`  Transitively removes `idna-convert` and `ip-utils`:
```
webignition/absolute-url-deriver 1.5.2 Derives an absolute URL from relative and source URLs
|--php >=5.6.0
`--webignition/url >=1.9.8
|--etechnika/idna-convert 1.0.*
|  `--php >=5.3.0
|--php >=5.3.0
`--xrstf/ip-utils v1.0.0
`--php >=5.3.0
webignition/url 1.9.8 Represents a URL, a library to be used in many other places. Applies semantically-lossless normalisation for comparisons.
|--etechnika/idna-convert 1.0.*
|  `--php >=5.3.0
|--php >=5.3.0
`--xrstf/ip-utils v1.0.0
`--php >=5.3.0
```
General tidiness
> Remove unused webignition libraries

- Idno/Core/Installer.php
- composer.json
- docs/install/requirements.md
- index.php
* PHP 7.0 set to warning
* PHP 5.6 support dropped completely
PHP 7.0 is EOL
> Deprecate PHP 7.0

- Idno/Core/HybridTwigTemplate.php
- Idno/Core/Idno.php
- composer.json
Added the ability for Known to load twig templates in addition to Known Bonita templates
Because it's standard, and we should probably be moving towards that.
> Twig template support

- Idno/start.php
- Tests/_bootstrap.php
- composer.json
- known.php
- warmup/CLI/CLIInstaller.php
Closes #2453: Switching to composer class loader
Replacing Symfony classloader as it's now deprecated by the project. Composer's class loader is also faster, so there's that.
> Closes #2453: Switching to composer class loader

- templates/default/entity/annotations/likes.tpl.php
- templates/default/entity/annotations/mentions.tpl.php
- templates/default/entity/annotations/replies.tpl.php
- templates/default/entity/annotations/rsvps.tpl.php
- templates/default/entity/annotations/shares.tpl.php
Ensure that all annotation links have rel="nofollow"
We should not be endorsing or passing on any pagerank to links in any pings.
> Ensure that all annotation links have rel="nofollow"

- Idno/Common/Page.php
- Idno/Pages/Entity/View.php
- Idno/Pages/User/View.php
- Tests/Pages/User/ViewTest.php
Permalink pages now actually set the object into metadata.
I want to be able to reference the object itself outside of its display shell. This is an easy way to put the object somewhere the whole page, all templates, and other hooks can access it.
> Associates object with a page when a permalink

- Idno/Common/Entity.php
Entity draw methods can now be completely overridden using an event.
Sometimes we may need to change how an entity is drawn, or suppress whether it is drawn at all. There's no good way to do this right now.
> Adds override hooks to entity draw methods

- .htaccess
- warmup/webserver-configs/htaccess-2.4.dist
- warmup/webserver-configs/htaccess.dist
- warmup/webserver-configs/nginx.conf
`.htaccess` line to 403 `.git` and `.github` directories
I feels insecure for those sites running on git version to expose git boilerplate.
> avoid exposing git folders

- composer.json
- tinymce to 5.0.11
- changelog https://www.tiny.cloud/docs/changelog/
- underscore to 1.9.1
- changelog: https://underscorejs.org/#changelog
- vanilla-fitvids plugin to 1.2.0
- mediaelement plugin to 4.2.10
- changelog https://github.com/mediaelement/mediaelement/releases
Update infra components to stay up to date.
> Update tinymce, underscore, vanilla-fitvids, and mediaelement dependencies

- Idno/Pages/Webmentions/Endpoint.php
removed deprecated getPageHandler() in Idno/Pages/Webmentions/Endpoint.php
less deprecation warnings = less errors in log = easier to debug real issues
> remove deprecated getPageHandler()

- .travis.yml
- Idno/Core/Installer.php
Moving warning from 7.0 to 7.1, and ok from 7.2 onwards
7.1 is now in extended support, and php unit is now failing for it
> Warn for 7.1

- warmup/schemas/postgres/2019060501.sql
Adjust SQL to reference the previously created table
Rewrote the date reference
SQL breaks otherwise
> Adjust SQL

- templates/default/forms/input/richtext.tpl.php
Permit the use of <div> in rich text blocks
Some people want to section out their content with div blocks.
Since the only way they can do this is via the html editor, lets assume that people who get
this far have some idea what they're doing, and lets let them add blocks that they can mark up
how they wish.
Closes #2317
> Permit the use of <div> in rich text blocks

- Idno/Pages/Session/Login.php
This patch modifies the session/login endpoint slightly so that it will, when hit by a non-default tempate (e.g. API), will generate and return the logged in user's API token.
API onboarding is hard, and asking individual users to generate OAuth2 applications or enter a long api token string is not feasible. 
I believe the solution is to generate and retrieve the api-token on session/login, after the login process has been completed successfully. I believe this is not a security hole as the user will have passed security checks at this point, and this is no different to hitting the api token endpoint.
Well, that's not actually quite true (see #831), tokens are stored clear in the database and so if that is compromised is will cause problems. Scope for this is limited with this patch as …
> Closes #2240: Return api-token on user login 

- Idno/Core/Purifier.php
adding archive.org and the Knight Lab CDN to default iFrames allowes
I added archive.org/embed
I added cdn.knightlab.com
these are very common places for media and we should encourage greater archive.org over YouTube for openly licensed material. 
- [ x] This pull request addresses a single issue
- [ x] I've adhered to [Known's style guide](http://docs.withknown.com/en/latest/developers/standards/) ([these codesniffer rules](http://docs.withknown.com/en/latest/developers/testing/#code-style-testing) might help!)
> Update purifiier.php to allow more default iframes

- composer.json
Updating swiftmailer to the latest 5.x branch
There was a security advisory for <5.4.5
> Security: Updating to the latest swiftmailer

- templates/default/settings-shell/css.tpl.php
- templates/default/settings-shell/footerjavascript.tpl.php
- templates/default/shell/css.tpl.php
- templates/default/shell/footerjavascript.tpl.php
- old path vendor/bower-asset/mention
- new path vendor/idno/mentionjs
Adjusted paths in templates.
Fixes a bug
> Update paths for adopted mentionjs module

- Idno/Core/Email.php
- Idno/Entities/Notification.php
- Idno/Entities/User.php
- templates/email/content/notification/preheader/like.tpl.php
- templates/email/content/notification/preheader/mention.tpl.php
- templates/email/content/notification/preheader/reply.tpl.php
- templates/email/content/notification/preheader/rsvp.tpl.php
- templates/email/content/notification/preheader/share.tpl.php
To the html notification template, adding a preheader.
This allows some email clients (especially mobile) to display the most relevant information first.
> Adding a notification email preheader

- Idno/Core/Idno.php
- composer.json
- package.json
- version.known
Making canEdit and canWrite on site extensible
To make things more flexible further down the road and allow plugin control of create / access
> Make site level permissions extensible

- languages/source/known.pot
- templates/default/shell/toolbar/search.tpl.php
Made the placeholder attribute use language()->_('Search')
Missing from localisation strings
- [ / ] This pull request addresses a single issue
> Make Search placeholder localisable

- templates/default/shell/footerjavascript.tpl.php
Added in timeago locales file based on language->getLanguage()
il y a environ 2 jours
Localisations are available and we aren't benefitting.
- [/] This pull request addresses a single issue
- [?] If this code includes interface changes, I've included screenshots in this Pull Request thread
- [/] I've adhered to [Known's style guide](http://docs.withknown.com/en/latest/developers/standards/) ([these codesniffer rules](http://docs.withknown.com/en/latest/developers/testing/#code-style-testing) might help!)
- [/] I've tested my code in-browser
> Localise timeago substitutions

- Idno/Core/Language.php
Locales exist that do not fit the 2 or 5 characters assumed by the existing code.
.UTF-8 suffix makes php’s date() output match content encoding of the rest of the page.
Returned value has always been hyphenated, gettext language code expects underscore.
> Fix detectBrowserLanguage() and constructor

- Idno/Data/MySQL.php
- Idno/Data/Postgres.php
- warmup/schemas/mysql/2019121401.sql
- warmup/schemas/mysql/mysql.sql
- warmup/schemas/postgres/2019121401.sql
- warmup/schemas/postgres/postgres.sql
Split search column into its own table
Slowly improving data model by splitting the full text search column into its own table. Later to be dispensed with for some proper search tool like elastic search
> Closes #2485: Splitting search into its own table

- Gruntfile.js
- Groups Idno and templates to remove duplicates
- Pipes through sort to make file changes manageable
Gettext template has duplicate strings from separate Idno and templates passes.
`find` can produce a list of strings in a different order without `sort`ing
- [/] This pull request addresses a single issue
> Change initial gettext string finding pass

- Idno/Pages/Account/Register.php
- Idno/Pages/Admin/Users.php
- languages/source/known.pot
- templates/default/account/export.tpl.php
- templates/default/admin/export.tpl.php
- templates/default/admin/home.tpl.php
- templates/default/admin/homepage.tpl.php
* Fixed missing, and localisation tool-"breaking" localised strings
* Added localisation hooks for yes/no, on/off
These checkins localise bootstrap toggle controls (plus some other localisable strings (in admin/home.tpl.php), fix one prone to creating a truncated entry in the gettext template
(Pages/Account/Register.php & Pages/Admin/Users.php))
Fixed it before but hadn't fixed localisation tool at the time
- [?] This pull request addresses a single issue
- [?] My git branch is named in a descriptive way - i.e., yourname-summary-of-issue
- [/] I've tested my code in-browser
> Localise bootstrap toggles and rearrange localisation template

- languages/source/known.pot
- templates/email-text/account/password.tpl.php
- templates/email/account/password.tpl.php
Changed email templates for password reset so that they are in the same localisation as the site when sent
- [/] This pull request addresses a single issue
- [/] My git branch is named in a descriptive way - i.e., yourname-summary-of-issue
- [/] I've tested my code in-browser
> Localise password reset

- templates/default/account/settings/following.tpl.php
Replaced `is` with `it`
Phrase was incorrectly translating
- [/] This pull request addresses a single issue
> Fix typo in localisable string on line 16

- composer.json
- composer.lock
- Provides an optional peer dependency for mf2/mf2 which allows for
better parsing of html5 syntax.
- Since it is not directly used add the unused package exclusion list.
Adding optional dependency for mf2/mf2
Works around an issue in the Mastodon plugin, plus provides better parsing for html5 elements
and is recommended in the mf2/mf2/README.md
> Introduce masterminds/html5 version 2.7

- languages/source/known.pot
- templates/default/content/notification/like.tpl.php
- templates/default/content/notification/mention.tpl.php
- templates/default/content/notification/reply.tpl.php
- templates/default/content/notification/rsvp.tpl.php
- templates/default/content/notification/share.tpl.php
- templates/default/content/notification/wrapper.tpl.php
- templates/default/settings-shell/footerjavascript.tpl.php
* Adds "liked", "mentioned", etc to localisable strings
* Adds localised date substitutions via timeago
- [~] This pull request addresses a single issue
- [/] My git branch is named in a descriptive way - i.e., yourname-summary-of-issue
- [/] I've tested my code in-browser
> Localise connecting parts of Notification page

- warmup/WebInstaller.php
- warmup/templates/default/pages/elements/messages.tpl.php
- warmup/templates/default/pages/settings.tpl.php
Moved the rewrite canary over to front side javascript.
People kept on having installer problems, which makes sense. Doing the rewrite canary on the back end is going to cause problems in situations where you're behind a proxy, using a container, or running on another port.
It should also really be on the front end anyway. Moving it there.
> Moving rewrite canary over to javascript, making it a non-blocker.

- Idno/Data/MySQL.php
- Idno/Data/Postgres.php
- composer.lock
- warmup/schemas/mysql/2020042101.sql
- warmup/schemas/mysql/mysql.sql
- warmup/schemas/postgres/2020042101.sql
- warmup/schemas/postgres/postgres.sql
Splits metadata tables out into their own tables.
This is the onward goal of improving the database schema bit by bit.
Splitting metadata out into their own tables should make things a bit faster. 
More importantly makes the schema easier to work with, for example, we can offload data integrity (e.g. deleting metadata) off to the database layer to manage. 
It also means we might be able to move over utf8mb4 at some point in the future (#2451), for which the length of indexes proved blockers.
> Schema: Split metadata table out into separate collection based tables

- warmup/schemas/postgres/2020042101.sql
Fixes #2746
Ignores deprecated_metadata
It is unknown / unknowable at this point if the constraint for unique _id, name pairs should be altered into this script, so that if the script errors but allows metadata to drop after transition to deprecated_metadata, if another script could be run without creating duplicates...
> Update Postgres upgrade script to work

- Idno/Common/Page.php
- templates/json/shell.tpl.php
- templates/jsonp/shell.tpl.php
* Added support for browser preflight OPTIONS call
* Added support to pass Authentication BEARER tokens through
Backporting stuff from the Day Job, to allow react front end applications and GQL parsers to federate bearer tokens and handle browser preflight tests
> CORS headers to allow API calls from Javascript / node

- Idno/Entities/Mutable.php
- Idno/Entities/Mutate.php
- Idno/Entities/RemoteUser.php
- Tests/Data/MutateTest.php
Add an interface for changing entity types for certain (related) classes
We need to be able to mutate some entity types, for example, turning a RemoteUser into a full fat user.
> Support entity mutation

- docs/plugins/community.md
I added [Matomo](https://codeberg.org/argovaerts/KnownMatomo) to the Community plugins section.
I made a plugin 🙃
> Added Matomo to community plugins

- docs/plugins/community.md
- fixed the broken URL for the _idno-file-picker_ plugin
- well, the URL was broken :)
> Fix broken URL for idno-file-picker

- .travis.yml
- Idno/Core/Installer.php
- README.md
- docs/install/requirements.md
* Removed official 7.2 support
* Allowing for testing on PHP 8
7.2 is EOL & 8 is out
> Deprecate the EOL PHP 7.2, allow PHP 8
