- templates/default/admin/home.tpl.php
This is to fix the issue #647.
"Set site private" property was incorrect and should be "set site public". See the issue for full details.
> Fix issue #647

- Idno/Pages/Account/Settings/Following/Bookmarklet.php
- templates/default/account/settings/following/mf2user.tpl.php
* Some cleanup of the add friend bookmark to handle missing photo (TODO: scrape remote photo #566)
* If no MF2 data is found, the user is given the opportunity to continue by filling in the details themselves.
* If a feed is detected, the user is fired down the subscribe workflow
> Fixing friends

- templates/default/shell/simple.tpl.php
I didn't test this, but I think something along these lines could fix #682
> Load Google fonts from protocol-agnostic URL

- IdnoPlugins/Media/templates/default/entity/Media.tpl.php
use u-video u-audio for video audio posts respectively per http://microformats.org/wiki/h-entry#Proposed_Additions. Fixes issue 694 and issue 695.
> u-video u-audio for video audio posts respectively

- IdnoPlugins/Photo/templates/default/entity/Photo.tpl.php
name/caption of a photo post should be "p-name" not "p-photo". default.css changes should be made with this one.
> name/caption of a photo post should be "p-name"

- .gitignore
Seams like something that should be in the default .gitignore
> Add Uploads folder to gitignore

- templates/default/admin/themes.tpl.php
I'm sure if I were smarter there'd be a cleaner way to do this than looping through the theme array twice, but this works as a start.
> Active theme displayed first

- Idno/Common/Page.php
Pushed to help others, yet to deploy myself (having unrelated issues with Pound not supporting SNI un packaged build)
> Detect when we're behind a TLS proxy like Pound.

- Idno/Pages/Account/Settings.php
- templates/default/account/settings.tpl.php
> No password cache

- Idno/Core/Email.php
- Idno/Pages/Admin/Users.php
Log errors; match up function post conditions
Refs #775
> Mail debug

- Idno/Pages/File/View.php
> Send last-modified header with image thumbs

- Idno/Core/Config.php
Haven't tested this, but would assume PuSH would work identically over https as over http, @julien51 can you confirm?
> https in hub link

- Idno/Common/Page.php
As per https://np.reddit.com/r/discworld/comments/2yt9j6/gnu_terry_pratchett/
... and there's a Dogeon export template in core ffs.
> RIP Terry Pratchett

- Idno/Pages/Account/Settings/Following/Bookmarklet.php
Minor tweak in error reporting
> Adding visible error for following

- Idno/Core/Config.php
- Idno/Core/Session.php
To address the weird issue, reported on IRC, regarding some problems with later versions on shared hosts.
> Make sha256 default, but configurable

- Idno/Core/Session.php
Validates session against a privilege elevation attack on intercepted insecure cookies + acts as a stub for additional validation.
> Validate session

- Idno/Core/Config.php
- Idno/Core/Webservice.php
Among other things this makes known now fully support tor hidden services
> Make curl settings more configurable

- CONTRIBUTORS.md
Now pointing to the new /Known URL of github !
> a simple URL change

- .gitignore
- Vagrantfile
- ansible/develop.yml
- ansible/roles/apache/handlers/main.yml
- ansible/roles/apache/tasks/main.yml
- ansible/roles/apache/templates/known.conf
- ansible/roles/common/handlers/main.yml
- ansible/roles/common/tasks/main.yml
- ansible/roles/common/templates/ntp.conf.j2
- ansible/roles/known/tasks/main.yml
- ansible/roles/known/templates/.htaccess
- ansible/roles/mysql/tasks/main.yml
- ansible/roles/php/tasks/main.yml
Probably should update the docs once this gets merged with instruction on how to use vagrant + ansible:
For now here is a quick start guide:
1. Install Virtualbox + Vagrant + Ansible
2. cd Known
3. vagrant up
* Ubuntu box will be downloaded
* Vagrant will configure the box
* Ansible will install everything on the server and configure known
4. Go to http://192.168.33.33/ and create the first user
> vagrant and ansible setup for development/local environment

- Idno/Common/Entity.php
This enhancement will open up the possibility of doing more in plugins with major social-network APIs.
> Add optional field to posse links to store bare item ID

- Idno/Core/Config.php
- Idno/Core/Session.php
> Allow configuration of whether database handles session or not

- css/defaultb3.css
Wondering whether this should really be in the plugin, but other CSS for twitter et al are in the main css, sooo....
> Bootstrap 3 linkedin class

- .travis.yml
- Idno/Core/Idno.php
- Idno/start.php
- Tests/EnvironmentTest.php
- Tests/HomepageTest.php
- Tests/_bootstrap.php
- Tests/build/config_sample.ini
- Tests/build/travis-ci-apache
- phpunit.xml
Unit tests run once more, added php 5.6 to travis build, added hook to run per-plugin tests, added placeholder for database init.
Refs #60
> Unit test tweaks

- Tests/EnvironmentTest.php
- Tests/HomepageTest.php
- Tests/KnownTestCase.php
- Tests/_bootstrap.php
Extends the test framework with some fixtures to allow easy access to a test and admin user.
> Users in test framework

- Tests/Data/ConfigTest.php
- schemas/sqlite3/sqlite3.sql
> Fixes config collection in sqlite schema

- Idno/Core/Session.php
- Tests/Core/SessionTest.php
Test session create / destroy, which sometimes exposes dataconciege bugs
> Test session

- templates/default/content/syndication.tpl.php
- templates/default/content/syndication/account.tpl.php
Hooks to activate certain syndication channels automatically, for example activate twitter when replying to twitter.
> Syndication activate

- templates/default/content/syndication.tpl.php
- templates/default/content/syndication/button.tpl.php
Handle case for old style single account syndication plugins (oops.)
> Handle legacy single account services.

- Idno/Data/Postgres.php
The Postgres equiv of MySQL's on duplicate update is kind of a weird
hack, but it seems to work.
Also made the hostname optional so you can connect to postgres
over a unix domain socket instead of a port.
> Postgres equivalent of MySQL "on duplicate update"

- Idno/Core/Logging.php
Purpose: to allow certain submodules to set a context (or multiple contexts), so as to better see where log messages come from.
> Introducing the concept of logging contexts.

- Idno/Pages/Admin/Users.php
- templates/default/admin/users.tpl.php
> Add form for adding users directly, without invitation process

- external/bonita/includes/Bonita/Forms.php
> Updating Bonita to latest

- Idno/Core/Migration.php
* Addresses problems exporting MongoDB ids
* Handles large exports better (however, there is still a problem with #1018)
> Export debug

- Idno/Entities/User.php
- templates/default/account/password/reset.tpl.php
* Uses cryptographically secure method for generating code
* Fixes some CSS errors with reset form
> Password recovery

- Idno/Common/Entity.php
Adding entropy, missed by previous commits (#1049, #1047)
> Slugs must be unique, so we should increase entropy.

- Idno/Core/DataConcierge.php
- Idno/Data/MySQL.php
- Idno/Data/Postgres.php
- Idno/Data/Sqlite3.php
I agree with @pierreozoux, database errors should not return 200 response.
> Closes #1048: Introduce 500 response for database errors.

- Idno/Core/Purifier.php
- Idno/Core/Template.php
> Make internal purifier play nicely

- Idno/Core/Session.php
So that GET api calls are validated correctly
> Normalise api request uri

- Idno/Core/Idno.php
> Check that new database is a subclass of DataConcierge before creating

- Idno/Common/Entity.php
Very long words (or embedded URLs) can cause 10 word slugs to
be longer than 255 characters, overrunning the MySQL column width.
This limits them to ~250 characters, which fixes the error but
might still be too long UX wise
Fixes #1089
> Limit length of slugs to prevent overrunning the UUID column

- docs/install/requirements.md
whee I'm reading https://www.amazon.com/Modern-PHP-Features-Good-Practices/dp/1491905018/ :)
> minor typo: OPcache is the name for the opcode cache

- IdnoPlugins/IndiePub/Pages/MicroPub/Endpoint.php
Support ?q=syndicate-to queries on Convoy and hosted.
I couldn't find a particularly elegant way to do this, so I went with targeted/low-churn instead. IndiePub makes a request directly to the hub for the syndication targets. It gets back the HTML buttons and parses out the values from there. 
I'd also considered adding some deferrals in `Idno\Core\Syndication`, so that it could fetch the list of accounts the first time it's needed. I ended up not pursuing this because it would block rendering of the entire edit widget until you can connect to Convoy.
> IndiePub: fetch syndication targets from Convoy

- Idno/Caching/APCuCache.php
- Idno/Caching/XCache.php
- Idno/Core/Idno.php
First draft of APCu Caching support (references a comment on #753).
I've not had a chance to test this yet, as I don't have APCu Cache enabled on anything and have run out of time. For the moment this is an exercise for the reader...
> Experimental APCu Cache

- Idno/Core/DataConcierge.php
- Idno/Data/MySQL.php
- Idno/Data/Postgres.php
- Idno/Data/Sqlite3.php
> Collection validation

- templates/default/entity/annotations/likes.tpl.php
- templates/default/entity/annotations/mentions.tpl.php
- templates/default/shell/toolbar/logged-in.tpl.php
- templates/default/shell/toolbar/main.tpl.php
Tiny tweak to move the "Delete" link inside the row it belongs to. (And remove a couple stray closing tags)
> template tweak: move 'Delete' inside row div for likes

- Tests/API/BasicAPITest.php
It's probably about time that we introduced some basic API testing to avoid previous regressions.
> Introducing a basic API tester

- docs/plugins/community.md
Footnote-style links reduces duplication for prolific plugin authors :)
> add plugins from me, use footnote-style links

- README.md
based on https://github.com/tinymce/tinymce/blob/master/LICENSE.TXT
> edit: TinyMCE license is LGPL not AGPL

- IdnoPlugins/IndiePub/Pages/MicroPub/Endpoint.php
add some hooks before and after publishing via Micropub.
needed these for https://github.com/kylewm/KnownInstagramShim
> indiepub: trigger events before and after micropub save

- Tests/API/BasicAPITest.php
For some reason, although I pushed it, these changes didn't make it into the patch. Not urgent, just a few minor improvements which made sense...
> Api test redux

- .travis.yml
The IRC messages for every successful build are a little noisy
> Only notify IRC the first time a build is successful

- IdnoPlugins/Event/templates/default/entity/Event/edit.tpl.php
The event editor would load but all the values were blank.
> make events editable again

- templates/default/content/end.tpl.php
- templates/default/shell.tpl.php
> show absolute day times for posts more than a month old

- Idno/Common/ContentType.php
matches changes made to Entity::draw() and Entity::drawEdit() in 400f7117fc8217618ebb1efc556c51cc00c1cd23
> support referencing icon template by full class name

- Idno/Common/Page.php
- Idno/Core/Input.php
Introduces an Input wrapper which allows you to get filtered values from input outside of page variables and before the current page is instantiated.
Closes #235
> Moving input to a static class

- docs/developers/plugins/index.md
mostly just adding a little documentation for @mapkyca's #221, 
and adding a recommended "url" property
fixes #1187 as scoped
> add "url" and [requirements] section to plugin.ini docs

- Idno/Entities/User.php
- Idno/Pages/Account/Settings/Notifications.php
- templates/default/account/settings/notifications.tpl.php
Useful if you already get notified about those replies via another channel (e.g. via the Twitter app)
Ref #882
> add option to suppress notifications from certain domains

- Idno/Core/DataConcierge.php
- docs/install/instructions.md
- add dbauthsrc config property to set the authenticationSource db
- add supporting documentation
fixes #175
> support username and password login for Mongo

- nginx.conf
compare with b0d8e5d13b148f2b3ef239b7a67970ae2a481fda
> add cache busting rewrite rules to nginx example

- IdnoPlugins/Checkin/Checkin.php
> bugfix: Checkin::getDescription should return the post body

- Idno/Core/DataConcierge.php
- Idno/Core/Idno.php
- Idno/Data/Mongo.php
- Idno/Data/MySQL.php
- Idno/Data/Postgres.php
- Idno/Data/Sqlite3.php
Allows multiple instances of a database connection to be created, with their own connection constructors.
Begins the process of migrating mongo code into its own class, and abstracting DataConciege.
Closes #1235 
Closes #1237
> Custom connection params

- IdnoPlugins/IndiePub/Main.php
- IdnoPlugins/IndiePub/Pages/Account.php
- IdnoPlugins/IndiePub/Pages/Revoke.php
- IdnoPlugins/IndiePub/templates/default/account/indiepub.tpl.php
- IdnoPlugins/IndiePub/templates/default/account/menu/items/indiepub.tpl.php
allows account access to be revoked manually.
fixes #1225
> added accounts page for indiepub

- IdnoPlugins/IndiePub/Pages/MicroPub/Endpoint.php
previously was classifying them as 'note'
> better post-type-detection of photos with no name or content

- IdnoPlugins/Checkin/ContentType.php
- IdnoPlugins/IndiePub/Pages/MicroPub/Endpoint.php
works with  @diplix http://ownyourcheckin.wirres.net
resolves #1227
> Micropub Endpoint creates checkin if mp-type == checkin

- Idno/Common/ContentType.php
- Idno/Core/Plugins.php
- Idno/Pages/Entity/Share.php
- templates/default/entity/edit/header.tpl.php
> add some hooks to support extending the /share page from a plugin

- .travis.yml
- Tests/Core/GatekeeperTest.php
> Closes #1254: Fixing mongodb test regression

- IdnoPlugins/IndiePub/Pages/MicroPub/Endpoint.php
if entity is not a checkin an error is logged as specific variables aren't used.
> adding missing field and escaping not used variables

- Idno/Core/Hub.php
- Idno/Core/Idno.php
- Idno/Core/Reader.php
- Idno/Entities/Reader/Feed.php
- Idno/Pages/Account/Settings/Feedback.php
- IdnoPlugins/APITester/Pages/Admin.php
- IdnoPlugins/Webhooks/Main.php
Calling static methods non-statically causes notice error in PHP7
> Make webservice calls statically

- Idno/Files/LocalFileSystem.php
- IdnoPlugins/Photo/Photo.php
Also Photos needs to fail when photo could not be saved.
> Filesystem should not return an id if uploads fail

- Idno/Core/Idno.php
> Collect php version on vendor message ping

- IdnoPlugins/Photo/templates/default/entity/Photo.tpl.php
Places title and description in metadata so that it's easier to extract and bind into photo galleries.
> Make photo data easier to pick out (for lightbox plugins or similar)

- IdnoPlugins/IndiePub/Pages/MicroPub/Endpoint.php
- gets $_FILE['photo'] and adds it to the checking
- multiple words categories changed to #MultipleWords 
- fixes $content override if $content was array.
> MicroPub Endpoint accepts Photo file from checkin

- Idno/Data/AbstractSQL.php
Transfer the fix of $not queries over to countRecords. I didn't realize this same code block was in both places. same fix as cd39685e0209a232ee6a4ed47f6e91c0ac52ad65
I was too hasty in sending the first PR!
> fix $not queries for countRecords too

- .htaccess
- .travis.yml
- docs/install/requirements.md
- htaccess.dist
This small hack reduced loading time of my test known site.
> Small hack to improve speed

- docs/plugins/community.md
A beautiful theme based on google's material design
because @benwerd wanted community theme :) + for fame :P
> add material theme

- docs/plugins/community.md
Added links to a few of my plugins
Fame
> Adding some plugins

- templates/default/entity/content/embed.tpl.php
Changed the default embed url to youtube-nocookie.com
Privacy is good, plus the current embed would explicitly strip privacy from someone who pastes a no-cookie link.
> Use youtube privacy enhanced player by default

- templates/default/entity/content/embed.tpl.php
Expand youtube/user links to play all user uploads as a playlist.
Linked to a youtube/user page, and the link was auto expanded with a broken player.
> Handle youtube/user links

- Idno/Core/Idno.php
- Idno/Pages/Admin/Home.php
- Idno/Pages/Service/Db/Optimise.php
- templates/default/admin/home.tpl.php
Introducing a service page hierarchy, moving optimise to a service call on admin/home
Because shutdown hooks no longer work.
Closes: #1247
> Shift Optimise to a service call.

- Idno/Common/Page.php
- Idno/Core/Idno.php
- Idno/Core/Session.php
- Idno/Core/TokenProvider.php
- Idno/Core/Webservice.php
- Idno/Entities/GenericDataItem.php
- Idno/Exceptions/ConfigurationException.php
- Idno/Exceptions/SecurityException.php
- Idno/Files/LocalFileSystem.php
- Idno/Pages/Account/Settings/Following/Bookmarklet.php
Makes better use of the SPL Exception library; Follows best practice to not use Exception for everything, introduces some specific runtime exceptions to give better granularity.
It's not recommended to just throw \Exception() all the time, as it becomes much harder to gracefully handle specific problems. We should get in the habit of either using existing SPL functions, or extend the appropriate base to add our own.
> Better exceptions

- README.md
* Added precisions on the BSD licenses.
* Added missing licensing info.
It makes things clearer for reuse of Known or its components.
> Completed licensing information for included libs

- IdnoPlugins/IndiePub/Pages/MicroPub/Endpoint.php
Add an RSVP type to the micropub post type detection, pass the 'rsvp' parameter through
The diff looks worse than it is because I re-indented that whole section.
> IndiePub: support receiving RSVPs

- Idno/Common/Entity.php
- Idno/Core/Template.php
Added underscore to tag regex 
To allow for tags like "#Star_trek" in addition to tags like "#Firefly"
> Closes #1383: Adding "_" to tag regex

- IdnoPlugins/IndiePub/Main.php
Moved the setting of API mode
It was causing problems with OAuth2 callbacks
> Closes #1419: Only set api mode when user has actually been authenticated

- templates/default/content/edit.tpl.php
Added a class to the edit content delete
So I could individually select the entry.
> Add extra class to edit link to allow it to be individually selected.

- Idno/Core/Idno.php
- Idno/Data/Mongo.php
Added indexes to mongo
Sorting failed on large data sets
> Adding mongo indexes

- Idno/Core/Idno.php
Added a mechanism to provide per version upgrades.
Needed to apply a one-time only update to something, and there wasn't a mechanism in place.
> Closes #256: Introducing version upgrade mechanism

- templates/default/admin/export.tpl.php
Modified the include hidden control
So hidden items can be included in RSS export
> Closes #1413: Include hidden button now functions in RSS export

- Idno/Common/Page.php
- Idno/Core/Migration.php
- Idno/Data/Mongo.php
- Idno/Pages/Admin/Export/Generate.php
Some extra debug to the export; Isolated and fixed infinite loop when exporting a mongo based database.
Attempt to track down why export is failing (#1437)
Closes #1437
> Fixing export on Mongo

- Idno/Core/Template.php
Modified parseUsers() to activate @users on replies to github
Because.
> Activate @replies to github

- IdnoPlugins/Checkin/checkin.js
* Debug to geo location checkin code
* Error handler now displays error messages
* When location fails, we initialise the map to a default location and allow manual entry
Location failures would give an infinite loop
> Handle geo location failures gracefully

- IdnoPlugins/Convoy/Pages/Connect.php
Added some debug to convoy connect
Try and see what is actually going on with #1457
> Refs #1457: Adding some debug to Convoy connect

- Idno/Data/Mongo.php
- docs/install/instructions.md
Added a few bits of documentation in code + docs to highlight the intention to eventually withdraw MongoDB support (#1277)
Fair warning.
> Note mongo deprecation

- templates/default/content/edit.tpl.php
Per object class edit menu
I needed a simple way to add edit options on specific classes.
> Per object class edit menu

- Idno/Entities/User.php
Added an interface to grant and check for arbitrary user permissions.
I needed to be able to set and revoke specific "permission" metadata on a user, so it made sense to provide a clean interface for it.
> Introducing arbitrary permissions system

- Idno/Entities/User.php
Fixed a couple of typos and comparison errors
To make it work
> Fixing permissions

- Idno/Core/Webservice.php
> Fixing minor, yet dumb, type-o

- IdnoPlugins/IndiePub/Pages/MicroPub/Endpoint.php
> Support single category in micropub endpoint

- IdnoPlugins/IndiePub/templates/default/account/indiepub.tpl.php
Added some explanation text when there are no IndiePub accounts associated with a site.
I was left scratching my head.
> Don't present the user with a blank page.

- IdnoPlugins/IndiePub/Pages/MicroPub/Endpoint.php
> Support multiple syndication URLs in micropub requests

- nginx.conf
https://developers.google.com/speed/pagespeed/insights/?url=http%3A%2F%2Fblog.indie.host%2F
From https://github.com/indiehosters/known/blob/master/nginx.conf
> Performant nginx configuration

- IdnoPlugins/IndiePub/Pages/MicroPub/Endpoint.php
Conform to the spec by sending out JSON error responses:
- When the access token is invalid
- When some error occurs, e.g. a post could not be saved
The micropub endpoint now also sends out a HTTP 500 status code
by default unless that's overriden later.
This helps when something crashes during processing.
Resolves: #1506
> Send proper micropub error responses

- IdnoPlugins/IndiePub/Pages/MicroPub/Endpoint.php
> Add "delete" action to micropub endpoint

- IdnoPlugins/IndiePub/Pages/IndieAuth/Auth.php
> Send "IndieAuth: authorization_endpoint" header

- IdnoPlugins/IndiePub/Pages/IndieAuth/Auth.php
This is not needed anymore since the bug in IndieAuth.com is fixed
that required this message.
See https://github.com/aaronpk/IndieAuth.com/issues/93
Follow up for #1537
> Remove "This is an IndieAuth server" message.

- IdnoPlugins/IndiePub/Pages/MicroPub/Endpoint.php
- IdnoPlugins/Like/Like.php
> Add support for bookmarks in micropub

- Idno/Common/Entity.php
- Idno/Core/Session.php
- Idno/Data/Mongo.php
- Idno/Data/MySQL.php
- Idno/Entities/AccessGroup.php
- Tests/Data/AccessGroupTest.php
- Tests/Data/DataConciergeTest.php
- Tests/KnownTestCase.php
Some tests for ACLs, some fixes for logged out users
ACLs weren't being tested, now they are.
Closes #1543
> Admin acl tests

- IdnoPlugins/IndiePub/Pages/MicroPub/Endpoint.php
Requires a video plugin to be installed, e.g.
https://github.com/cweiske/withknownVideo
Related: #1374
> Add video upload support to the micropub endpoint

- Tests/build/config_default.ini
- Tests/build/config_mysql.ini
- Tests/build/config_pgsql.ini
- Tests/build/config_sqlite3.ini
Specify and activate some default plugins
Allow the tests to pass
> Fix build errors introduced by a672895d388a1fcecc8f30565d57044e1a9b9e43.

- templates/default/entity/feed.tpl.php
- templates/default/shell/dublincore.tpl.php
Fixed various notice errors.
Various notice errors were found, which broke stuff in pedantic mode
> Fixing notice errors

- Idno/Common/Entity.php
- IdnoPlugins/Text/Entry.php
* Introduced the concept of post status
* Modified Entity::publish() to only syndicate if publish_status == 'published'
We need the concept of 'draft'. 
Refs #888
> Post status

- Idno/Common/Entity.php
Added a inACL() helper function
Needed a method to determine whether you had access to something because you had access to something or because you were an admin.
> Introducing inACL() helper function

- templates/rss/shell.tpl.php
* Handle cases when an object was created by a deleted user (rare, but happened on my test build owing to broken phpunit tests)
* Encode entity title to allow for & and similar characters.
RSS was broken and spat out errors
> Unterminated shell

- Idno/Common/SessionStorageInterface.php
- Idno/Core/Config.php
- Idno/Core/DataConcierge.php
- Idno/Core/Session.php
- Idno/Data/AbstractSQL.php
- Idno/Data/Mongo.php
* Added a SessionStorageInterface that provides handleSession()
* Specify that DBs implement this handler
* Add a way to specify new handler
Session handlers should probably be plugable.
> Pluggable sessions

- Idno/Common/Page.php
- Idno/Pages/Admin/Diagnostics.php
- templates/default/account/menu.tpl.php
- templates/default/admin/menu.tpl.php
- Introduced doesPathMatch() helper function
- Modified admin and account menus to use it
Current menu highlighting did not work in subdirectory installs.
> Subdirectory menus

- IdnoPlugins/Checkin/Pages/Callback.php
- IdnoPlugins/Checkin/checkin.js
- Fix initMap so that it sets hidden values on init.
- Update map when the address field is changed, allowing manual address input and lookup
Location API is restricted to TLS origins, and we currently have no fallback for those running HTTP
> Manual address entry

- Idno/Common/Entity.php
Added some debug to the object search 
to try and get to the bottom of #1595
> Adding some debug (refs #1595)

- Idno/Common/Entity.php
Removed yesterday's debug
No longer required
> Removing temporary debug that was introduced yesterday (refs #1595)

- docs/developers/plugins/api.md
Added some better documentation re the API
Clarification, slightly related to #225
> Updating documentation to add better docs about API

- docs/install/debugging.md
- docs/install/index.md
- mkdocs.yml
Adding some documentation for logging and diagnostics
Again, quick to do, probably useful
> Closes #1480: Adding some documentation about logs and diagnostics

- docs/plugins/community.md
Added a link to a new plugin that syndicates plugins to pinboard.in
> added Pinboard plugin

- Idno/Common/Entity.php
Add a few set* on Entry
I tried to access them, and while there's a setTitle() there isn't an equivalent for other common fields which also have a get*
> Add a few missing setters, to avoid confusion

- Idno/Entities/User.php
Pass the user to the acl event trigger
To simplify event handling
> Pass the current user to the event

- known.php
Added support for regular Known plugins to provide console plugins
I wanted to provide console only functionality to an existing plugin, without requiring the creation of a separate console plugin
> More console tweaks

- Idno/Common/Entity.php
- Idno/Common/Page.php
- Idno/Core/Migration.php
- Idno/Pages/Admin/Import.php
* Better logging
* Fixing success email send
* Import functions actually report success.
Some folk were reporting Wordpress import wasn't working, and although in my tests the wordpress import did import all the items from my blog, it never reported that this was done successfully.
> Wordpress import fixes

- Idno/Pages/Admin/Diagnostics.php
Security: Redacting site_secret
Formatting: A little bit of spacing
Information: Returning machine version as well as human version
It was bugging me
> Diagnostics tweaks

- templates/rss/shell.tpl.php
Adding WP namespace
Because, oops.
> Adding WP namespace

- templates/rss/shell.tpl.php
Temporarily reverting RSS fix
Until I have time it properly
> Temporarily commenting out import fixes

- templates/default/content/embed.tpl.php
Added parameters to iframe embed to enable fullscreen
It wasn't enabled.
> Enable full screen support on youtube video embed

- docs/plugins/community.md
added link to plugin
Like he said... Trump!
> mapkyca's Archive.org/Wayback Machine plugin

- IdnoPlugins/Photo/Photo.php
- IdnoPlugins/Photo/templates/default/entity/Photo/edit.tpl.php
* Added a preview to the photo edit form for existing photos
* Tweaked the upload to allow replacement of existing photos and handling of text only edits
It wasn't possible to replace an existing image with a new one, you had to delete and recreate the post.
> Photo tweaks

- Idno/Data/Mongo.php
Restored previous mongo key wrapping keys
Mongo was broken for some people
> Bringing back previous wrapping functions

- Idno/Core/Template.php
Url port was missing at 4 functions.
> Fix url port missing

- Idno/Data/Mongo.php
- IdnoPlugins/Webhooks/Main.php
- IdnoPlugins/Webhooks/templates/default/webhooks/admin/home.tpl.php
Avoid some notice errors
There seemed to be some strangeness on my local install related to webhooks and mongo, this avoids it breaking...
> Fix some more notice errors

- docs/plugins/community.md
I added a plugin that I made for tracking your eating and drinking activities.
Because I love eating and drinking!
> Adding Food and Drink logging plugin

- docs/plugins/community.md
Adding a customization plugin.
Thought it might be useful to someone!
> Adding a simple customization plugin

- docs/developers/plugins/index.md
- templates/default/admin/dependencies/build.tpl.php
- templates/default/admin/dependencies/idno.tpl.php
- templates/default/admin/dependencies/php.tpl.php
- templates/default/admin/plugins/plugin.tpl.php
* Added build version requirement option
* Fixed notice error
* Improved requirement messages
* Error broke things
* A build requirement allows better requirement specifications
* Errors weren't very helpful
> Known plugin manifests

- templates/default/entity/User/profile/fields.tpl.php
extended the FA icon set a little for a few common sites.
Added resolving the Font Awesome icons for reddit, instagram and paypal.
It's a small fix but I believe it improves the ecstatic of the profile page.
> Few more FA icons

- templates/default/onboarding/begin.tpl.php
I guess somebody forgot to update all relative paths to images to make it work outside of root of site...
> Fix paths of images during onboarding when installed not at root of site

- Tests/build/config_default.ini
- Tests/build/config_mysql.ini
- Tests/build/config_pgsql.ini
- Tests/build/config_sqlite3.ini
Modified travis config files to execute tests with ```pedantic_mode``` on
Encourage fewer notice errors
> Pedantic tests

- Idno/Pages/Entity/Share.php
Test for content-type array entry
Was generating a notice error
> Avoid notice error

- templates/rss/shell.tpl.php
Addressed a number of validation issues as reported by the W3C RSS validator
Better support feeds
> Rss validation

- mkdocs.yml
Added admonition support to mkdocs. 
To support
```
!!! note 'Notes'
note support
```
etc
> Support admonition

- Idno/Core/Session.php
Fixing a notice error/wrong placement of trigger
Oopsy
> Fixing error

- Idno/Entities/File.php
- Idno/Files/MongoDBFileSystem.php
- Idno/Pages/File/Picker.php
Fixes some image orientation issues in File and wysiwyg embed
Selfies were appearing in the wrong orientation, large images were being stretched if rotated.
> Image orientation

- templates/default/content/embed.tpl.php
Added instagram support to the embed template
was missing, and other things had been added.
> Adding instagram support

- docs/developers/plugins/index.md
- templates/default/admin/dependencies/plugin.tpl.php
- templates/default/admin/plugins/plugin.tpl.php
Removed notice warnings, fixed errors in plugin requirements handling
It was broke and confusing
> Plugin requirements

- schemas/postgres/2017032001.sql
Removed syntax error
It was a syntax error
> Closes #1752: Changing syntax as noted

- templates/jsonfeed/shell.tpl.php
Adding support for the new JSON Feed format. - https://jsonfeed.org
Starting to gain some traction.
> Adding JSON Feed support.

- Idno/Core/Logging.php
- IdnoPlugins/Event/plugin.ini
- docs/install/debugging.md
- docs/install/upgrade.md
- templates/email/shell.tpl.php
Roll up of various little fixes I noticed/were pointed out.
* Clarification of RSVP
* Email template tweaks
* Tidying up logging
* Some documentation tweaks
Bugging me, didn't want to do a whole bunch of PRs for them
> Little fixes

- Idno/Common/Page.php
- Idno/Core/Idno.php
- Idno/Pages/Service/Security/CSRFToken.php
- js/default.js
Modified previous HEAD method of token update to an explicit ajax endpoint
Based on a conversation with @benwerd, this seemed to be more consistent.
> Token update endpoint

- IdnoPlugins/Photo/Photo.php
- docs/developers/plugins/api.md
* Improved the API docs to make them clearer, and to include working examples
* Removed a notice error
* The API docs were old and confusing
> Updating the API docs

- Idno/Core/Session.php
Added some debug around API calls and signature validation
To help API developers debug where calls are failing.
> Adding some more useful debug for API queries

- Idno/Stats/Counter.php
- Idno/Stats/Timer.php
Basic interfaces for setting timers and counters
To debug various things I needed to track a couple of things and ended up retyping the same code, this makes its usage easier.
> Basic stats interface

- Idno/Core/Template.php
Added a sampleTextChars method to return max chars
Needed a way to truncate text nicely to a maximum number of chars.
> Method to return text up to max chars

- IdnoPlugins/Checkin/external/stamen-maps/README.md
- IdnoPlugins/Checkin/external/stamen-maps/tile.stamen.js
Flagged this code as modified
Dotting Is and Crossing Ts
> Making a copyright note that this is a modified version

- Idno/Common/Entity.php
- IdnoPlugins/Checkin/Checkin.php
- IdnoPlugins/Event/RSVP.php
- IdnoPlugins/Like/Like.php
- IdnoPlugins/Photo/Photo.php
- IdnoPlugins/Status/Reply.php
- IdnoPlugins/Status/Status.php
- IdnoPlugins/Text/Entry.php
- templates/jsonfeed/shell.tpl.php
Decentralizing the metadata generation for JSON Feed and delegating it to plugins, where possible. Also, updating a few pieces of terminology/properties to more closely match other Indieweb work like JF2.
Largely in response to ongoing discussions here:
https://github.com/brentsimmons/JSONFeed/issues/51
> JSON Feed evolution

- IdnoPlugins/IndiePub/Pages/MicroPub/Endpoint.php
Micropub Media Endpoint support.
Many Micropub clients require it.
> Initial implementation of Micropub Media Endpoints.

- ConsolePlugins/Statistics/Main.php
- Idno/Core/Admin.php
- Idno/Core/Statistics.php
- Idno/Pages/Admin/Statistics.php
- templates/default/admin/menu.tpl.php
- templates/default/admin/statistics.tpl.php
- templates/default/admin/statistics/report.tpl.php
Added a framework for admin statistics, pluggable by plugins and events
Needed a more standard way for sites and plugins to add and gather statistics
> Admin statistics framework and basic statistics

- Idno/Core/Statistics.php
- Idno/Pages/Admin/Statistics.php
- templates/default/admin/statistics.tpl.php
Added, the ability to specify specifically desired report
May not be desirable to run every report for everything
> Statistics tweaks

- Idno/Pages/Account/Notifications.php
- templates/default/account/notifications.tpl.php
Passing appropriate items per page
Pagination was broke
> Fixing pagination

- templates/default/forms/token.tpl.php
Changed marker div to span
Div was apparently causing some layout issues
> Using span instead of div

- Idno/Stats/Timer.php
- Idno/Stats/TotalTimer.php
Added TotalTimer
This variation of Timer is handy to time the time spent in each section of a loop, and output the result at the end.
> Introducing a functional total timer

- Idno/Core/DataConcierge.php
Added a function which, when passed a variable, will always return an array
I ended up typing it a lot, and I don't like typing.
> Introducing a simple array normalising function

- Idno/Common/Page.php
- Idno/Pages/Entity/View.php
- Idno/Pages/File/View.php
* Resolving aggressive browser caching error
* Restoring 304 support on permalinks and files
Efficiency.
> Fixing lm gatekeeper

- CONTRIBUTING.md
* Changed section order
* Highlighting the code of conduct
To better fit the format spotlighted by GitHub
> Slight tweak to the order of CONTRIBUTING.md

- Idno/Core/Idno.php
- Idno/Core/SynchronousQueue.php
* Added a validating component constructor factory to the Idno class.
* Moved database construction to support this
* Added compatibility "mongo" support
* Fixed a typo in event queue class
To allow for customisable system components without a whole lot of typing
> Component constructor

- ConsolePlugins/EventQueueService/Main.php
- Idno/Core/AsynchronousQueue.php
- Idno/Core/Idno.php
- Idno/Core/SynchronousQueue.php
- Idno/Entities/AsynchronousQueuedEvent.php
- known.php
Added support for asynchronous queues
To do some messaging in the background
> Asynchronous queue support

- ConsolePlugins/EventQueueService/Main.php
- IdnoPlugins/IndiePub/Pages/MicroPub/Endpoint.php
> More minor tweaks

- Idno/Core/Session.php
Actually set the user on email
Last PR wasn't complete
> Actually set the user!

- Idno/Common/Page.php
Changed test in isAcceptedContentType
To preserve expected behaviour after changes in #1838
> Preserve behaviour after changes in #1838

- Idno/Pages/Annotation/View.php
- templates/default/entity/annotations/like.tpl.php
- templates/rss/shell.tpl.php
Feeds (json and rss) on annotations
Needed in order to automate some stuff, thought it might be useful for folk. (seem to remember it was requested a while ago)
> Comment list

- Idno/Pages/Service/System/Log.php
- js/default.js
Removed some unnecessary debug, changed error message
Needed some tidying
> Minor fixes

- Tests/Data/AccessGroupTest.php
> Asserting acl bypass test

- IdnoPlugins/Event/templates/default/entity/RSVP/edit.tpl.php
- templates/default/forms/input/select.tpl.php
Added the ability to have multiple items on a select control
'twas needed
> Support multiple entry on select

- Idno/Core/Idno.php
- Tests/build/config_default.ini
- Tests/build/config_mysql.ini
- Tests/build/config_pgsql.ini
- Tests/build/config_sqlite3.ini
Looks like SQLLite needs a little bit of love
Noticed that the travis tests were always failing
Closes #1876
> Give SQLLite a little bit of love

- Idno/Common/Entity.php
Added a utility wrapper function for getByxxx that will try multiple different methods for a given identifier.
I kept on having to test retrieval for a ID and UUID
> Adding utility wrapper function

- templates/default/shell/css.tpl.php
- templates/default/shell/footerjavascript.tpl.php
- templates/default/shell/javascript.tpl.php
* Reverts cache busting
* Gingerly restore fragmentions
* Attempt to poke Travis builds into working again
Various
> Revert cache busting etc 

- templates/default/content/notification/wrapper.tpl.php
* Parsing urls in notifications, and parse tags etc
* Parse out htmlentities
Prettyness + xss protection
> Parse urls and tags, and add htmlentities()

- Idno/Common/Entity.php
- Idno/Core/Idno.php
- Idno/Core/Logging.php
- Idno/Core/Template.php
- Idno/Core/Webmention.php
- Idno/Entities/File.php
- Idno/Entities/UnfurledUrl.php
- Idno/Pages/Service/Web/ImageProxy.php
- Idno/Pages/Service/Web/UrlUnfurl.php
- templates/default/account/settings/following/mf2user.tpl.php
- templates/email-text/admin/oops.tpl.php
- templates/email/admin/oops.tpl.php
* Misc tweaks from #1886
* Extended image proxy to allow for scaling and transformations (making image square)
* Pave the way for replacing the current handling of webmention urls
Refs #432
> Imageproxy transform

- Idno/Core/Idno.php
- Idno/Core/Logging.php
- Idno/Entities/UnfurledUrl.php
- Idno/Pages/Service/Web/ImageProxy.php
- Idno/Pages/Service/Web/UrlUnfurl.php
- templates/email-text/admin/oops.tpl.php
- templates/email/admin/oops.tpl.php
* Debug info added to Ooops email
* Unfurl now extracts MF2
Tweaks
> Debug and tweaks

- Idno/Core/Language.php
Allow for per user language selection
Because we're going to need it eventually, right? 
Refs #339
> Allow for user language preferences

- templates/default/entity/edit/footer.tpl.php
- templates/default/entity/edit/spinner.tpl.php
Made the spinner a reusable control
Make it easier to use elsewhere.
> Make spinner a reusable control

- Idno/Common/Plugin.php
Added a method to extract plugin manifest information
Wanted to have a mechanism to extract versions.
> Adding mechanism to extract plugin version

- Idno/Core/Template.php
- templates/default/shell/css.tpl.php
- templates/default/shell/javascript.tpl.php
* Adding a mechanism to get the modified time of a given file.
* Wrapping this around files for cache busting.
To bust them caches wide open.
> Cache busting attempt 2

- Idno/Pages/Account/Settings.php
Adding missing stuff from timezones merge
Missed it
> Allow for setting of "no timezone"

- templates/default/forms/usersearch.tpl.php
Prevent enter from submitting form
onChange worked, but submit caused weirdness.
> Prevent enter from submitting the form

- templates/default/forms/usersearch.tpl.php
Added a submit button to user search form
To maintain common ux
> Adding a submit button

- templates/default/forms/usersearch.tpl.php
fixed typo in user pagination javascript
To activate pagination
> Fixing user search pagination

- templates/default/shell/footerjavascript.tpl.php
Adding cache busting on shell and embed
Missing
> Adding missing cachebusting

- Idno/Core/Arrays.php
- known.php
- templates/default/entity/annotations/comment/main.tpl.php
* ctrl+enter submit on comments
* improved console commands in regular plugins - now supports multiple plugins in a /Console/ directory
Make my life easier
> Misc tweaks

- IdnoPlugins/Media/Media.php
- IdnoPlugins/Media/templates/default/entity/Media/edit.tpl.php
Ability to replace media on existing content
Make edit work as expected and bring it in line with changes already made to the photos plugin
> Allow audio file replacement

- Idno/Common/Entity.php
- Idno/Common/EntityInterface.php
- Idno/Common/RSSSerialisable.php
- Idno/Core/DataConcierge.php
- Idno/Core/Migration.php
- Idno/Core/Template.php
- Idno/Data/Mongo.php
- Idno/Data/MySQL.php
- Idno/Data/Postgres.php
- Idno/Data/Sqlite3.php
- Idno/Pages/Account/Export/RSS.php
- Idno/Pages/Admin/Export/RSS.php
- templates/rss/shell.tpl.php
A raft of changes around export and export RSS in order to make it more reliable and, notably, to handle very large data sets.
I fixed a number of minor bugs, and as a bonus, it is now possible for individual objects to specify exactly how they are rendered in RSS, making RSS feeds *much* more flexible. 
Before I could even consider looking at bulletproof import I needed to be able to export some real data. Half the time this was impossible as Known ran out of memory before the export could be completed.
> Export tweaks

- Idno/Core/Migration.php
Adding RSS output formatting
Better output some export
> Better format the output

- .travis.yml
Changes to travis build
Seems travis have changed their builds a bit...
> Fixing some travis errors

- templates/default/file/picker/image.tpl.php
Adding a class to the file picker so we can control it better
So we can better skin the controls
> Some filepicker tweaks

- IdnoPlugins/Like/templates/default/entity/Like/edit.tpl.php
- templates/default/entity/edit/spinner.tpl.php
A patch roundup of various tweaks
A bit of a roundup of various bits.
> Some minor fixes

- Idno/Core/Admin.php
- Idno/Core/Idno.php
- Idno/Entities/User.php
Tidying up a few things which are not used and/or in a silly place
It's good to remove kruft from time to time
> Deletion candidates

- Idno/Core/SynchronousQueue.php
- Idno/Pages/File/View.php
- IdnoPlugins/Media/Media.php
- IdnoPlugins/Media/templates/default/entity/Media.tpl.php
- IdnoPlugins/Media/templates/default/media/shell/footer.tpl.php
* Removed mediaelement from video playback
* Added an enqueue event for video transcoding
* Mediaelement didn't handle scaling very well, so leaving this to the browser
* Add a future enhancement to offline transcode videos 
Note, this shouldn't be taken as a directional thing, I am itch scratching here :D
> Minor (unsupported)video fixes

- docs/install/advanced.md
Explained some service stuff
You need to run as the web user
> Make a note about the service user

- docs/install/advanced.md
Added some extra instructions for service and cron init
Make it easier for folk
> Better advanced config doc

- Idno/Data/Mongo.php
- Idno/Pages/Admin/Diagnostics.php
Add a diagnostic test to see if the Mongo BSON db bug (https://github.com/mongodb/mongo-php-driver/pull/340)  is present in your mongodb driver
Hopefully to try and get asynchronous queues working in mongo
> Mongo bson bug

- Idno/Core/AsynchronousQueue.php
> Removing limitation

- IdnoPlugins/Text/templates/default/entity/Entry/edit.tpl.php
> Ensure autoSave is called after javascript is loaded.

- ConsolePlugins/EventQueueService/Main.php
Reinitialise mongo database connection for child fork
It was causing issues on the queue service
> Mongo process control

- Idno/Caching/MemoryCache.php
Fixing a typo on namespace
So it worked.
> Fixing namespace

- IdnoPlugins/IndiePub/Pages/MicroPub/Endpoint.php
Fixing by-reference error
Passing function output as reference caused notice error
> Fixing pass by reference error

- docs/install/advanced.md
Added a note about upgrades WRT the queue service.
This issue bit me in the bum when updating the twitter plugin for 280 char tweets, wanted to save other folk problems!
> Making a note on upgrades

- Idno/Caching/ArrayCache.php
- Idno/Caching/Cache.php
- Idno/Caching/MemoryCache.php
- Idno/Caching/StaticArrayCache.php
- Idno/Core/Idno.php
* Added static memory array cache
* Renamed some classes for clarity
Needed it
> Shared memory caches

- templates/default/admin/about.tpl.php
- templates/default/admin/dependencies/build.tpl.php
- templates/default/admin/dependencies/idno.tpl.php
Migrated deprecated functions
Removing notice errors
> Avoiding some notice errors for deprecated functions

- Idno/Core/Template.php
- external/MrClay_AutoP/AutoP.php
Fixing some issues with autop and username/link activation
@ links on notifications were displaying screwy, probably caused issues elsewhere too.
> Spacing tweak

- .htaccess
- htaccess-2.4.dist
- htaccess.dist
Added composer.lock to the blocked list
Some deploys seem to use composer for some stuff, block the lock file from showing.
> Somehow some deploys have a composer lock file

- Idno/Common/Page.php
- Idno/Core/TokenProvider.php
Added some logging
To help diagnose token errors
> Token debug

- Idno/Entities/UnfurledUrl.php
- Idno/Pages/Service/Web/UrlUnfurl.php
- README.md
- external/php-ogp/.gitignore
- external/php-ogp/README.md
- external/php-ogp/example.php
- external/php-ogp/ogp/Parser.php
Backported my unfurl work into my library that it was based on, using this library
I hate repeating myself :)
> Use PHP-OGP

- Idno/Pages/Annotation/Post.php
Only using json template for xhr
Comment splurged back json
> Closes #1968: Only use json template for xhr

- ConsolePlugins/EventQueueService/Main.php
A try catch and additional loop
I was getting periodic database connection issues with long time persistent connections, hopefully this will make the script more resilient.
> Attempt catch and recovery of some database errors

- .travis.yml
Added 7.1 and 7.2 builds to travis
Progress
> PHP 7.1 and 7.2 travis builds

- IdnoPlugins/Checkin/templates/default/entity/Checkin.tpl.php
Updated the microformats for Checkin posts to match the draft spec:
https://indieweb.org/checkin#Publish
As a result of a conversation with @aaronpk on our Together reader project:
https://github.com/cleverdevil/together/issues/19
> Update the microformats for Checkin posts to match the draft spec.

- templates/default/admin/diagnostics.tpl.php
Made the diagnostics printout fixed height
Minor styling to make it easier to select
> Minor styling tweak

- ConsolePlugins/EventQueueService/Main.php
- Idno/Core/Bonita/Forms.php
* Some speculative fixes for async queues
* Some logging in tokens to try and catch "invalid token" message
Trying to get to the bottom of things
> A few tweaks

- Idno/Core/Bonita/Forms.php
> Display token in log, human readable

- Idno/Core/Session.php
- Idno/Pages/Service/Notifications/NewNotifications.php
- Idno/Pages/Service/Security/CSRFToken.php
- Idno/Pages/Service/Vendor/Messages.php
* Removing changes from ce203f7
* Explicitly setting no-cache headers on certain important endpoints 
* Some caching was happening
> Set no cache headers

- docs/developers/commit-messages.md
- docs/developers/standards.md
- mkdocs.yml
* Updated the code style guide
* Added a guide for commit messages
Bringing a little order to the chaos.
> Adding some code standards and commit message guidelines

- Idno/Core/Language.php
Ability to request the full locale from a language string, and add sanitisation
Security, and for future enhancements.
> Language detection enhancement

- .travis.yml
Tidy up travis logic
Attempting to get php 7.2 branch to pass
> Stop installing PHP5 stuff on PHP 7

- Idno/Common/Page.php
- Idno/Core/Idno.php
- Idno/Entities/User.php
Removed a number of long-time deprecated object methods
To tidy the interface, and because it was about time...
> Remove deprecated methods

- Idno/Pages/Account/Register.php
- Idno/Pages/Session/Login.php
Remove reference to removed methods
Was breaking login and register
Closes #2019
> Remove reference to deprecated (now removed) functions

- Idno/Core/Time.php
- Idno/Entities/User.php
- IdnoPlugins/Event/Event.php
- IdnoPlugins/Event/templates/default/entity/Event.tpl.php
- IdnoPlugins/Event/templates/default/entity/Event/edit.tpl.php
- templates/default/forms/output/timezones.tpl.php
* Added a timezone to events
* Added tools for displaying and comparing timezones
Long standing issue, needed for i18n
> Event timezone support

- Idno/Common/Entity.php
- IdnoPlugins/IndiePub/Pages/MicroPub/Endpoint.php
- IdnoPlugins/Status/templates/default/entity/Status.tpl.php
Handle tags better
Return correct content type
Low hanging fruit after playing with omnibear
> Micropub tweaks

- Idno/Common/Entity.php
- Idno/Common/Page.php
- Idno/Core/Email.php
- Idno/Core/Session.php
- Idno/Core/Webservice.php
- Idno/Files/LocalFileSystem.php
- Idno/Pages/Account/Password.php
- Idno/Pages/Account/Password/Reset.php
- Idno/Pages/Account/Register.php
- Idno/Pages/Account/Settings.php
- Idno/Pages/Account/Settings/Feedback.php
- Idno/Pages/Account/Settings/Following/Bookmarklet.php
- Idno/Pages/Account/Settings/Notifications.php
- Idno/Pages/Admin/EmailTest.php
- Idno/Pages/Admin/Homepage.php
- Idno/Pages/Admin/Import.php
- Idno/Pages/Admin/Plugins.php
- Idno/Pages/Admin/Themes.php
- Idno/Pages/Admin/Users.php
- Idno/Pages/Annotation/Delete.php
- Idno/Pages/Entity/Delete.php
- Idno/Pages/Entity/View.php
- Idno/Pages/Entity/Withdraw.php
- Idno/Pages/File/Picker.php
- Idno/Pages/Following/Add.php
- Idno/Pages/Following/Confirm.php
- Idno/Pages/Session/Login.php
- Idno/Pages/Session/Logout.php
- Idno/Pages/User/View.php
i18n hooks around addMessage and addErrorMessage calls
So they can be translated at a later date.
> i18n hooks around addMessage and addErrorMessage calls

- IdnoPlugins/IndiePub/Pages/MicroPub/Endpoint.php
> Respect published property in Micropub JSON requests.

- IdnoPlugins/Comments/Pages/Post.php
Removed call to deprecated function
Refs #2019
> Removing reference to deprecated function.

- known.php
Display a friendly console message
Just to make it a little obvious
> Display some friendly version info for Known Console

- Idno/Common/Page.php
- Idno/Core/Bonita/Forms.php
Very slight tweak to logging
Just to make future tweaks easier.
> Tokens: make the logging a little easier to read.

- .travis.yml
- Tests/EnvironmentTest.php
Changing path of configuration to the new location
Consistency
> Tweaking path

- Idno/Core/Installer.php
- warmup/CLI/.htaccess
- warmup/CLI/CLIInstaller.php
- warmup/WebInstaller.php
Adding CLI installer
Providing a cli and scriptable site installer
> Introducing CLI installer

- ConsolePlugins/EventQueueService/Main.php
- ConsolePlugins/PeriodicExecutionService/Main.php
See if we can catch mongo errors at a higher level
Trying to keep things running a little longer
> Attempt a higher level catch

- Idno/Pages/Service/Security/CSRFToken.php
Removing some token debug
Tidiness
> Removing token debugging.

- Idno/Core/Installer.php
- warmup/CLI/CLIInstaller.php
* Ability to specify alternative configs to write settings to
Make the installer a little bit more flexible and able to configure additional sites.
> Output to a separate config.ini

- Idno/Entities/User.php
Adding a restricted processing flag to users
This allows a user to be flagged for "Restricted Processing", where by it will no longer be visible to back office staff. 
Currently this isn't checked for, but is there for future enhancement.
https://techblog.bozho.net/gdpr-practical-guide-developers/
> Add a simple flag for "Restricted Processing" as defined by GDPR

- Idno/Core/Template.php
Open links in a new window
Don't want to clobber the current window on click
> Open remote links in a new window/tab

- Tests/Core/TemplateTest.php
Fixed a syntax error
I broked it.
> Fixing syntax error introduced in last edit

- IdnoPlugins/IndiePub/Pages/MicroPub/Endpoint.php
Added support for creating private posts via Micropub based upon the "visibility" extension documented here:
https://indieweb.org/Micropub-extensions#Visibility
I'm migrating away from "Day One" as a result of their recent security snafu.
> Supporting the "visibility" extension for Micropub:

- IdnoPlugins/IndiePub/Pages/MicroPub/Endpoint.php
Moved the file upload logic in the micropub
At some point in the past this was seemingly broken, or was always broken but nobody noticed. But hey.
> Micropub: Fixing image upload logic

- Idno/Entities/User.php
Removed unnecessary declaration
Just to tidy things up a bit
> Implementing JsonSerializable here, it's part of the EntityInterface

- IdnoPlugins/Like/templates/default/entity/Like.tpl.php
Changed the icon for "Like" from a missing icon to an appropriate new icon from font-awesome, and added an icon for "Bookmark" content to make things more consistent.
@mapkyca did an awesome thing and upgraded font-awesome. This is one of the only side-effects in core.
> Update icons post font-awesome upgrade.

- templates/default/entity/User/profile/fields.tpl.php
Adding Patreon icon to profile
To use the correct icon when listing it.
> Adding Patreon icon

- Themes/Black/templates/default/content/end.tpl.php
- Themes/Cherwell/templates/default/content/end.tpl.php
- Themes/Fauvists/templates/default/content/end.tpl.php
- js/templates/default/shell.js
See: #2099 
Note: I don't know how to regenerate the minimized JavaScript, so someone else will need to handle that. @mapkyca maybe?
> Addresses the renaming of the star and closed star icons in fontawesome.

- templates/jsonp/shell.tpl.php
* Removing caching header
* Making jsonp consistent with json
Just tweaking things.
> Jsonp tweaks

- IdnoPlugins/Photo/Photo.php
Pick up exceptions on missing photos
To prevent crashes
> More JSON tweak

- Idno/Core/Installer.php
- warmup/webserver-configs/config.ini.template
Date + time to installer
Missing from last commit
> Installer: Adding config build time to installer config.ini builder

- IdnoPlugins/IndiePub/Pages/IndieAuth/Auth.php
Return a more granulated error message
Hopefully debug some issues people have been having.
Refs #2110
> Display return error if it's available.

- warmup/CLI/CLIInstaller.php
Adding a check-requirements method to installer
Because I wanted the option
> Adding check-requirements method to CLI installer.

- languages/source/known.pot
Updating the core gettext corpus .pot file
To take in to account the new strings
> Refs #2114: Updating gettext corpus

- Idno/Data/MySQL.php
- Idno/Data/Postgres.php
- Idno/Data/Sqlite3.php
Correcting the schema location for various things
Wasn't correct
> Correcting location

- IdnoPlugins/Comments/templates/default/comments/public/form.tpl.php
- templates/default/content/unfurl.tpl.php
- templates/default/entity/annotations/replies.tpl.php
Added some sanitisation, and typos
Public comments could break the page, and the current build had broken unfurl
> Tidying up some bits

- Idno/Core/Idno.php
Sweeping up some sawdust
Needed sweeping
> Removing reference to the now removed URL Proxy

- Gruntfile.js
- languages/source/known.pot
Added a grunt task to build the known core language file
To make it easier to build the core language .pot file
> Grunt build-lang process

- Idno/Pages/Account/Export.php
- Idno/Pages/Account/Notifications.php
- Idno/Pages/Admin/Export.php
- Idno/Pages/Admin/Homepage.php
- Idno/Pages/Admin/Import.php
- Idno/Pages/Following/Home.php
- Idno/Pages/Onboarding/Begin.php
- Idno/Pages/Onboarding/Connect.php
- Idno/Pages/Onboarding/Profile.php
- Idno/Pages/Session/CurrentUser.php
- Idno/Pages/User/Edit.php
- Idno/Pages/User/View.php
- Idno/Pages/Webmentions/Endpoint.php
- languages/source/known.pot
Adding some missing translation strings
Needed for more complete translations going forward
> Adding some language strings

- Idno/Pages/Session/CurrentUser.php
- Idno/Pages/User/Edit.php
- Idno/Pages/User/View.php
Fixing some syntax errors
Second parameter should be passed as an array.
Closes #2136
> Fixing language syntax

- docs/developers/testing.md
- mkdocs.yml
Documentation for running php unit tests
Closes #2148
> Adding documentation regarding PHP Unit tests

- IdnoPlugins/APITester/languages/apitester.pot
- IdnoPlugins/Bridgy/languages/bridgy.pot
- IdnoPlugins/Checkin/languages/checkin.pot
- IdnoPlugins/Comic/languages/comic.pot
- IdnoPlugins/Comments/languages/comments.pot
- IdnoPlugins/Event/languages/event.pot
- IdnoPlugins/FooterJS/languages/footerjs.pot
- IdnoPlugins/IndiePub/languages/indiepub.pot
- IdnoPlugins/Like/languages/like.pot
- IdnoPlugins/Media/languages/media.pot
- IdnoPlugins/Photo/languages/photo.pot
- IdnoPlugins/StaticPages/languages/staticpages.pot
- IdnoPlugins/Status/languages/status.pot
- IdnoPlugins/Styles/languages/styles.pot
- IdnoPlugins/Text/languages/text.pot
- IdnoPlugins/Webhooks/languages/webhooks.pot
- languages/source/known.pot
Updating core strings
To include new strings and update string line numbers fixed by #2162
> I18n update

- templates/default/content/unfurl.tpl.php
Added descriptive titles to url preview delete and refresh button
Refs #2171
> Adding hover descriptive title

- docs/install/sharedhost.md
Removed a space
I hate spaces!
> Broken markdown

- Idno/Core/Service.php
- Idno/Pages/Service/Queues/Queue.php
* Normalised urls for token generation
* Handled mongo IDs
Make queue service work on all services
Refs #2181
> Console service tweaks

- docs/developers/build.md
- docs/developers/index.md
- docs/install/cliinstaller.md
- docs/install/config.md
- docs/install/instructions.md
Docs: Adding some notes regarding building known and vagrant
Clarification
> Docs: Adding some notes regarding building known and vagrant

- Idno/Core/Logging.php
- IdnoPlugins/Checkin/templates/default/entity/Checkin/edit.tpl.php
- IdnoPlugins/Comic/templates/default/entity/Comic/edit.tpl.php
- IdnoPlugins/Like/templates/default/entity/Like/edit.tpl.php
- IdnoPlugins/Media/templates/default/entity/Media/edit.tpl.php
- IdnoPlugins/Photo/templates/default/entity/Photo/edit.tpl.php
- IdnoPlugins/StaticPages/templates/default/staticpages/admin.tpl.php
- known.php
- languages/processfile.php
Applied some of the missing PHPCS fixes to certain files
They were missed in the last patch
> Adding some PHPCS files missed last time

- phpcs/known.xml
> Updated PHPCS rules to be in line with real usage

- Idno/Common/Entity.php
- IdnoPlugins/Checkin/Checkin.php
- IdnoPlugins/Checkin/languages/checkin.pot
- IdnoPlugins/Comic/Comic.php
- IdnoPlugins/Comic/languages/comic.pot
- IdnoPlugins/Event/Event.php
- IdnoPlugins/Event/RSVP.php
- IdnoPlugins/Event/languages/event.pot
- IdnoPlugins/Like/Like.php
- IdnoPlugins/Like/languages/like.pot
- IdnoPlugins/Media/Media.php
- IdnoPlugins/Media/languages/media.pot
- IdnoPlugins/Photo/Photo.php
- IdnoPlugins/Photo/languages/photo.pot
- IdnoPlugins/Status/Status.php
- IdnoPlugins/Status/languages/status.pot
- IdnoPlugins/Text/Entry.php
- IdnoPlugins/Text/languages/text.pot
Missing translations plus a couple more things.
Added everything in #2195 plus a few more that I missed.
Closes #2195
> Indieweb Ox 2

- Idno/Core/Bonita/Forms.php
- IdnoPlugins/Comments/Pages/Post.php
- IdnoPlugins/Comments/templates/default/comments/public/form.tpl.php
Added a function to do form name obfuscation
DRY
> Adding form name obfuscation function

- docs/developers/commit-messages.md
Adding spacing
So that it renders correctly in github
> Docs: Spacing tweak

- Idno/Common/Entity.php
- Idno/Common/JSONLDSerialisable.php
- Idno/Entities/User.php
- Idno/Files/FileSystem.php
- Idno/Pages/User/View.php
- IdnoPlugins/Checkin/Checkin.php
- IdnoPlugins/Media/Media.php
- IdnoPlugins/Photo/Photo.php
- IdnoPlugins/Text/Entry.php
- Tests/API/HSTSTest.php
- languages/source/known.pot
- templates/default/shell.tpl.php
- templates/default/shell/structured-data.tpl.php
Adding JSON+LD support
Adds json+ld for site itself (including search function in google), user (including linking to social media posts), blog post, photos and media.
Structured data support is sort of the thing these days.
I'd love @edent 's input on this, as I understand this is right up your ally.
> Adding JSON+LD support

- IdnoPlugins/Checkin/Checkin.php
Using HTTPS rather than HTTP
The correct address is now https.
> Using HTTPS rather than HTTP

- .gitignore
- templates/default/robot/post.tpl.php
- templates/default/robot/wizard.tpl.php
Translation hooks for warmup robot strings
For future translation
> i18n: adding translations to warmup robot

- Idno/Common/Entity.php
- Idno/Entities/User.php
- Idno/Pages/Session/CurrentUser.php
* Tidied the currentUser json
* Added a couple of extra fields to user export json
* Added updated timestamp to default entity json export
* Been playing around with api some more
> Tidying up a couple of views

- Idno/Core/Template.php
- templates/default/content/syndication.tpl.php
* changed form-fields to formFields
* Better handling of arrays
So that the api can be more easily parsed.
> Improve form documentation code

- .github/CODEOWNERS
Adding CODEOWNERS file.
This sets automatic owners of Known components for the purposes of setting automatic code review requiests.
> Adding CODEOWNERS file.

- IdnoPlugins/IndiePub/Pages/MicroPub/Endpoint.php
- IdnoPlugins/Photo/Photo.php
* Handle situations when single files are uploaded using the faked $_FILES array
* No longer inline photo images
'twas broken.
> Fixing micropub single photos

- Idno/Core/Plugins.php
- Idno/Core/Webservice.php
- Idno/Pages/Service/Notifications/NewNotifications.php
- phpcs/known.xml
- templates/default/shell/structured-data.tpl.php
- warmup/CLI/CLIInstaller.php
- warmup/WebInstaller.php
- warmup/templates/default/pages/elements/messages.tpl.php
- warmup/templates/default/pages/requirements.tpl.php
- warmup/templates/default/pages/settings.tpl.php
* Remove /external from PHPCS 
* Apply PHPCS filters to some files
> PHPCS tweaks

- IdnoPlugins/IndiePub/Pages/MicroPub/Endpoint.php
Capture pings to the endpoint to aid debug.
> Adding some debug to micropub endpoint

- IdnoPlugins/IndiePub/Pages/MicroPub/Endpoint.php
Hopefully address the double photo issue, and a number of other things
Refs #2267
> A collection of Micropub Endpoint tweaks

- CONTRIBUTING.md
Replicating changes in #2271, for CONTRIBUTING.md
> Use HTTPS urls by default... redux.

- Idno/Core/Vendor.php
There's no need to collect it.
> Reduce information sent in vendor ping

- CONTRIBUTING.md
- docs/community/contributors.md
Added myself to the list of core contributors
Check out my phat stats: https://github.com/idno/known/graphs/contributors
> Shamelessly adding myself to the list of core contributors

- .travis.yml
- Tests/Common/EntityTest.php
- Tests/Core/PermalinkStructureTest.php
- Tests/Core/SessionTest.php
- Tests/Data/AccessGroupTest.php
- Tests/Data/DataConciergeTest.php
- Tests/KnownTestCase.php
- Tests/Pages/HomepageTest.php
- Tests/_shims.php
- Tests/build/travis-ci-apache
Modernising Travis CI installation scripts
They are currently broken, so I've attempted to modernise the script based on work I've done elsewhere.
Closes #2344
> FIX: Updating Travis CI script

- .gitignore
- Idno/Core/Plugins.php
- Idno/Pages/Admin/Plugins.php
- phpunit.xml
Adds support for IdnoPlugins.local directory
To do this I:
* Created enable/disable methods to the Plugins class
* Fixed a few bugs
* Hid non-plugin directories from the plugins admin page
Closes #2327 
It seemed like a good idea, and helps when building plugins using the vagrant build
> Adds support for IdnoPlugins.local directory

- .github/pull_request_template.md
Add a checkbox prompting for a unit test
We should get into the habit of running all existing unit tests against committed branches, regardless of the current state of Travis.
> Add a checkbox prompting for a unit test

- Idno/Data/Sqlite3.php
Fixing SQLite3 order by query
Fixing a regression introduced in a previous commit.
> Fixing SQLite3 order by query

- Idno/Files/CDNStoreable.php
Added an interface to allow for CDN storable files
To support direct URL for a file stored on a CDN (for use with IPFS etc)
Refs #2322
> Introducing storage interface for CDN Stored files

- Idno/Data/Sqlite3.php
Deprecate SQLite3 support
This does not seem to be widely used, and I'd prefer to minimise the amount of stuff we have to maintain.
Closes #2356
> Deprecate SQLite3 support

- .travis.yml
Adding PHP 7.3 support to travis ci
PHP 7.3 is stable
> Adding PHP 7.3 support to travis ci

- composer.json
Adding extension requirements to composer.json
Seemed a good idea to add platform reqs to the proposed new installer
> Adding extension requirements to composer.json

- README.md
- docs/install/upgrade.md
Adding some notes about composer in upgrade docs
Clarify upgrade info for github users
> Adding some notes about composer in upgrade docs

- README.md
Fix build status
Status is case sensitive, and repo has changed
> Fixing build status

- Idno/Common/Page.php
On investigating #2388 I spotted a potential issue with detection.
One of the SSL detection tests had faulty logic.
Closes #2388 ... hopefully.
> Fixing a potential SSL detection bug

- .gitignore
Ignore composer.phar
Preventing the inevitable accidental commit in the future.
> Ignore composer.phar

- .gitignore
Removing fontello reference
Spring cleaning
> Fontello config not used, removing

- IdnoPlugins/Comments/templates/default/comments/public/form.tpl.php
Hide bot honeypot using pure javascript
They've adapted.
> Hide bot honeypot using pure javascript

- Idno/Pages/Account/Register.php
Use the main template (or onboarding template) for page registration
Closes #2402
> Use the main template (or onboarding template) for page registration

- docs/install/data_migration.md
Fixing markdown
For some reason, a space was needed to get markdown to parse the bullet points.
> Fixing markdown

- Idno/Pages/Search/Mentions.php
Adding search hook on mentions endpoint for extension
It would be handy to improve user search and cross platform mentions. I don't have time to necessarily do this right now, but others have expressed an interest. This should make it easier for them.
Refs #2364
Refs #1992
> Adding search hook on mentions endpoint for extension

- Idno/Pages/Admin/Diagnostics.php
- templates/default/admin/about.tpl.php
Semver.org versioning on diagnostics and about
To aid reporting, as people were getting confused between version and build.
> Semver.org versioning

- docs/developers/testing.md
Updated docs to reference new phpcs
Needed updating
> Documentation: Update phpcs docs to reference mapkyca/known-phpcs

- Idno/Core/Logging.php
- Idno/Data/AbstractSQL.php
- IdnoPlugins/Photo/Photo.php
Removing write to file logging option
Removing technical debt for a rarely used functionality.
> Removing write to file logging option

- Idno/Core/Idno.php
Removing a couple of long time deprecated functions
Removing technical debt
> Remove some technical debt

- templates/default/settings-shell/nav.tpl.php
Change admin top link location
Change a slightly confusing admin link url
Closes #2412
> Change admin top link location

- Idno/Common/Page.php
- templates/default/settings-shell/metatags.tpl.php
- templates/default/shell/metatags.tpl.php
Making page variables private
Starting with the simple stuff, lets make sure that we don't just make every variable public.
> Making page variables private

- Idno/Common/Entity.php
- Idno/Common/Page.php
- Idno/Core/Admin.php
- Idno/Core/Idno.php
* Type hinting
* Making things private that shouldn't be public
Code standards and cleanup
> Code cleanup

- Gruntfile.js
Updated the Grunt task runner for recent changes, updating watch to watch for changes in javascript and sass, and automatically refresh the build and lint the results.
To make it easier to work with known, and to edit css/javascript
> Improving task runner script

- languages/source/known.pot
Update language file
It has been a while
> Updating languages as necessary

- .travis.yml
- Idno/Core/Session.php
- Idno/Data/AbstractSQL.php
- Idno/Data/Mongo.php
- Idno/Data/MySQL.php
- Idno/Data/Postgres.php
- Idno/start.php
- Tests/_bootstrap.php
- composer.json
- known.php
- warmup/schemas/mysql/2019060501.sql
- warmup/schemas/mysql/mysql.sql
- warmup/schemas/postgres/2019060501.sql
- warmup/schemas/postgres/postgres.sql
Updated all Symfony components 
They were really fracking old, and the new class loader is supposed to be faster.
Also want to see if this addresses issues on #2446 
Includes database schema change
Closes #2448
> Roll Symfony components up to latest

- Idno/Core/Idno.php
Including missing stuff from previous symfony rollup
Missing event in upgrade
> Fixing upgrade

- Tests/API/BasicAPITest.php
- Tests/API/HSTSTest.php
- Tests/API/UploadTest.php
- Tests/Common/EntityTest.php
Removed some unnecessary debug
Used data providers on the low hanging fruit
Had 15 minutes at the end of the day and I didn't have time to get into anything more involved.
> Tidying up the tests a little bit

- Idno/Common/Page.php
`getEntity` shouldn't take a parameter.
> Removing needless parameter

- Idno/Pages/Admin/Homepage.php
Fixed Idno/Pages/Admin/Homepage to save config correctly
Fix #2479 in the same way #2468 did.
> remove reference to private variable (fixes #2479)

- .gitignore
- composer.lock
Add composer.lock file to repository
As recommended, you should include the composer.lock file in your repo, as well as the composer.json.
Especially relevant when deploying on Elastic beanstalk or similar
> Add composer.lock file to repository

- statics/db.php
Avoid notice error on db error template
Tidying things up
> Avoid notice error on db error template

- Idno/Entities/User.php
Hide published and updated date in user json
This information is sensitive and should be redacted.
> Hide published and updated date in user json

- templates/default/content/embed.tpl.php
Add closing bracket to url embed regex exclusion
Fix embed regex
> Closes #2496: Add closing bracket to url embed regex exclusion

- composer.lock
Committed new composer.lock
fixing broken submodules
> Updating composer.lock

- Gruntfile.js
- package.json
Some bugfixes
Some bugs needed fixing
> Some grunt tweaks

- templates/default/content/notification/wrapper.tpl.php
> Don't show image if one not available

- composer.json
- composer.lock
- minor fixes
- Changelog: https://www.tiny.cloud/docs/changelog/
Upgrade tinymce
General maintenance.
> Upgrade tinymce from 5.0.11 to 5.0.16

- composer.json
- package.json
- version.known
Marking a line in the sand for Known 1.0.0 Release Candidate 1
Gotta do it sometime
> Known 1.0.0-rc.1

- Idno/Core/Webservice.php
- composer.json
- composer.lock
- package.json
- version.known
> Mapkyca fixing hsts

- composer.json
- composer.lock
- languages/source/known.pot
- package.json
- templates/default/forms/input/richtext.tpl.php
- version.known
* Few minor bugfixes
* Bumping to 1.0
Because it's 'bout time
> Line in the sand

- composer.json
- composer.lock
- package.json
- version.known
Updating from @dependabot
The march continues
> Some post 1.0 updates

- composer.json
- composer.lock
Adopted a couple of projects which I now consider abandonware
These projects have been abandoned by their authors, and while we should look to replace them, lets adopt them for now.
Refs #2575
Closes #2572
> Adopting abandonware

- Idno/Core/PageHandler.php
Added some type enforcements
I was in the file anyway
> Enforce some function type definitions

- composer.json
- composer.lock
Removing all dev master dependencies
To allow safer usage of composer
> Removing all dev-master dependencies

- composer.json
- composer.lock
- package.json
- templates/default/forms/token.tpl.php
- version.known
Returning CSRF for forms when making json endpoint queries
While most (all) endpoints should be being addressed via the api, using an api token, it is still possible that in some cases you'd want to perform a standard web post without an API (e.g. session/login). 
Make this easier by including the CSRF stuff in a nice way.
> Tidy form csrf tokens for JSON requests

- Idno/Common/Page.php
- composer.json
- languages/source/known.pot
- package.json
- version.known
Added a couple of missing translation strings
A sense of completeness
> Adding a couple of missing translation strings

- Idno/Core/Email.php
- composer.json
- composer.lock
- package.json
- version.known
Upgrading to swift mailer 6
Keeping everything up to date
> Swiftmailer 6

- composer.json
- composer.lock
- package.json
- version.known
Updated a few version dependencies
To stop dependabot from nagging me
> Updating versions

- templates/default/content/embed.tpl.php
Lazy loading on embed images and iframes
Chrome supports this, so lets switch it on for stream
> Lazy loading on embed images

- Idno/Common/Entity.php
Improving JSON representation of attached files
Improve the output of attached files in json slightly (by outputting a filename as well), as this makes it easier for an api to marry up attached files with thumbnails.
> Improving JSON representation of attached files

- Idno/Common/Entity.php
- Idno/Core/Purifier.php
Removed some deprecated stuff
7.4 is out, lets get ready.
> Removing some deprecated 7.4 functionality

- README.md
Added a BrowserStack logo.
So we can get an open source BrowserStack account for testing.
> Updating README to include BrowserStack thank you

- templates/default/settings-shell.tpl.php
Making the admin interface work a bit better on smaller screens
Bugging me
> Closes #2634: Settings theme tweaks for smaller screens

- languages/source/known.pot
- templates/default/admin/import.tpl.php
Change "treated at" to "treated as"
> Fix typo in Import localised string

- languages/source/known.pot
- templates/default/robot/wizard.tpl.php
Strings truncated
Ends missing
> Fix a couple of Aleph localisation strings

- templates/default/admin/about.tpl.php
- templates/default/robot/post.tpl.php
Added open collective button to:
- About page
- Robot greeting
Nobody is going to read documentation, so lets give people a nudge
> Add Open Collective links to robot and about

- templates/default/forms/input/form-list.tpl.php
- templates/default/forms/input/input.tpl.php
Added a form list helper view
Make it a lot easier to quickly create forms
> Adding form list helper

- templates/default/forms/input/form-list.tpl.php
> Adding description text

- templates/default/forms/input/form-list.tpl.php
> Fixing required field

- Idno/Entities/Invitation.php
- languages/source/known.pot
- templates/email-text/account/invite.tpl.php
- templates/email/account/invite.tpl.php
- templates/email/shell.tpl.php
Made invite emails match localisation of site when invites created and sent
> Localise invitations

- Idno/Core/Config.php
HTTPS Proxy aware config
So that heroku button works would recognise URL
> Make Proxy aware

- templates/default/forms/input/form-list.tpl.php
> Handle hidden

- .htaccess
I had mysterious problems with file uploads, figured it out and the default 8M php upload size limits was causing problems.
Decided to add a commented entry in the .htaccess file.  Should also probably add this to the diagnostics page?  Maybe add to FAQ as well?  At least this is a start....
> Add comments to .htaccess about upload size workaround

- .github/pull_request_template.md
> Make it clearer how the ticked boxes work

- Idno/Core/Config.php
Environment aware base-config
I have setup Known on Heroku, the ephemeral filesystem made installing a royal pain. The same would be true of CloudFoundry.
> Use ENV as source of Install Config

- warmup/schemas/postgres/2016102601.sql
- warmup/schemas/postgres/postgres.sql
Postgres Schema changes
* guard statements
* unique index that was required for foreign key added
* concurrently keyword added to index creation
Using docker and heroku postgres, the SQL provided in the repository failed to create a database for a fresh install.
> Postgres warmup schema edits

- Idno/Core/Config.php
- Idno/Core/Idno.php
Fixed ENV as a source of config mapping to config, and ability to use Postgres Database driver
I had a number of issues after some clean-room redeploys. It seems some state is captured in the Known database and it made me overlook some problems.
the following branches are < 2 minute installers so the reviewer can verify these changes
| heroku deploy button | repo link | database | region's tested |
| --- | --- | --- | --- |
| [![Deploy](https://www.herokucdn.com/deploy/button.svg)](https://dashboard.heroku.com/new?button-url=https%3A%2F%2Fgithub.com%2FLewiscowles1986%2Fknown%2Ftree%2Fheroku-postgres&template=https%3A%2F%2Fgithub.com%2FLewiscowles1986%2Fknown%2Ftree%2Fheroku-postgres) | https://github.com/Lewiscowles1986/known/tree/heroku-postgres | Postgres | EU, US |
| …
> Config Changes

- Idno/Core/Config.php
- composer.json
- package.json
- version.known
> Fixing per-domain config

- Idno/Pages/Entity/View.php
- composer.json
- composer.lock
- package.json
- version.known
If there is no short description available, attempt to get a short description from the full description (truncated).
To make the meta descriptions work a little bit better.
> Refs #2624: Handle descriptions better

- composer.json
- composer.lock
Adding a Postgres dev environment
It's hard to test, as I'm entirely mysql for the most part
> Adding docker dev container

- composer.json
- package.json
- version.known
> Version bump

- Idno/Data/Postgres.php
- composer.json
- docs/install/requirements.md
- package.json
- version.known
Flagging Postgres as deprecated
I have no time to maintain Postgres going forward, so moving this into the community
> Marking Postgres as deprecated

- Idno/Data/MySQL.php
Apply updates as a transaction
Hopefully make the DB patching a little bit more robust
> Adding transaction and rollback to database update

- Idno/Core/Logging.php
PHP 8 compatibility
Change
Only one thing spotted so far, but will poke
> PHP 8 Compatible

- Idno/Data/MySQL.php
Known now checks for MySQL transactions before trying to roll one back.
Known was attempting to roll back transactions if we weren't in one, causing a 500 error. This was particularly problematic on first installation.
> Ensure we don't rollback a transaction if we're not in one
